### ISSUE TITLE
Specify region

### ISSUE THREAD

**Issue by mike-seagull** [bubuntux/nordvpn#1]
How would you specify a region?

Looking at nordVpn.sh, it looks like it makes a request to the NordVPN API to get a server recommendation, but it would most likely get back a server that is close by. How could a specify that I want a server in another county?

**Comment by bubuntux** [comment]
i believe nordVpn will return the best server for you, so i'm hoping is one close to you, not sure tho, i had in mind adding parameter to specify server type and country, but as right now the container is working for my needs.
i'll be more than glad to accept a pull request with the change if you make something like that

**Comment by bubuntux** [comment]
Thanks to @azinchen contributions now, country, category, protocol and max load is not configurable
