### ISSUE TITLE
Killswitch Disabled?

### ISSUE THREAD

**Issue by cyb3rl4d** [bubuntux/nordvpn#100]
In the readme it says that kill switch is operational/enabled but when I do a 'nordvpn settings' is shows 'Kill Switch: disabled'. Is this correct? Is the 'killswitch' feature mentioned in the readme iptables rule config and so not using nordvpn's killswitch capability?

Looking at other issues the nordvpn killswitch seems to be disabled in debug output so I think I'm good but just wanted to confirm. I haven't seen anyone talk about this before in issues.

Thanks and great work btw!

**Comment by bubuntux** [comment]
kill switch is on using iptables, the "feature" on nordvpn binary has a few issues, using iptables is safer for this use case, review  [start_vpn.sh](https://github.com/bubuntux/nordvpn/blob/master/start_vpn.sh) if you want to see how it works
