### ISSUE TITLE
Unable to stablish connection with 3.8.0+ version

### ISSUE THREAD

**Issue by bubuntux** [bubuntux/nordvpn#103]
**Describe the bug**
Latest version 3.8.0 fails to connect

**Comment by bubuntux** [comment]
Seems to be an issue with the nordvpn binary, we may have to wait for a fix on their end, 
**use version 3.7.4 for now**

`docker run ... bubuntux/nordvpn:3.7.4`

**Comment by musician2000** [comment]
Just to add, getting the me problem here in the UK, since the latest release of this container.. changed to 3.7.4 and all working great! thanks

**Comment by jonathan-bloodworth** [comment]
I've downgraded back to 3.7.4 but unfortunately getting the same issue as before:

Whoops! We couldn't connect you to 'United_Kingdom'. Please try again. If the problem persists, contact our customer support.

**Comment by AlexMinty** [comment]
Unable to connect, this is the only error i see in the logs.

[Error] disabling IPv6: sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system

broke when merging IPv6 support?

**Comment by jonathan-bloodworth** [comment]
Booted up the older image this morning and now all is working (weird), tried the latest image but problem still persists but like @musician2000 3.7.4 is still working.

**Comment by musician2000** [comment]
Hi, my setup runs a cron job every night to get the latest version and update it the current version running, so tweaked it to only get version 3.7.4 at the moment, it rebuilt last night and still working ok, fully connected to nordvpn..  my docker create code is this if it helps, Ignore all the ports, I have a lot of ports added as have several containers that connect to it, so I can still access them `docker create -ti --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -p 8118:8118 -p 8989:8989 -p 8080:8080 -p 9090:9090 -p 7878:7878 -p 5076:5076 -p 9117:9117 -p 8112:8112 -e NETWORK=192.168.1.0/24 -e USER=xxxxxxx -e PASS='xxxxxxxx' bubuntux/nordvpn:3.7.4`

**Comment by eriklysoe** [comment]
I get same problem with version 3.7.4

Whoops! We couldn't connect you to 'Norway'. Please try again. If the problem persists, contact our customer support.

**Comment by larivierec** [comment]
Same. I also tried 3.8.1 same issue.
I also downgraded however, connection doesn't stay up is that normal?

**Comment by AlexMinty** [comment]
> Booted up the older image this morning and now all is working (weird), tried the latest image but problem still persists. Like @musician2000 has mentioned 3.7.4 is still working.

I'm in the same boat, tried 3.8.1 but issue persists. I was getting permission errors with resolv.conf. downgrading to 3.7.4 works fine

**Comment by bubuntux** [comment]
i submitted an issue to NordVpn support, their response:

> We have noticed an increased issue with 3.8.0 and are working on a fix.
> Should be solved within the upcoming updates.
> For now, I would recommend sticking to 3.7.4

no tracking number or anything, we would need to keep an eye on updates and hope they fix their shit =/ 
https://nordvpn.com/blog/nordvpn-linux-release-notes/ 

So for now just keep using 3.7.4

**Comment by gabrielwhite** [comment]
3.8.3 still has this problem.

**Comment by Ansem93** [comment]
3.8.4 is out, let's see if they fixed it :/ waiting for the container to auto-update.

**Comment by bubuntux** [comment]
> 3.8.4 is out, let's see if they fixed it :/ waiting for the container to auto-update.
> Apparently it still doesn't fix it. Tomorrow i'll write to nordvpn, it's just better to give them as much feedback as possible.

3.8.4 still fails

**Comment by sorryusernameisalreadytaken** [comment]
How can I temp. downgrade to a working version? docker exec....?

**Comment by jackwilsdon** [comment]
@sorryusernameisalreadytaken specify the verssion number in your `run` command as @bubuntux suggested:

```
docker run ... bubuntux/nordvpn:3.7.4
```

**Comment by jhuesos** [comment]
@sorryusernameisalreadytaken if you use docker-compose, update in your `docker-compose.yml` file this line from this

```
image: bubuntux/nordvpn
```

to

```
image: bubuntux/nordvpn:3.7.4
```

That means you should go back and remove that version number when it is fixed or you will be stuck with this version forever :)

**Comment by klara31** [comment]
Any news or progress on this issue?

**Comment by bubuntux** [comment]
> Any news or progress on this issue?

Version 3.8.5 still broken, we need to bug nordvpn about this.

**Comment by paskalll** [comment]
I need to add --sysctl net.ipv6.conf.all.disable_ipv6=0 to the container and 3.8.0+ works.
Better to activate ipv6? I am not sure but at least this will make it work. May it helps to found the real problem this is more a dirty workarround.

**Comment by alikasundara** [comment]
Similar issue with 3.8.6 
```
Whoops! We couldn't connect you to 'P2P'. Please try again. If the problem persists, contact our customer support.                                                                                                

nordvpn    | App Version: 3.8.6                                                                                                                                                                                   
nordvpn    | OS Info:                                                                                                                                                                                             
nordvpn    | PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```

**Comment by larivierec** [comment]
> 
> 
> Similar issue with 3.8.6
> 
> ```
> Whoops! We couldn't connect you to 'P2P'. Please try again. If the problem persists, contact our customer support.                                                                                                
> 
> nordvpn    | App Version: 3.8.6                                                                                                                                                                                   
> nordvpn    | OS Info:                                                                                                                                                                                             
> nordvpn    | PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> ```

based on this, it believe it's still broken?

**Comment by gabrielwhite** [comment]
Anyone had luck with 3.8.7 (pushed a few hours ago)?

**Comment by tlai88** [comment]
No luck, 

Whoops! We couldn't connect you to **'X'.** Please try again. If the problem persists, contact our customer support.

**Comment by bubuntux** [comment]
doesn't seems like nordvpn have intentions to fix the issues, i fixed the version to 3.7.4 and remove the automatic updates, i migrate things to a more manual update format, should be safe to use latest tag again (will be using 3.7.4 binary)

**Comment by wayne-robinson** [comment]
Just tried with the latest version (v1.0) and can confirm the problem is resolved when using the instructions in https://github.com/bubuntux/nordvpn#docker-compose-example-without-web-proxy

**Comment by adrawdet** [comment]
Pulled the latest version on Docker. Looks to be working now.

**Comment by AlexMinty** [comment]
is there any harm in staying on 3.7.4 for the time being? I'm generally in the 'if it aint broke don't fix it' camp

**Comment by obbardc** [comment]
> Pulled the latest version on Docker. Looks to be working now.

...

> is there any harm in staying on 3.7.4 for the time being? I'm generally in the 'if it aint broke don't fix it' camp

the latest docker tag pulls version 3.7.4 as a workaround. I guess this workaround will stick around until NordVPN fix their client.

**Comment by AlexMinty** [comment]
> > Pulled the latest version on Docker. Looks to be working now.
> 
> > is there any harm in staying on 3.7.4 for the time being? I'm generally in the 'if it aint broke don't fix it' camp
> 
> the latest docker tag pulls version 3.7.4 as a workaround. I guess this workaround will stick around until NordVPN fix their client.

Thanks for the speedy response. I’ll leave it on 3.7.4 until Nord does a fix

**Comment by obbardc** [comment]
But if you update your docker tag and pull from  latest you will possibly
get some extra bug fixes ;-)

**Comment by r4ph0u** [comment]
Just tried with version 3.7.4 but it still doesn't connect

**Comment by frasy** [comment]
Hi @bubuntux, it seem there is a new Release 3.8.10 on which notes says ```Fixed: NordVPN runs smoothly again on Ubuntu 18.04.```

Have you given this a try yet?

**Comment by 5t4cktr4c3** [comment]
So I just tested the new version by upgrading using `apt-get update; apt-get install --reconfigure nordvpn`. After that I restarted the container, but got `Whoops! /run/nordvpn/nordvpnd.sock not found` on `nordvpn status`. `service nordvpn stop; service nordvpn start` did the trick to get it returning `Status: Disconnected` again. 
Since then it seems like the socket has moved from `/run/nordvpnd.sock` to `/run/nordvpn/nordvpnd.sock`. However, the `start_vpn.sh` script waits for the socket on `/run/nordvpnd.sock` and sleeps until it has been created. So it will `sleep 0.25` forever, since it will never show up at the mentioned path and therefore the connection will never be established.
In the next few days I'll try to modify the path in the connection script and share my results here.

**Comment by Buntelrus** [comment]
I build the image with version `3.8.10` and get now following error:
```
vpn_1  | 2021/01/22 18:57:51 [Info] Daemon has started
vpn_1  | 2021/01/22 18:57:51 Error on listening to UNIX domain socket: listen unix /run/nordvpn/nordvpnd.sock: bind: no such file or directory
```

hope that helps.

**Comment by 5t4cktr4c3** [comment]
For debugging purposes I installed additionally `host`, `iputils-ping` and `nano`. I also ran `apt-get autoremove.`
As also stated by @Buntelrus, the daemon exits with `Error on listening to UNIX domain socket: listen unix /run/nordvpn/nordvpnd.sock: bind: no such file or directory`. In my case it helped starting and stopping the daemon by `service nordvpn start; servie nordvpn stop`. We stop the daemon because the daemon is intended the run as the `vpn` group from the `start_vpn.sh` script.
The container will then exit. Simply start it again and the VPN will connect successfully. Curling by `curl ifconfig.me` does not work. Running it as the `vpn` groups works. The traffic is still being redirected through the VPN, as `nordvpn status | grep "Your new IP"` returns in my case `Your new IP: 195.181.170.199`. `curl ifconfig.me` returns `195.181.170.200`. The reason why the IP is not the exact same is because of entry and exit IPs, this is what someone from the NordVPN support team explained to me. However, curling with `HTTPS` does not work with my setup. Curling with verbose output (`sg vpn -c "curl -v https://ifconfig.me"`) gets stuck after the following lines:
```
* Rebuilt URL to: https://ifconfig.me/
*   Trying 216.239.32.21...
* TCP_NODELAY set
* Connected to ifconfig.me (216.239.32.21) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
^C
```
So as far as I got means that we have an issue with IPtables as soon as the VPN connection is established. `iptables -L` returns:
```
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -s 195.181.170.199/32 -i eth0 -j ACCEPT
-A INPUT -s 172.17.0.0/24 -i eth0 -j ACCEPT
-A INPUT -i eth0 -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.024 -j ACCEPT
-A FORWARD -s 172.17.0.0/24 -j ACCEPT
-A OUTPUT -d 195.181.170.199/32 -o eth0 -j ACCEPT
-A OUTPUT -d 172.17.0.0/24 -o eth0 -j ACCEPT
-A OUTPUT -o eth0 -j DROP
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -m owner --gid-owner 101 -j ACCEPT
-A OUTPUT -d 172.17.0.0/24 -j ACCEPT
```
Would be happy to help :)

**Comment by GJRTimmer** [comment]
> I build the image with version `3.8.10` and get now following error:
> 
> ```
> vpn_1  | 2021/01/22 18:57:51 [Info] Daemon has started
> vpn_1  | 2021/01/22 18:57:51 Error on listening to UNIX domain socket: listen unix /run/nordvpn/nordvpnd.sock: bind: no such file or directory
> ```
> 
> hope that helps.

Easy fix, because the socket was moved the directory has to be created first
The following has to be added to the script:
```bash
if [ ! -d /run/nordvpn ]; then
    mkdir /run/nordvpn
fi
```

**Comment by janstadt** [comment]
Anyone have a working fork with the latest nordvpn binary? Would love to get this working. Been using the pinned version for months and i am having some serious stability issues. I dont see anything weird in the logs or anything. Hoping an update fixes it up.

**Comment by 5t4cktr4c3** [comment]
@janstadt You may wanna try the image I just published on GitHub and Docker Hub.

**Comment by janstadt** [comment]
> @janstadt You may wanna try the image I just published on GitHub and Docker Hub.

Cool thanks will look into it. Any chance you can push a PR to the main @bubuntux repo? Also, i see in the readme that you changed the example to us openvpn. Have you tested it out using NordLynx as well?

**Comment by sUyMur** [comment]
It’s already there: https://github.com/bubuntux/nordvpn/pull/139

**Comment by rundx** [comment]
> @janstadt You may wanna try the image I just published on GitHub and Docker Hub.

It's not just the socket path that needs fixing there is a problem with iptables rules 
nordvpn will connect just fine but no internet outside of vpn system group and linked containers will have no internet too

**Comment by 5t4cktr4c3** [comment]
> Have you tested it out using NordLynx as well?
I couldn't solve it yet, see my tries here: https://github.com/bubuntux/nordvpn/issues/103#issuecomment-765899973

> It's not just the socket path that needs fixing there is a problem with iptables rules
> nordvpn will connect just fine but no internet outside of vpn system group and linked containers will have no internet too
In my setup it works fine, you may want to test it with my network environments to see if it works for you then.

**network**:
`docker network create -d bridge --subnet=192.168.1.0/24 --ip-range=192.168.1.0/24 --gateway=192.168.1.1 --opt "com.docker.network.bridge.name"="mynet" --opt "com.docker.network.bridge.enable_ip_masquerade"="true" --opt "com.docker.network.bridge.enable_icc"="true" --opt "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0"  --opt "com.docker.network.driver.mtu"="1350" mynet`

**nordvpn container**:
`docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn --sysctl net.ipv4.conf.all.rp_filter=2 -e USER=USER -e PASS="PASS" -e CONNECT=DE -e NETWORK="192.168.0.0/24" -e DNS=192.168.0.1 -e TZ=Europe/Berlin -d --network mynet -d --restart unless-stopped -p 8765:80 5t4cktr4c3/nordvpn`

**speedtest container** (for testing - you need to clone the git repository of the speedtest project to your home directory):
```
docker run --name=speedtest \
      -d \
      --network container:vpn \
      -v "$HOME/Speedtest-Tracker/config":/config \
      -e OOKLA_EULA_GDPR=true \
      --restart unless-stopped \
      henrywhitaker3/speedtest-tracker:latest-arm
```

**Comment by klara31** [comment]
@bubuntux Any update on when these changes will be pushed to git? Thanks!

**Comment by sUyMur** [comment]
Nice, thanks! :-)

**Comment by bubuntux** [comment]
i merged the changes from @5t4cktr4c3 but they don't quite work for me.. anyone else can test ?

**Comment by bubuntux** [comment]
changes were reverted, dns is not resolving properly i need to do more testing, for now rolling back to an stable version
