### ISSUE TITLE
Failed Starting vpn : Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device \"/dev/net/tun\": no such file or directory

### ISSUE THREAD

**Issue by adriancossu** [bubuntux/nordvpn#107]
I can't seem to create the stack in portainer using docker-compose. I keep getting the error that stating: 

Failed Starting vpn : Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device \"/dev/net/tun\": no such file or directory

**To Reproduce without docker CLI**
version: "2"
services:
  vpn:
    image: bubuntux/nordvpn:3.7.4  #Using this version since to solve the reported connection issues
    network_mode: bridge        
    cap_add:
      - NET_ADMIN               
      - SYS_MODULE               
    devices:
      - /dev/net/tun
    environment:
      - USER=
      - "PASS="
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24 
      - TZ=Europe
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  qbit:
    image: linuxserver/qbittorrent
    container_name: qbit_nord
    environment:
      - PUID=1026
      - PGID=101
      - TZ=America/Toronto
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /volume1/Configs/qbit3:/config
      - /volume1/Downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn

**Logs**

time="2020-09-21T21:27:14Z" level=error msg="Failed Starting vpn : Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device \"/dev/net/tun\": no such file or directory",
time="2020-09-21T21:27:14Z" level=info msg="[0/2] [qbit]: Starting ",
time="2020-09-21T21:27:15Z" level=error msg="Failed Starting qbit : Error response from daemon: cannot join network of a non running container: 10ebac9b0bc45633acb655acaba1be1171bff70fdac757f1ea6155007de0ff23",
time="2020-09-21T21:27:15Z" level=error msg="Failed to start: vpn : Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device \"/dev/net/tun\": no such file or directory",
time="2020-09-21T21:27:15Z" level=error msg="Failed to start: qbit : Error response from daemon: cannot join network of a non running container: 10ebac9b0bc45633acb655acaba1be1171bff70fdac757f1ea6155007de0ff23",
2020/09/21 21:27:15 http error: Error response from daemon: cannot join network of a non running container: 10ebac9b0bc45633acb655acaba1be1171bff70fdac757f1ea6155007de0ff23 (err=Error response from daemon: cannot join network of a non running container: 10ebac9b0bc45633acb655acaba1be1171bff70fdac757f1ea6155007de0ff23) (code=500),
time="2020-09-21T21:27:12Z" level=info msg="[0/2] [vpn]: Starting ",
Creating network "qbitnord_default" with driver "bridge"

**Comment by bubuntux** [comment]
execute vpn container only and include -e DEBUG=on
wondering if you are reaching 
`create_tun_device `
in the startup script, please follow the bug template instructions

**Comment by adriancossu** [comment]
Fixed by following this: https://ruimarinho.github.io/post/fix-tun-tap-not-available-on-a-synology-nas/
