### ISSUE TITLE
Add fail2ban support

### ISSUE THREAD

**Issue by klara31** [bubuntux/nordvpn#113]
**Is your feature request related to a problem? Please describe.**
When I check the openvpn logs, I see a lot of IP addresses trying to gain access to my server. These IP's can easily be frustrated by blocking them, using fail2ban.

**Describe the solution you'd like**
Add fail2ban with a filter on OpenVPN

**Describe alternatives you've considered**
Alternative solutions to block these IP's would be quite complex, I guess...

**Additional context**
Added security!

**Comment by Groofster** [comment]
As far as I know NordVPN does not support port forwarding anymore. So as far as I know there is nothing to be banned and/or blocked.

**Comment by klara31** [comment]
You're right, I am mixing up some stuff and made a wrong conclusion...
