### ISSUE TITLE
some of X-Digest, X-Authorization headers are missing

### ISSUE THREAD

**Issue by alexanderryan4** [bubuntux/nordvpn#120]
Getting this issue above when running my container in docker.  I've been having tons of issues lately starting yesterday when the container just wouldn't work so I've recreated it multiple times and that is the current error I get.  I've tried running it from a stack and from just straight-up visually composing it in create container and I still can't get it to work.  Let me know if you need any additional details to solve the issue.

**Comment by kimpenhaus** [comment]
@alexanderryan4 did you managed to get this solved? facing the same issue after pulling the latest docker image - even switching to older releases won't fix it again... might this be related to nord vpn having server issues?

**Comment by alexanderryan4** [comment]
I use portainer so I'll leave my docker-compose stack below if that's any help.  You actually need to roll your image back to image: bubuntux/nordvpn:3.7.4 due to some issue with nordVPNs setup, it's a bug that's been going on for quite a while now.  I can't remember if I still had this issue after I did this or not, but I just ended up recreating the portainer and it worked for me, but your main fix will probably be rolling back your image to version 3.7.4  The stack I now use is down below
`  vpn:
    image: bubuntux/nordvpn:3.7.4
#    network_mode: bridge
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - TECHNOLOGY=NordLynx
      - CONNECT=United_States
      - SUBDOMAINS=wildcard
      - NETWORK=192.168.1.0/24
      - PASS=
      - USER=
    ports:
      - 9117:9117 #jackett
      - 34400:34400 #xteve
      - 9091:9091 #transmission
      - 51413:51413 #transmission
      - 51413:51413/udp #transmission
      - 8989:8989 #Sonarr
      - 7878:7878 #Radarr
    restart: unless-stopped`

**Comment by kimpenhaus** [comment]
@alexanderryan4 thanks for your response - tried several different tags already (3.6.x - 3.7.x) - none of them is working anymore... just can't figure out what changed on my site :( I've just pulled a new image deleted the old container and created a new one... damn it

**Comment by Pfuenzle** [comment]
Same for me, only error I get is
-2021/01/26 17:00:29 some of X-Digest, X-Authorization headers are missing

**Comment by bubuntux** [comment]
seems like an issue with nordvpn itself, not this container
