### ISSUE TITLE
Terminate the container successfully.

### ISSUE THREAD

**Issue by Rouryi** [bubuntux/nordvpn#121]
**Is your feature request related to a problem? Please describe.**
When stopping the container with docker-compose, it does not exit normally (Exit 0), but is forced to exit (Exit 137).

>  Code 137 means your app catched SIGKILL that means Unexpectedly Closed. This is not good for your apps and this article describes how to fix it.

**Describe the solution you'd like**
I found a way to terminate the container successfully.
Could it be used in this container as well?
https://gist.github.com/hiroaki-yamamoto/4e27167dd3cb74700ce86e678ff987cc

**Additional context**
![docker](https://user-images.githubusercontent.com/18416118/100191587-badfd180-2f33-11eb-9ceb-f8d1ef9e73a9.png)

**Comment by bubuntux** [comment]
i believe this is fix in the latest version
