### ISSUE TITLE
Kill Switch missing iptables OUTPUT for nordlynx

### ISSUE THREAD

**Issue by mcteixeira** [bubuntux/nordvpn#128]
Hello,

Shouldn't this line be added to start_vpn.sh script for nordlynx interface?

`**iptables -A OUTPUT -o nordlynx -j ACCEPT**`

Like the ones below for TUN/TAP interfaces:

```
**iptables -A OUTPUT -o tap+ -j ACCEPT
iptables -A OUTPUT -o tun+ -j ACCEPT**
        
```

Thanks

**Comment by bubuntux** [comment]
this change is already in master
