### ISSUE TITLE
country specification broken?

### ISSUE THREAD

**Issue by lavaguy1** [bubuntux/nordvpn#14]
my existing compose file got borked in one of the newer releases... i also had the "invalid uername" issue, which seems to be fixed now,. But I'm having a problem with specifying multiple countries with the "COUNTRY=" parameter. Previously, "COUNTRY=us;Switzerland;Germany" worked fine. Now it's returning an error:

Whoops! We can't connect you to 'us;ch;de'. Please try again. If the problem persists, contact our customer support.

Using just "COUNTRY=us" works...

Any ideas? 

Thanks!

*EDIT - I also tried "COUNTRY=US;CH;DE" -which also didn't work... ;)

**Comment by bubuntux** [comment]
The latest version uses the official nordvpn client, unfortunately it's limited to only specify one country, the old version also just connect to one country but select any from the list, the server selection was not the best and cause a lot of issues, mostly slow connections and high latency, using the official version guarantee a better, faster and reliable connection, i added a change to keep the previous value backward compatible, just keep in mind it will only use the first country for now.

also if you want to keep using the old version there is a tag available for it, amd64-old and arm-old

thanks for you report!

**Comment by lavaguy1** [comment]
Thanks! I‘ll keep that in mind!
