### ISSUE TITLE
Question about nginx reverse proxy integration

### ISSUE THREAD

**Issue by benfishbus** [bubuntux/nordvpn#149]
I am running nordvpn+qbittorrent via the "docker-compose example without web proxy". I have an existing reverse proxy setup (linuxserver/swag, also nginx), and I would like to configure it to reach this qbittorrent web ui. Normally that would mean putting the container on an "external network" shared with swag. But the docker-compose file says "network_mode: bridge" is required. Can I change the network without compromising vpn security or breaking the container altogether? Or should I be using the web proxy example? Looking for the simplest solution.

Thanks for any help!
Ben

**Comment by Kristof-Mattei** [comment]
You can create your own custom bridge and put it together with swag, yes.

**Comment by stx8** [comment]
> You can create your own custom bridge and put it together with swag, yes.

I actually have this exact ask too.. have been trying to create my own custom bridge, but when I do so the VPN does not have any internet access at all. I intialy wanted to create my own network but it seems swag creates its own network on startup (swag_default).

I tried to put the bubuntux container in there just to try but no connection... 

Actually, i know that on the readme of Bubuntux, the example compose shows that to use a web proxy, network_mode = bridge isn't needed but I spun up a test container and I can't connect at all whenever the network_mode = bridge line is missing.

**Comment by benfishbus** [comment]
Gave this a shot.
Commented out `network_mode: bridge` line from vpn service
Set `container_name: qbittorrent` for vpn service (to avoid having to edit the swag sample config for qbittorrent)
Appended the same "default network" definition as all my other swag'd services:
```
networks:
   default:
     external:
       name: mycustomswagnet
```
### Result:
Qbittorrent web ui successfully proxied through swag, and ipleak.net "Torrent Address detection" still shows NordVPN ip.

Still wondering if I'm missing the boat by not using the "web proxy" method, or something else altogether. Ultimately I want to be able to do this (map "admin" activity to swag/bridge, and let the rest flow to vpn container net) easily for any container.

**Comment by bubuntux** [comment]
i added examples using traefik, i would recommend it over nginx
