### ISSUE TITLE
Healthcheck override set by environment variable

### ISSUE THREAD

**Issue by mtompkins** [bubuntux/nordvpn#150]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Variable healthcheck period - the 5m + 1m start is quite long especially if there are dependent docker containers.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

We could pass an environmental variable in a manner such as ...

```
# docker-compose.yml file

version: '2'

services:
  nordvpn:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - HEALTHBEAT=5
```

**Comment by bubuntux** [comment]
you can already override the healthcheck interval 
  `  --health-interval       Time between running the check`
  please review docker documentation
