### ISSUE TITLE
Connect using IP of NordVPN Server

### ISSUE THREAD

**Issue by Jimmy-SafeCash** [bubuntux/nordvpn#157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
My NordVPN container is behind a Sophos XG firewall. I block all traffic from the container except to a specific NordVPN server IP. I want to be able to specify the server IP instead of region, country etc. I'm currently unable to restrict in the fashion I'd like to as there are a number of random URLs that are queried during connection. My existing OpenVPN solution works using a single whitelisted IP.

**Describe alternatives you've considered**
There is no solution as the URLs used during connection appear random.

**Additional context**

**Comment by bubuntux** [comment]
have you tried setting the env variable CONNECT to the specific server ?

**Comment by Jimmy-SafeCash** [comment]
> have you tried setting the env variable CONNECT to the specific server ?

I have. This is the log output.

iptables v1.6.1: host/network `api.nordvpn.com' not found


Try `iptables -h' or 'iptables --help' for more information.


2021/03/26 01:24:51 [Info] Daemon has started



-
  

-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/2021/03/26 01:24:56 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout



-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|2021/03/26 01:25:06 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": context deadline exceeded (Client.Timeout exceeded while awaiting headers)



/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|2021/03/26 01:25:11 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\2021/03/26 01:25:21 Post "https://boi9osyg1uwtyafn.com/v1/users/tokens": context deadline exceeded (Client.Timeout exceeded while awaiting headers)



|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\2021/03/26 01:25:26 Get "https://x9fnzrtl4x8pynsf.com/v1/servers/countries": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-2021/03/26 01:25:36 Post "https://icpsuawn1zy5amys.com/v1/users/tokens": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-2021/03/26 01:25:41 Get "https://2ohvff3e8v46kb8.info/v1/servers/countries": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/2021/03/26 01:25:51 Post "https://4qlnp8csnrj5zla.me/v1/users/tokens": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/2021/03/26 01:25:56 Get "https://q8uvnsgljgste3f.info/v1/servers/countries": context deadline exceeded (Client.Timeout exceeded while awaiting headers)



-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|2021/03/26 01:26:06 Post "https://w569ut7zbkiqf5b.xyz/v1/users/tokens": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|2021/03/26 01:26:31 Get "https://w569ut7zbkiqf5b.xyz/v1/helpers/ips/insights": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/2021/03/26 01:26:36 [Error] logging in: ntp check failed



  
Technology is successfully set to 'NordLynx'.


Subnet 192.168.5.0/24 is whitelisted successfully.



-
  
Please enter your login details.


Stdin/Stdout should be terminal



-
  

-
  
You are not connected to NordVPN.




2021/03/26 01:26:36 releasing /etc/resolv.conf

**Comment by bubuntux** [comment]
this request needs to be sent to nordvpn, i have no control over the nordvpn binary, since it doesn't support this feature i can add it to the container.
