### ISSUE TITLE
Healthcheck causing frequent disconnects\reconnects

### ISSUE THREAD

**Issue by ProjectVRD** [bubuntux/nordvpn#159]
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
Everytime a health check is run at the 5m interval, the NordLynx connection is disconnected and reconnected when there is a new version of the application. The application does not get updated and NordVPN reconnects.

**Expected behavior**
Healthcheck to notify of new version, disconnect and then install new version and finally reconnect.

**Code to run**
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    container_name: NordLynx
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=****@*****    # Required
      - "PASS=**********"    # Required
      - CONNECT=United_Kingdom
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.1/24 
      - TZ=Europe/London
    ulimits:                    # Recommended for High bandwidth scenarios
      memlock:
        soft: -1
        hard: -1
    ports:
      - 8080:8080 # qBittorrent
      - 7878:7878 # Radarr
      - 8989:8989 # Sonar
      - 6767:6767 # Bazarr
      - 9117:9117 # Jackett
      - 8765:80     # OoklaSpeedTest

  torrent:
    image: linuxserver/qbittorrent
    container_name: qBittorrent
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Qbittorrent:/config
      - /volume1/Downloads/Qbittorrent/Finished:/downloads
      - /volume1/Media:/mediafiles
    network_mode: service:vpn
    depends_on:
      - vpn

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: Radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Radarr:/config
      - /volume1/Media/Movies:/movies
      - /volume1/Downloads/Qbittorrent:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: Sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Sonarr:/config
      - /volume1/Media/TV Shows:/tv
      - /volume1/Downloads/Qbittorrent:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn
      
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: Bazarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Bazarr:/config
      - /volume1/Media/Movies:/movies
      - /volume1/Media/TV Shows:/tv
    network_mode: service:vpn
    depends_on:
      - vpn 
      
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: Jackett
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Jackett:/config
      - /volume1/Downloads/Qbittorrent/TorrentWatchFolder:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn 
      
  speedtest:
    image: henrywhitaker3/speedtest-tracker
    container_name: OoklaSpeedTest
    volumes:
      - /volume1/docker/OoklaSpeedTest:/config
    environment:
      - PGID=1026
      - PUID=101
      - TZ=Europe/London
      - OOKLA_EULA_GDPR=true
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "200k"
    network_mode: service:vpn
    depends_on:
      - vpn 
      
      
# The torrent service would be available at https://localhost:8080/ or anywhere inside the local network http://192.168.1.xxx:8080

**Logs**
/bin/sh: 1: test: =: unexpected operator - A new version of NordVPN is available! Please update the application. - \ | You are disconnected from NordVPN. How would you rate your connection quality on a scale from 1 (poor) to 5 (excellent)? Type 'nordvpn rate [1-5]'. - A new version of NordVPN is available! Please update the application. - \ | Connecting to United Kingdom #2109 (uk2109.nordvpn.com) - You are connected to United Kingdom #2109 (uk2109.nordvpn.com)! -

**Additional context**
System: Synology DS220+
OS: DSM 6.2.3

**Comment by bubuntux** [comment]
unable to reproduce this issue
