### ISSUE TITLE
Enable aarch64

### ISSUE THREAD

**Issue by w0ndersp00n** [bubuntux/nordvpn#17]
Right now x86-64 and armhf are supported. Is it possible to add support for aarch64 as well?

**Comment by bubuntux** [comment]
Yes, I'm actually working on it, seems like the binary didn't play well with the base image I'm using, I'll switch it up and notify here

**Comment by bubuntux** [comment]
I don't have an aarch64 device to properly test it but tag bubuntux/nordvpn:2.2.0-2-dev should be compatible, can you test it and let me know if it works?

**Comment by w0ndersp00n** [comment]
I just tested it, but it stops after showing these messages:

```
 /usr/bin/entry.sh: line 55: /bin/sh: cannot execute binary file: Exec format error
 /usr/bin/entry.sh: line 55: /bin/sh: Success
 /usr/bin/entry.sh: line 55: /bin/sh: cannot execute binary file: Exec format error
 /usr/bin/entry.sh: line 55: /bin/sh: Success
```
It seems the architecture for sh is incorrect, though I don't receive anymore logging information.

**Comment by w0ndersp00n** [comment]
I think the issue might be here in the Dockerfile:

```curl "https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn_${NORDVPN_BIN_VERSION}_${NORDVPN_BIN_ARCH}.deb" -o /tmp/nordvpn.deb && \```

Before that line ```NORDVPN_BIN_ARCH``` is declared, however as ```AMD64```, which I assume doesn't work on ARM. Shouldn't that also be ```aarch64``` in this case?

**Comment by bubuntux** [comment]
nah, seems like the binary is not compatible for some reason

https://github.com/bubuntux/nordvpn/blob/master/hooks/build

docker build -f $DOCKERFILE_PATH --build-arg ARCH=aarch64 --build-arg NORDVPN_BIN_ARCH=aarch64 -t "${DOCKER_REPO}:aarch64-${VERSION}" .

is building the aarch64 image with the aarch64 binary, but for some reason it doesn't work...
i actually have a version working with pure openvpn, i'm just working on a better server selection and adding extra parameters, should be ready to go soon

**Comment by w0ndersp00n** [comment]
I see, I'm not that experienced with building like this. I actually just downloaded your repo, hardcoded the aarch64 in the variables and build the image. It actually runs, so that's why I thought that might be the issue.

```
[....] Restarting /usr/sbin/nordvpnd: nordvpnstart-stop-daemon: warning: failed 
to kill 421: No such process                                                    
. ok                                                                            
spawn nordvpn login                                                             
Please enter your login details.                                                
Email / Username: wicky@rampersad.me                                            
Password:                                                                       
You are logged in. Welcome to NordVPN! You can now connect via 'nordvpn connect'
.                                                                               
The command you entered is not valid. Enter 'nordvpn set protocol --help' to see
 the options.                                                                   
Kill Switch is successfully set to 'enabled'.                                   
CyberSec is already set to 'disabled'.                                          
Obfuscation is already set to 'disabled'.                                       
DNS is already set to 'disabled'.                                               
Connecting to Netherlands #116 (nl116.nordvpn.com)                              
We could not disable IPv6. Check logs for more information.                     
Great! You are now connected to Netherlands #116 (nl116.nordvpn.com)            
Full input access enabled                                                       
Added network route 192.168.1.0/24                                              
2019/02/25 21:39:17 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with
 256 bit key                                                                    
2019/02/25 21:39:17 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with
 256 bit key                                                                    
```

**Comment by bubuntux** [comment]
hmm interesting... 

i triggered a build just for you, you can check the tag aarch64-2019-02-25T21.38-openvpn 
that one should work with aarch64 just check the doc 
https://github.com/bubuntux/nordvpn/blob/openvpn/README.md

i noticed some big issue with the official binary implementation, so thinking on going back to openvpn implementation since is easier to customize, feel free to give it a try. i'm still exploring more alternatives, and more arch support, so sry for the mess and thanks for being patient

**Comment by w0ndersp00n** [comment]
Just downloaded this one, and this one indeed just works! I'm going to test it, but at first sight I noticed network speeds are higher now.

**Comment by bubuntux** [comment]
aarch64 should be working fine on the latest version now
