### ISSUE TITLE
unable to run focal tag image

### ISSUE THREAD

**Issue by ThangEthan** [bubuntux/nordvpn#170]
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
The container failed to connect to VPN server and exit

**To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            -e USER= -e PASS='' \
            -e CONNECT=nl -e TECHNOLOGY=NordLynx -d bubuntux/nordvpn:focal`

**Expected behavior**
Expected to successfully establish a connection

**Logs**
+ [[ -n '' ]]

++ ip -o addr show dev eth0

++ awk '$3 == "inet" {print $4}'

+ DOCKER_NET=172.17.0.3/16

+ trap cleanup SIGTERM SIGINT EXIT

+ kill_switch

+ iptables -F

+ iptables -X

+ iptables -P INPUT DROP

+ iptables -P FORWARD DROP

+ iptables -P OUTPUT DROP

+ iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A INPUT -i lo -j ACCEPT

+ iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A FORWARD -i lo -j ACCEPT

+ iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A OUTPUT -o lo -j ACCEPT

+ iptables -A OUTPUT -o tap+ -j ACCEPT

+ iptables -A OUTPUT -o tun+ -j ACCEPT

+ iptables -A OUTPUT -o nordlynx -j ACCEPT

+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE

+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE

+ iptables -t nat -A POSTROUTING -o nordlynx -j MASQUERADE

+ iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

+ iptables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

+ iptables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

+ iptables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

+ iptables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

+ [[ -n 172.17.0.3/16 ]]

+ iptables -A INPUT -s 172.17.0.3/16 -j ACCEPT

+ iptables -A FORWARD -d 172.17.0.3/16 -j ACCEPT

+ iptables -A FORWARD -s 172.17.0.3/16 -j ACCEPT

+ iptables -A OUTPUT -d 172.17.0.3/16 -j ACCEPT

+ [[ -n '' ]]

+ ip6tables -F

+ ip6tables -X

+ ip6tables -P INPUT DROP

+ ip6tables -P FORWARD DROP

+ ip6tables -P OUTPUT DROP

+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A INPUT -p icmp -j ACCEPT

+ ip6tables -A INPUT -i lo -j ACCEPT

+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A FORWARD -p icmp -j ACCEPT

+ ip6tables -A FORWARD -i lo -j ACCEPT

+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A OUTPUT -o lo -j ACCEPT

+ ip6tables -A OUTPUT -o tap+ -j ACCEPT

+ ip6tables -A OUTPUT -o tun+ -j ACCEPT

+ ip6tables -A OUTPUT -o nordlynx -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

+ ip6tables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

+ ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

++ ip -o addr show dev eth0

++ awk '$3 == "inet6" {print $4; exit}'

+ local docker6_network=

+ [[ -n '' ]]

+ [[ -n '' ]]

+ white_list api.nordvpn.com

++ echo api.nordvpn.com

++ sed 's/^.*:\/\///;s/\/.*$//'

+ local domain=api.nordvpn.com

+ iptables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT

+ ip6tables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT

+ [[ -n '' ]]

+ setup_nordvpn

+ pkill nordvpnd

+ rm -f /run/nordvpn/nordvpnd.sock

+ nordvpnd

+ '[' '!' -S /run/nordvpn/nordvpnd.sock ']'

+ sleep 0.25

2021/05/06 20:45:28 [Info] Daemon has started

2021/05/06 20:45:28 Kill Switch set to: disabled

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

2021/05/06 20:45:28 Technology set to: OpenVPN

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

2021/05/06 20:45:28 DNS set to: disabled

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

2021/05/06 20:45:28 Protocol set to: UDP

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

2021/05/06 20:45:28 Auto-connect set to: disabled

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

2021/05/06 20:45:28 CyberSec set to: disabled

NordVPN App Connection Settings:

Technology: OpenVPN

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

+ '[' '!' -S /run/nordvpn/nordvpnd.sock ']'

+ nordvpn login -u -p ''

Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

+ [[ -n NordLynx ]]

+ nordvpn set technology NordLynx

2021/05/06 20:45:30 Technology set to: NordLynx

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled

Technology is successfully set to 'NordLynx'.

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n 172.17.0.3/16 ]]

+ nordvpn whitelist add subnet 172.17.0.3/16

Subnet 172.17.0.0/16 is whitelisted successfully.

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n on ]]

+ nordvpn -version

NordVPN Version 3.9.2

+ nordvpn settings

Technology: NordLynx

Firewall: enabled

Kill Switch: disabled

CyberSec: disabled

Notify: disabled

Auto-connect: disabled

DNS: disabled

Whitelisted subnets:

172.17.0.0/16

+ mkdir -p /dev/net

+ [[ -c /dev/net/tun ]]

+ nordvpn connect nl

-2021/05/06 20:45:31 PRE_CONNECT system info:

App Version: 3.9.2

OS Info:

NAME="Ubuntu"

VERSION="20.04.2 LTS (Focal Fossa)"

ID=ubuntu

ID_LIKE=debian

PRETTY_NAME="Ubuntu 20.04.2 LTS"

VERSION_ID="20.04"

HOME_URL="https://www.ubuntu.com/"

SUPPORT_URL="https://help.ubuntu.com/"

BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"

PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

VERSION_CODENAME=focal

UBUNTU_CODENAME=focal

System Info:Linux 4bfe8970218c 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Routes of All Routing Tables:

default via 172.17.0.1 dev eth0

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.3

broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1

local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1

local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1

broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1

broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.3

local 172.17.0.3 dev eth0 table local proto kernel scope host src 172.17.0.3

broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.3

IP Rules:

0: from all lookup local

32766: from all lookup main

32767: from all lookup default

IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -o nordlynx -j ACCEPT

-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 104.17.50.74/32 -o eth0 -j ACCEPT

-A OUTPUT -d 104.17.49.74/32 -o eth0 -j ACCEPT

nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

-A POSTROUTING -o nordlynx -j MASQUERADE

mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT

security:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

/2021/05/06 20:45:41 [Debug] picking servers for NordLynx technology

|2021/05/06 20:45:46 [Error] disabling IPv6: seting net.ipv6.conf.all.disable_ipv6 to 1: exit status 255: sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system

/2021/05/06 20:45:48 POST_CONNECT system info:

Routes of All Routing Tables:

default via 172.17.0.1 dev eth0

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.3

broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1

local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1

local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1

broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1

broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.3

local 172.17.0.3 dev eth0 table local proto kernel scope host src 172.17.0.3

broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.3

IP Rules:

0: from all lookup local

32766: from all lookup main

32767: from all lookup default

IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -o nordlynx -j ACCEPT

-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 104.17.50.74/32 -o eth0 -j ACCEPT

-A OUTPUT -d 104.17.49.74/32 -o eth0 -j ACCEPT

nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

-A POSTROUTING -o nordlynx -j MASQUERADE

mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT

security:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

Whoops! We couldn't connect you to 'nl'. Please try again. If the problem persists, contact our customer support.

+ exit 1

+ cleanup

+ nordvpn disconnect

You are not connected to NordVPN.

+ pkill nordvpnd

2021/05/06 20:45:48 releasing /etc/resolv.conf

+ trap - SIGTERM SIGINT EXIT

+ exit 0

**Comment by bubuntux** [comment]
i'm aware of the issues with focal that is why i haven't merge into master and release it, not sure what is wrong i may just skip the upgrade.
