### ISSUE TITLE
WIndows ARM64

### ISSUE THREAD

**Issue by pb5050** [bubuntux/nordvpn#185]
Do you guys have any plans on adding this architecture?

**Comment by bubuntux** [comment]
no, this image is based on the debian package

**Comment by pb5050** [comment]
i will be ending my membership with nord.  I was unaware. That lazy devs were involved with this project. I'm sorry if I come off rude. But a simple no. Because it's based on a debain package.   thats why? you dont like a chalenge?  If you can't just plug and cross compile, it's a note. I mean there has to be a work around. I'm sure it would be. Quite a bit of work, but. Let me show you an example.

https://github.com/AdguardTeam/AdGuardHome/issues/3057#issuecomment-832044885
9 month eta im sure it wil be longer but atleast they are going for it. 

POwer toys has been working 0on it for a year and half. 


just no because its based on a debain package fml lol

**Comment by bubuntux** [comment]
I made this project for my personal use and made it available for anyone that is interested in,
I have no affiliation with nordvpn, no one is paying me to work on this project and i don't have the time to fix other ppls problem, if you are interested in adding support for windows feel free to fork the project and add support for it, i would be happy to accept a pull request.

**Comment by pb5050** [comment]
my apology 💀(￣┰￣*)       (+_+)                   ?(⊙o⊙)
