### ISSUE TITLE
Windows ARM64 - Emulation being blocked. 

### ISSUE THREAD

**Issue by pb5050** [bubuntux/nordvpn#186]
i replied to your simple "no" 
https://github.com/bubuntux/nordvpn/issues/185#issuecomment-848696306

Maybe this goes hand in hand with the effort thing i talked about, but you guys block the surface pro x from installing even when it supports x86 and x64 emulation but when installing the file it says nord does not support my OS.

I can emulate so i can run the file the blockj jkeeps people from emulatinf the OS for the app

**Comment by bubuntux** [comment]
no interested in adding support for windows, you are free to add support on your own or switch to linux.
