### ISSUE TITLE
Add timezone environment variable

### ISSUE THREAD

**Issue by gabrielwhite** [bubuntux/nordvpn#193]
**Is your feature request related to a problem? Please describe.**
I have trouble debugging the logs as time is recorded in UTC and my other system logs are in my local timezone.

**Describe the solution you'd like**
It would be great to add an environment variable to set the timezone, often available in other Docker images (e.g "- TZ=Europe/London")

**Comment by bubuntux** [comment]
i added the feature into the master branch, i'll release it along with the newest version that seems like maybe available soon.

**Comment by gabrielwhite** [comment]
Thanks!

**Comment by gabrielwhite** [comment]
Works thanks! And thanks for improving showing of time stamps in the log itself - very helpful.
