### ISSUE TITLE
Whoops, connection failed please try again

### ISSUE THREAD

**Issue by zyzzma** [bubuntux/nordvpn#197]
Synology DSM6.2 
Been running this container for many months. Cannot seem to get it to work now. I've tried CLI and regular synology GUI. neither seem to work and I get the following error on the title. Any help is appreciated

**Comment by bubuntux** [comment]
You need to provide more information, there is a reason why there is a template to create tickets. 
if you don't know what is wrong and don't post details and what thing u tried and so fort, no one will be able to help you.

**Comment by zyzzma** [comment]
You're right, I apologize. 
       
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -o nordlynx+ -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE
-A POSTROUTING -o nordlynx+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


2021/06/03 14:52:47 [Debug] picking servers for NordLynx technology
2021/06/03 14:52:47 [Warning] route(s) for whitelisted subnet(s) via non-default gateway already exist in the system
2021/06/03 14:52:47 [Error] turning on nordlynx: Creating tun device: no such device
2021/06/03 14:52:47 POST_CONNECT system info:
Routes of All Routing Tables:
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.7 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.7 
local 172.17.0.7 dev eth0 table local proto kernel scope host src 172.17.0.7 
broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.7 
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium

IP Rules:
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -o nordlynx+ -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE
-A POSTROUTING -o nordlynx+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


[2021-06-03T14:52:47+00:00] Unable to connect.


Done on synology DSM 6.2 using the CLI instructions. putting my NordVPN username and password (not the openvpn ones). I had this working lovely for a long time. I don't know what happened....

**Comment by bubuntux** [comment]
please follow the template instructions, enable DEBUG=trace, the logs provided are not enough, 
have u tried updating to the latest version ? have u tried older versions ? try to narrow down the problem.

**Comment by zyzzma** [comment]
I have only tried latest version, not older ones. I added trace like you said. Here is the results:



[2021-06-03T15:19:08+00:00] Firewall is up, everything has to go through the vpn
[2021-06-03T15:19:08+00:00] Enabling connection to secure interfaces
[2021-06-03T15:19:08+00:00] Enabling connection to nordvpn group
iptables: No chain/target/match by that name.
[2021-06-03T15:19:08+00:00] group match failed, fallback to open necessary ports
[2021-06-03T15:19:08+00:00] ip6 group match failed, fallback to open necessary ports
[2021-06-03T15:19:08+00:00] Enabling connection to docker network
[2021-06-03T15:19:09+00:00] Restarting the service
[2021-06-03T15:19:09+00:00] Waiting for the service to start
[2021-06-03T15:19:10+00:00] Logging in

-
  

-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
[2021-06-03T15:19:16+00:00] Setting up NordVPN Version 3.9.5
Technology is successfully set to 'NordLynx'.
Subnet 172.17.0.0/16 is whitelisted successfully.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Technology: NordLynx
Firewall: enabled
Kill Switch: disabled
CyberSec: disabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
	172.17.0.0/16
[2021-06-03T15:19:16+00:00] Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
/
-
\
|
/
-
\
  
Connecting to Portugal #71 (pt71.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
/
-
\
|
/
  
Connecting to Portugal #50 (pt50.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
  
Connecting to Portugal #54 (pt54.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
\
  
Connecting to Portugal #40 (pt40.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #46 (pt46.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #46 (pt46.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
/
  
Connecting to Portugal #54 (pt54.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #40 (pt40.nordvpn.com)

-
\
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #40 (pt40.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #46 (pt46.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #38 (pt38.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #46 (pt46.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
/
  
Connecting to Portugal #66 (pt66.nordvpn.com)

-
\
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #67 (pt67.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #70 (pt70.nordvpn.com)

-
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.

-
  
A new version of NordVPN is available! Please update the application.

-
  
Connecting to Portugal #46 (pt46.nordvpn.com)

-
\
  

-
  
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.
Routes of All Routing Tables:
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.7 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.7 
local 172.17.0.7 dev eth0 table local proto kernel scope host src 172.17.0.7 
broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.7 
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium

IP Rules:
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -o nordlynx+ -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE
-A POSTROUTING -o nordlynx+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


2021/06/03 15:20:40 PRE_CONNECT system info:
App Version: 3.9.5
OS Info:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

System Info:Linux 95d60d27217f 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux


Routes of All Routing Tables:
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.7 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.7 
local 172.17.0.7 dev eth0 table local proto kernel scope host src 172.17.0.7 
broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.7 
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium

IP Rules:
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -o nordlynx+ -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE
-A POSTROUTING -o nordlynx+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


2021/06/03 15:20:40 [Debug] picking servers for NordLynx technology
2021/06/03 15:20:40 [Warning] route(s) for whitelisted subnet(s) via non-default gateway already exist in the system
2021/06/03 15:20:40 [Error] turning on nordlynx: Creating tun device: no such device
2021/06/03 15:20:40 POST_CONNECT system info:
Routes of All Routing Tables:
default via 172.17.0.1 dev eth0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.7 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.7 
local 172.17.0.7 dev eth0 table local proto kernel scope host src 172.17.0.7 
broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.7 
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium
unreachable default dev lo proto kernel metric 4294967295 error -101 pref medium

IP Rules:
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -o nordlynx+ -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE
-A POSTROUTING -o nordlynx+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


[2021-06-03T15:20:40+00:00] Unable to connect.

**Comment by bubuntux** [comment]
doesn't look like trace is enable, also please follow the template!!! 
provide docker cli command/compose file

**Comment by zyzzma** [comment]
I'm still a relatively noob at this, I tried the trace and it isn't working for some reason... 
I've come further along now, I've been working at this for the past 4h nonstop. I just have a few questions

Should I leave the network at "bridge" or "nordvpn_default"? 
Do I need to have any ports? I don't mean to route containers, I mean just so I can do a curl ipconfig.io to check I'm getting a successful route and if so - udp or tcp?


I'm using portainer to manage all of this. If you answered these questions I might be able to set this up. As of now the logs say I'm connected to Portugal which is definitely not what I want.
