### ISSUE TITLE
auth. failures

### ISSUE THREAD

**Issue by lavaguy1** [bubuntux/nordvpn#20]
hi, i've been getting authentication failures when connecting to a selected nordvpn gateway since yesterday. uid/pw work fine to login to nordvpn website (account management). error has been there since yesterday, 27.Feb.2019. Log is below:

```
Selecting the best server...


White listing api.nordvpn.com...


Searching for country : CH (209)


Searching for group: legacy_p2p


Searching for technology: openvpn_udp


Best server : ch76.nordvpn.com


Using config file /vpn/ovpn/ch76.nordvpn.com.udp.ovpn...


Connecting...


Thu Feb 28 12:59:58 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 26 2018


Thu Feb 28 12:59:58 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10


Thu Feb 28 12:59:58 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit


Thu Feb 28 12:59:58 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Thu Feb 28 12:59:58 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication


Thu Feb 28 12:59:58 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication


Thu Feb 28 12:59:58 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.236.201.131:1194


Thu Feb 28 12:59:58 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]


Thu Feb 28 12:59:58 2019 UDP link local: (not bound)


Thu Feb 28 12:59:58 2019 UDP link remote: [AF_INET]185.236.201.131:1194


Thu Feb 28 12:59:58 2019 TLS: Initial packet from [AF_INET]185.236.201.131:1194, sid=e1d9facc ca00f9dd


Thu Feb 28 12:59:59 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA


Thu Feb 28 12:59:59 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA3


Thu Feb 28 12:59:59 2019 VERIFY KU OK


Thu Feb 28 12:59:59 2019 Validating certificate extended key usage


Thu Feb 28 12:59:59 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication


Thu Feb 28 12:59:59 2019 VERIFY EKU OK


Thu Feb 28 12:59:59 2019 VERIFY OK: depth=0, CN=ch76.nordvpn.com


Thu Feb 28 13:00:01 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA


Thu Feb 28 13:00:01 2019 [ch76.nordvpn.com] Peer Connection Initiated with [AF_INET]185.236.201.131:1194


Thu Feb 28 13:00:02 2019 SENT CONTROL [ch76.nordvpn.com]: 'PUSH_REQUEST' (status=1)


Thu Feb 28 13:00:02 2019 AUTH: Received control message: AUTH_FAILED


Thu Feb 28 13:00:02 2019 SIGTERM[soft,auth-failure] received, process exiting
```

**Comment by bubuntux** [comment]
Does your password contain the $ character by any chance? 
if so you can you try to replace it with \$, so for example if the password is `pa$word ` try adding the env variable as `pa\$word` 
if not, does it contains another special character? i imagine one of them may cause the issue

**Comment by bubuntux** [comment]
or just define your password sounder by single quotes 
-e PASS='yourPa$$word' that may also work

**Comment by lavaguy1** [comment]
Thanks for the quick response. I'll give it a try, but it's odd that it worked until yesterday...

**Comment by lavaguy1** [comment]
No, neither of those worked. Even tried changing my password. Still getting auth failure... could it be choking on the user Id? It's an email address...
Also, I'm setting everything up using docker-compose and a yml file that also worked fine until 27.2.

**Comment by bubuntux** [comment]
hmm.. the email shouldn't be a problem.. are you mounting the volume /vpn by any chance? 
i tried multiple password configurations using diff characters and adding the single quotes fixed it, 
do you mind sharing with me more details of the command/docker-compose (leaving out the pass/user)

**Comment by lavaguy1** [comment]
Here is the relevant section of my yml file for compose:

version: "3.6"

services:
  vpn:
    container_name: vpn
    restart: unless-stopped
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    volumes:
      - ${USERDIR}/docker/vpn:/vpn
      - /dev/net:/dev/net:z
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8999:8999"
      - "3128:3128"
      - "1080:1080"
      - "8080:8080"
    stdin_open: true
    environment:
      - TZ=${TZ}
      - NETWORK=192.168.178.0/24
      - USER=Email
      - PASS=Password
      - COUNTRY=US
# Switzerland;Germany
      - CATEGORY=P2P
# ;Obfuscated Servers
      - PROTOCOL=UDP
# openvpn_udp
      - PUID=${PUID}
      - PGID=${PGID}

**Comment by bubuntux** [comment]
can you make sure to remove the auth file inside of 
${USERDIR}/docker/vpn
it will write the file only if it doesn't exist already
since it probably does (and have the wrong password) you keep getting the issue

**Comment by lavaguy1** [comment]
One more try... here is the relevant part of my compose yml-file:
version: "3.6"

services:
  vpn:
    container_name: vpn
    restart: unless-stopped
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    volumes:
      - ${USERDIR}/docker/vpn:/vpn
      - /dev/net:/dev/net:z
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8999:8999"
      - "3128:3128"
      - "1080:1080"
      - "8080:8080"
    stdin_open: true
    environment:
      - TZ=${TZ}
      - NETWORK=192.168.178.0/24
      - USER=s.davis1@gmail.com
      - PASS='4Lm7MUXYb'
      - COUNTRY=US
      - CATEGORY=P2P
      - PROTOCOL=UDP
      - PUID=${PUID}
      - PGID=${PGID}

**Comment by lavaguy1** [comment]
Relevant part of yml file:
version: "3.6"

services:
  vpn:
    container_name: vpn
    restart: unless-stopped
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    volumes:
      - ${USERDIR}/docker/vpn:/vpn
      - /dev/net:/dev/net:z
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8999:8999"
      - "3128:3128"
      - "1080:1080"
      - "8080:8080"
    stdin_open: true
    environment:
      - TZ=${TZ}
      - NETWORK=192.168.178.0/24
      - USER=Userid
      - PASS=Password
      - COUNTRY=US
      - CATEGORY=P2P
      - PROTOCOL=UDP
      - PUID=${PUID}
      - PGID=${PGID}

**Comment by lavaguy1** [comment]
Thanks - deleting the auth file fixed it...
