### ISSUE TITLE
Cycle through servers?

### ISSUE THREAD

**Issue by NoLooseEnds** [bubuntux/nordvpn#203]
Is it possible to add a list of specific servers and cycle through them in case the first is down.

ie. 
```
CONNECT: de102, dk20, de200, sv192
```

You can do this in a standard openvpn config, and it's just cycling through the list until one of them connects.

**Comment by bubuntux** [comment]
this could be a feature, but what about not setting the CONNECT variable and let nordvpn connects you to the best server ?

**Comment by NoLooseEnds** [comment]
My main motivation is to have better control over the IP of the VPN-server, since my guess is that the individual server ip's don't change that often.
