### ISSUE TITLE
Using OPENVPN_OPTS breaks container

### ISSUE THREAD

**Issue by Groofster** [bubuntux/nordvpn#21]
The OPENVPN_OPTS option is broken because of the location of the variable at startup:

The startup script thinks the OPENVPN_OPTS variable contains parameters to the --down script instead of extra options for openvpn. I think moving the variable to before the --up statement will make it work again

exec sg vpn -c "openvpn --config ${config_file} --auth-user-pass ${auth_file} --auth-nocache \
                            --script-security 2 ${OPENVPN_OPTS} --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh"

**Comment by bubuntux** [comment]
the order of the parameters shouldn't matter, can you provide logs and command line used?

**Comment by Groofster** [comment]
docker-compose.yaml

version: '3.5'

services:
  nordvpn:
    image: "bubuntux/nordvpn"
    container_name: nordvpn
    restart: unless-stopped
    stdin_open: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Amsterdam
      - USER=
      - PASS=
      - COUNTRY=Netherlands;
      - NETWORK=10.10.1.0/24
      - CATEGORY=P2P
      - OPENVPN_OPTS='--mute-replay-warnings --mssfix 1432'

Gives me the following error and a restarting container:

Connecting ( '--mute-replay-warnings --mssfix 1432' )... 
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: mute-replay-warnings --mssfix 1432 (2.4.6)

Swithing the OPENVPN_OPTS gives the following error:

Connecting ( ' --mssfix 1432 --mute-replay-warnings' )... 
Options error: the --down directive should have at most 1 parameter.  To pass a list of arguments as one of the parameters, try enclosing them in double quotes ("").

**Comment by Groofster** [comment]
I found out this is more a 'pebkac' kind of error. The syntax in docker-compose is slightly different from a normal docker run -e PARAMETER. Changing the OPENVPN_OPTS line to following made it happily accept it (it's all in the quotes):

 environment:
- TZ=Europe/Amsterdam
- USER=
- PASS=
- COUNTRY=Netherlands;
- NETWORK=10.10.1.0/24
- CATEGORY=P2P
- 'OPENVPN_OPTS=--mute-replay-warnings --mssfix 1432'

This (non) issue can be closed. Thanx for your time, sorry to have bothered you with my personal f-up.

**Comment by bubuntux** [comment]
Thanks for reporting the issue, i'll fix the documentation to make it more clear
