### ISSUE TITLE
CATEGORY won't work

### ISSUE THREAD

**Issue by xXTim97Xx** [bubuntux/nordvpn#22]
I'm using the Country Flag CH and specified the CATEGORY with 'Standard VPN servers'.
But the client keeps connecting me to the 'ch-onion1.nordvpn.com' server, even if I enter another CATEGORY like P2P.

Any ideas?

**Comment by bubuntux** [comment]
seems to be working fine for me 
```
$ docker run --rm -ti --cap-add=NET_ADMIN --device /dev/net/tun -e USER=<secret> -e PASS=<secret>  -e CATEGORY='Standard VPN servers' -e COUNTRY=CH bubuntux/nordvpn 
Staring firewall...
White listing downloads.nordcdn.com...
Downloading config files...
White listing api.nordvpn.com...
Selecting the best server...
Searching for country : CH (209)
Searching for group: legacy_standard
Best server : ch63.nordvpn.com
Using config file /vpn/ovpn/ch63.nordvpn.com.tcp.ovpn...
Connecting ... 
Fri Mar  8 15:44:33 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 26 2018
Fri Mar  8 15:44:33 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2
```

can you provide the command line and logs?

**Comment by bubuntux** [comment]
btw, when using docker-compose you don't need the single quotes

**Comment by xXTim97Xx** [comment]
Here is my Docker Compose File

version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=
      - PASS=
      - COUNTRY=CH
      - CATEGORY='Standard VPN servers'
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - PROTOCOL=UDP
      - NETWORK=192.168.178.0/24
      - TZ=Germany/Berlin
    ports:
      - 9999:8000
    stdin_open: true
    restart: unless-stopped
  app:
    image: writl/pyload:latest
    container_name: pyload
    network_mode: service:vpn
    depends_on:
      - vpn

**Comment by bubuntux** [comment]
remove the single quotes 
try 
- CATEGORY=Standard VPN servers
instead of 
- CATEGORY='Standard VPN servers'

**Comment by xXTim97Xx** [comment]
Thank you very much. This solved my problem
