### ISSUE TITLE
Can there be support for "teams" edition?

### ISSUE THREAD

**Issue by huanga** [bubuntux/nordvpn#223]
This container image works great for regular account, but we've recently migrated to [NordVPN Teams](https://nordvpnteams.com/), which they also offer applicable [linux download](https://nordvpnteams.com/download/linux/) in `.deb` format that is used in the current container. I haven't really poked much at it to know if the two debs could co-exist, but if there's no major technical limitation, would it be possible to make this image also support Teams edition?

**Comment by bubuntux** [comment]
It seems possible, i don't want to sound like a jerk, but i don't have the incentive to work on this, i just don't use teams client and have no need for it.
i would be more than happy to accept a pull request with the changes need it for teams support. 

OPTIONALLY i can take a stab at it in exchange for a $50 one-time donation in [guthub sponsor](https://github.com/sponsors/bubuntux?frequency=one-time)
