### ISSUE TITLE
Configuration file/Modify whitelist on the fly

### ISSUE THREAD

**Issue by 5t4cktr4c3** [bubuntux/nordvpn#229]
**Is your feature request related to a problem? Please describe.**
A few months ago I started programming a Python-based managing script to change the whitelist configuration easily from the command line while the container was running. This would enable more flexibility for dynamic network environments.

**Describe the solution you'd like**
I can provide the basic code snippets that I programmed (however, they're incomplete, but I'm motivated to get back to it with some help).
This script or better said the scripts would replace the environment variables as the configuration would be possible with the script.

**Describe alternatives you've considered**
I just had the idea that we can provide a configuration file that's mounted to the container(s). As soon as the configuration file changes the script inside the container is triggered and modifies the whitelist based on the changes in the configuration file.

**Additional context**
#

**Comment by bubuntux** [comment]
As a work around you can try to use the 
recently added POST_CONNECT variable, you can create a script to be executed after connection is establish, there you can do whatever you want, including updating the whitelist
