### ISSUE TITLE
User-defined docker network prevents NordVPN to login

### ISSUE THREAD

**Issue by mazzy89** [bubuntux/nordvpn#238]
**Describe the bug**

Launching the following container with an user-defined network, it does not provide connectivity to the container making the login failing.

**To Reproduce using docker CLI**

Create a custom network:

```
docker network create -d bridge --subnet=172.20.0.0/16 --gateway=172.20.0.1 -o "com.docker.network.bridge.name=br-nordvpn" -o "com.docker.network.bridge.enable_ip_masquerade=true" -o "com.docker.network.bridge.enable_icc=true" -o "com.docker.network.bridge.host_binding_ipv4=0.0.0.0" -o "com.docker.network.driver.mtu=1500" nordvpn
```

Create NordVPN container defining as network `--net=nordvpn`

**Expected behavior**
I would expect that the container would work and login returns successfully.

**Logs**
Add DEBUG=trace and copy the logs here (make sure to remove you user and password from the logs as well).

**Additional context**

I have tried to update the Ubuntu version of the container maybe thinking that `iptables` old version could be buggy but it did not help.

**Comment by mazzy89** [comment]
My gut feeling was right. Removing the `DROP` statements at the beginning of the `start_vpn.sh` script made it working. Those statements in fact drop rules that are important for containers running with user-defined network.

@bubuntux Do you think you can wire some adjustments? Do you want to keep those `DROP` statements? WHat do you think?

**Comment by bubuntux** [comment]
i honestly just leave them there for legacy reasons, but also didn't think they were necessary or were causing any issues so.. yeah i think we can remove them.

**Comment by mazzy89** [comment]
do you want me to wire a PR to drop those rules?

**Comment by bubuntux** [comment]
i think for this one i want to create a separate branch just to be extra cautious, just so i can run some tests, so it may take me some time to get to it.

**Comment by mazzy89** [comment]
sure. you might know better the different test suites. I'm already running w/o those statements for like one hour and it looks ok. let me know then.

**Comment by bubuntux** [comment]
well.. actually.. those drops guarantee the kill switch now that i think about it..

**Comment by bubuntux** [comment]
i'm thinking maybe store those rules, drop everything and re add them after, not sure how tbh, will need to dig in more, if you find a solution without compromising the kill switch do not hesitate to create a PR

**Comment by mazzy89** [comment]
I need to test then to close the VPN connection and see if the kill switch works.

**Comment by mazzy89** [comment]
Yeah I confirm. removing those rules affecet the kill switch functionality. In fact disconnected i have still connectivity in the container but with my local IP.

**Comment by mazzy89** [comment]
so the game here would be to start the container, save those special rules defined for user-defined network, run those DROP statements and then apply again.

We should run an `iptables-save`, pull those rules needed, store temporary, run the `DROP` statements and apply the saved ones.

**Comment by bubuntux** [comment]
yup, something like it, but things get a little extra tricky, since this container can start along with others, the longer you wait to execute those drops, the higher the chances to leak the real ip, we had an issue with that in the past that is why i moved them at the very top now everything is coming back, we def need those drops.

**Comment by likwid101** [comment]
I was wondering if there was any movement on this? AKA, is this an issue that has potential of being resolved or is it kind of stuck where it is? I recently found that using the image on dockerhub in my unRaid setup that the bridge network type works but as soon as I change it to custom br0 it will not connect.
![image](https://user-images.githubusercontent.com/25729062/131617482-d724b8ff-0163-4603-8133-41918d3b1fa8.png)

**Comment by hemna** [comment]
I am running into this as well.  can't login 

```
vpn_1      | [2021-09-28T17:14:49+00:00] Invalid Username or password.
vpn_1      | [2021-09-28T17:14:50+00:00] Firewall is up, everything has to go through the vpn
vpn_1      | [2021-09-28T17:14:50+00:00] Enabling connection to secure interfaces
vpn_1      | [2021-09-28T17:14:50+00:00] Enabling connection to nordvpn group
vpn_1      | [2021-09-28T17:14:50+00:00] Enabling connection to docker network
```

**Comment by bubuntux** [comment]
does the solution for #267 solves this issue ?

**Comment by igor-pavlichenko** [comment]
#267 did it for me 👌
