### ISSUE TITLE
Add scheduled build jobs

### ISSUE THREAD

**Issue by brainkiller** [bubuntux/nordvpn#242]
I noticed that the image is not regularly rebuild (for example weekly or monthly).
It's only build when a change is commited to the GIT repository. Could you please make a scheduled build job for this image ?

If you want I can call a webhook on a regular basis to trigger a build. It depends on how you build and push the image

**Comment by bubuntux** [comment]
ill add this feature soon

**Comment by bubuntux** [comment]
i changed my mind about this issue, with the new login --nordaccount this container may no longer work in future versions, so the usage of [nordlynx](https://github.com/bubuntux/nordlynx) container may be the only option, i'll add an scheduled job there
