### ISSUE TITLE
Cannot establish connection 

### ISSUE THREAD

**Issue by lizardkingDOTca** [bubuntux/nordvpn#25]
Not sure what i am doing wrong, but i keep getting

Attempting to establish TCP connection with [AF_INET]184.75.212.59:443 [nonblock] | stdout
-- | --
then
SIGUSR1[connection failed(soft),init_instance] received, process restarting

**Comment by lizardkingDOTca** [comment]
my password start with an equal sign [=], and contains a plug sign [+] and a double quote ["]
so not sure if that is the problem

**Comment by bubuntux** [comment]
can you provide more information, command used and full logs ? (leave out user/pass)
the password should not be an issue, you could double check it's properly set by 
` docker exec "container_name" cat /vpn/auth `

**Comment by lizardkingDOTca** [comment]
i use docker compose
`version: "3"

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: vpn-nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=[email address]
      - PASS='[password]'
      #- PASS='m6ebRc3LHasnhV7'
      - COUNTRY=Canada
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - NETWORK=10.10.1.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=America/Toronto
    ports:
      - 8080:80
      - 8113:8112 #port for deluge
    restart: unless-stopped`

**Comment by bubuntux** [comment]
The issues is def the password then
Can you remove the single quotes for the password? 

from
- PASS='[password]'
to
- PASS=[password]

**Comment by lizardkingDOTca** [comment]
So that did work for UDP (which I had not try yesterday without the quote, my bad)
But still not working for TCP 
[vpn-nordvpn.csv.log](https://github.com/bubuntux/nordvpn/files/2972436/vpn-nordvpn.csv.log)

**Comment by bubuntux** [comment]
are u on the latest version? i believe that issues was fixes already

**Comment by lizardkingDOTca** [comment]
the image is tag as "bubuntux/nordvpn:latest", so should I put another tag.
My docker-compose it set to pull "image: bubuntux/nordvpn" which should be the latest I would think

**Comment by bubuntux** [comment]
i'm not able to reproduce the issue, are you able to connect if you only add the parameter PROTOCOL TCP (so remove COUNTRY, CATEGORY and OPENVPN_OPTS) ?

**Comment by lizardkingDOTca** [comment]
I try removing country, category and openvps_opts, same results.

**Comment by bubuntux** [comment]
i'm not sure what it could be
can you try
`docker pull bubuntux/nordvpn`
and make sure your container is a fresh one using the latest version, that should fix the issue, since version [2019.03.01](https://github.com/bubuntux/nordvpn/commit/0a2f677c4ff4672da4403d26a07cb79b5d8f0c5e#diff-c58c12b84ee9c06749a2b6145889ab89) include that fix

**Comment by kisonay** [comment]
Hate to bring up a closed issue but I am having this exact issue. I can connect via UDP protocol without issue but I get gateway timeouts and the above errors when trying to connect via TCP using the latest release.

```
Mon Jun 10 08:37:23 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 26 2018
Mon Jun 10 08:37:23 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Mon Jun 10 08:37:23 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Mon Jun 10 08:37:23 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun 10 08:37:23 2019 NOTE: --fast-io is disabled since we are not using UDPMon Jun 10 08:37:23 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Jun 10 08:37:23 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Jun 10 08:37:23 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]89.187.xxx.xx:443
Mon Jun 10 08:37:23 2019 Socket Buffers: R=[87380->87380] S=[16384->16384]Mon Jun 10 08:37:23 2019 Attempting to establish TCP connection with [AF_INET]89.187.xxx.xx:443 [nonblock]
Mon Jun 10 08:39:23 2019 TCP: connect to [AF_INET]89.187.xxx.xx:443 failed: Operation timed out
Mon Jun 10 08:39:23 2019 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Mon Jun 10 08:39:23 2019 Restart pause, 5 second(s)
```

**Comment by bubuntux** [comment]
@kisonay is there a .tcp file available for the server you are trying to connect ?
