### ISSUE TITLE
DNS-based service discovery is broken in user-defined networks

### ISSUE THREAD

**Issue by hexfaker** [bubuntux/nordvpn#267]
**Describe the bug**
Services connected to the same user-defined network should be able to discover their peers using DNS-based discovery mechanism. But it's not working because NordVPN overwrites `/etc/resolv.conf`. 

**To Reproduce without docker CLI**
I used modified `start-vpn.sh` to work-around #238. My version and corresponding compose are in this [gist](https://gist.github.com/hexfaker/cfff1970a6096307c9072e825abe9e69).

**Expected behavior**
Service `bar` should successfully ping `foo`.

**Additional context**
I was able to work around this issue by saving the original `resolve.conf` at the beginning of `start-vpn.sh` and restoring it after this [line](https://github.com/bubuntux/nordvpn/blob/master/start_vpn.sh#L206). These lines are present in my gist, but I commented them out.

**Comment by bubuntux** [comment]
using the env DNS doesn't help?

**Comment by bubuntux** [comment]
that can be achieved with the new env variables PRE/POST_CONNECT

**Comment by bubuntux** [comment]
PRE_CONNECT=cp /etc/resolv.conf /etc/resolv1.conf
POST_CONNECT=cp /etc/resolv1.conf /etc/resolv.conf
