### ISSUE TITLE
new version of NordVPN 3.12.0

### ISSUE THREAD

**Issue by HansVanderGucht** [bubuntux/nordvpn#270]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**

**To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run ... bubuntux/nordvpn `

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: '3'
services:
  vpn:
    image: bubuntux/nordvpn
  ...
```

**Expected behavior**
A clear and concise description of what you expected to happen and a simple way for someone else to test it.

**Logs**
Add DEBUG=trace and copy the logs here (make sure to remove you user and password from the logs as well).

**Additional context**
Distribution used, versions, architecture and any other context about the problem here.

**Comment by bubuntux** [comment]
i did a big refactor to use s6 init framework and prepare to use wireguard without nord binary, those efforts can be found https://github.com/nrdvpn/client 
this include latest version and a few variables were renamed so review those if you want to give it a try
