### ISSUE TITLE
--ping-exit crashes whole vpn setup in docker compose

### ISSUE THREAD

**Issue by DavHau** [bubuntux/nordvpn#28]
First, thanks for the great image. I'm using it since a few weeks and I'm quite happy with it.
But there is one problem i encountered with the latest version.

The --ping-exit 180 which has recently been added as a recommendation doesn't seem like a good idea
Whenever the vpn container loses its connection for more than 180 sec, all containers which connect through the vpn will lose their internet connection forever. (Until they are restarted manually)
They will not reconnect through the vpn even if the vpn restarts and reconnects successfully.
The problem is whenever multiple child container share the network of a mother container via 'network_mode:service', they will lose their network adapter indefinitely when the mother container restarts.
I opened an [issue](https://github.com/docker/compose/issues/6626) for docker compose. but i don't know if they will improve this behavior.

replacing --ping-exit with --ping-restart seems to fix the issue, since this doesn't exit the whole container and keeps the network interface intact.

**Comment by bubuntux** [comment]
in that case --ping-restart is actually not need it, since the server usually push those into the client.
this will keep the interface intact as you point out, but keep trying to reconnect to the same server.

The reason why i was using the --ping-exit is to select a new server instead, seems like a need a better strategy.

**Comment by DavHau** [comment]
Maybe starting the vpn process in a loop inside the container is the solution. Then the whole openvpn process will actually restart without the container being restarted.

**Comment by bubuntux** [comment]
yup i have created a temporal tag named 'dev' that contains a possible fix, i did a few tests and seems to be working do you mind give it a shot?

**Comment by bubuntux** [comment]
actually never mind, it doesn't work the way i was expecting =/

**Comment by bubuntux** [comment]
latest dev tag should try to reconnect selecting new servers every time it get disconnected due --ping-exit, can you give it a shoot now?

**Comment by DavHau** [comment]
I just tried. Works like a charm... exactly how you described. New server got selected after disconnect. Thanks for the fix

**Comment by bubuntux** [comment]
i just merged the fix into `latest`, thanks for reporting the issue
