### ISSUE TITLE
/bin/sh: 1: /usr/bin/start_vpn.sh: not found

### ISSUE THREAD

**Issue by MRobi1** [bubuntux/nordvpn#284]
Just updated to :latest and on running the container the logs show:
/bin/sh: 1: /usr/bin/start_vpn.sh: not found

Going back to v3.12.0-1-2 and v3.12.0-1-2 gives the same error.

Going back to v3.10.0-1-1 solves the issue and connects fine.
No config changes between versions.

Were there any breaking config changes in the latest release?

**Comment by bubuntux** [comment]
i think this is a dup of #282
