### ISSUE TITLE
Environment variable addition: KILLSWITCH

### ISSUE THREAD

**Issue by JFirmware** [bubuntux/nordvpn#287]
**Is your feature request related to a problem? Please describe.**
Container starts without the killswitch enabled. 

**Describe the solution you'd like**
Addition to the Environment variables: KILLSWITCH = enable would be very useful. 

**Describe alternatives you've considered**
PRE_CONNECT=nordvpn settings killswitch enable 
I may be using this variable incorrectly

**Comment by bubuntux** [comment]
nordvpn killswitch is not need it due to the iptables commands executed

**Comment by JFirmware** [comment]
Can you explain? For my own education

**Comment by bubuntux** [comment]
this https://github.com/bubuntux/nordvpn/blob/master/rootfs/etc/cont-init.d/00-firewall blocks all the traffic

and then https://github.com/bubuntux/nordvpn/blob/master/rootfs/etc/cont-init.d/20-inet  allow the traffic on the vpn interface, if that interface drops there would be no traffic, with the exception of a few necessary ports to allow the initial connection
