### ISSUE TITLE
Can't connect anymore after an unstable connection is detected

### ISSUE THREAD

**Issue by mazzy89** [bubuntux/nordvpn#293]
**Describe the bug**

The container stay up for like an hour or two. After it detects un unstable connections, it dies. The routes are deleted and it cannot reach anymore the internet.

**To Reproduce using docker CLI**

**To Reproduce using docker-compose**

**Expected behavior**
When the container detects an unstable connection, it should simply restart nordlynx and avoid to delete those routes.

**Logs**

Logs have been posted as a screenshots

**Additional context**

What I do not get is because the route are deleted and never added anymore

![Screenshot 2021-12-02 at 12 00 48](https://user-images.githubusercontent.com/5463218/144410101-93258b4f-b187-47aa-a7b7-87224e72d8dc.png)

```env
CHECK_CONNECTION_URL=www.google.it
CONNECT=Italy
CYBER_SEC=true
NET_LOCAL=192.168.10.0/24
PASS=pwd
TECHNOLOGY=NordLynx
TZ=Europe/Rome
USER=user
```

**Comment by mazzy89** [comment]
FYI at the moment under your recommendation I've migrated to nordlynx container. for the moment seems way more stable.

**Comment by mazzy89** [comment]
Can say that the container nordlynx is much better and much stable. we can close this or leave it around in case anyone stumbled upon the same issue. what I can say is to migrate to nordlynx.

**Comment by bubuntux** [comment]
yup, this container will eventually be used to get the private key need it for nordlynx and nothing more, so yeah just use the new container
