### ISSUE TITLE
Access WebGUI of the container

### ISSUE THREAD

**Issue by babaz8** [bubuntux/nordvpn#294]
I need to access locally the webgui of the container using the VPN container is there a way to do it ?
Container A -> nordvpn
Container B -> web application with webgui

I need to access the webgui of container B .
Thanks

**Comment by rivera2387** [comment]
You should expose the port container B on container A. Container B should not have any exposed ports that container A is using.

It's in the docker-compose example https://github.com/bubuntux/nordvpn#docker-compose-example
