### ISSUE TITLE
VPN container keeps losing network access

### ISSUE THREAD

**Issue by pmarcantuono** [bubuntux/nordvpn#299]
Roughly 4 times today the VPN container has lost network access and didn't resolve itself.  This obviously effects the dependent containers as well.  

I get the following when I run "curl ifconfig.io" on any of the containers when this happens:

--------------
root@31553ebd0ac0:/# curl ifconfig.io
curl: (6) Could not resolve host: ifconfig.io
--------------

At this point I need to first restart the VPN container, then restart the dependents.  Otherwise, if you do them all together you get errors since the VPN container may not be online when the others come up.

Should I include add the "CHECK_CONNECTION_INTERVAL=300" environment variable even though it should be set by default?

Any help that can be provided would be greatly appreciated.   Thanks in advance!

Below is the Compose file I'm using:

version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn:latest
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=******         # Required
      - PASS=******         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080			#qbittorrent Web UI
      - 6881:6881			#qbittorrent data
      - 6881:6881/udp		#qbittorrent data
      - 8787:8787			#readarr
      - 8989:8989			#sonarr
      - 7878:7878			#radarr
      - 8686:8686			#lidarr
      - 9117:9117			#jackett
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    restart: unless-stopped

**Comment by bubuntux** [comment]
try latest version or migrate to https://github.com/bubuntux/nordlynx
