### ISSUE TITLE
Username with + cannot authenticate

### ISSUE THREAD

**Issue by philhawthorne** [bubuntux/nordvpn#30]
**Describe the bug**
I have just opened a new NordVPN account, using an aliased email address (for example phil+nordvpn@gmail.com).

However I am now receiving authentication issues when trying to start the container.

**To Reproduce**
```bash
docker run -tid --cap-add=NET_ADMIN --device /dev/net/tun --privileged  --name vpn -e USER=phil+example@example.com -e PASS='P4ssw0rd' -e NETWORK=192.168.1.1/24 -e TZ='Australia/Melbourne' -e PROTOCOL=UDP bubuntux/nordvpn
```

**Logs**
```
Connecting ...
Mon Apr  8 10:21:10 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 26 2018
Mon Apr  8 10:21:10 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Mon Apr  8 10:21:10 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Mon Apr  8 10:21:10 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Apr  8 10:21:10 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Apr  8 10:21:10 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Apr  8 10:21:10 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]144.48.37.133:1194
Mon Apr  8 10:21:10 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Apr  8 10:21:10 2019 UDP link local: (not bound)
Mon Apr  8 10:21:10 2019 UDP link remote: [AF_INET]144.48.37.133:1194
Mon Apr  8 10:21:11 2019 TLS: Initial packet from [AF_INET]144.48.37.133:1194, sid=357d3f69 6dced0fa
Mon Apr  8 10:21:11 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Mon Apr  8 10:21:11 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA3
Mon Apr  8 10:21:11 2019 VERIFY KU OK
Mon Apr  8 10:21:11 2019 Validating certificate extended key usage
Mon Apr  8 10:21:11 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Mon Apr  8 10:21:11 2019 VERIFY EKU OK
Mon Apr  8 10:21:11 2019 VERIFY OK: depth=0, CN=au354.nordvpn.com
Mon Apr  8 10:21:13 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Mon Apr  8 10:21:13 2019 [au354.nordvpn.com] Peer Connection Initiated with [AF_INET]144.48.37.133:1194
Mon Apr  8 10:21:14 2019 SENT CONTROL [au354.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Mon Apr  8 10:21:14 2019 AUTH: Received control message: AUTH_FAILED
Mon Apr  8 10:21:14 2019 SIGTERM[soft,auth-failure] received, process exiting
```

**Additional context**
My previous NordVPN account, with an email address without the + alias does actually work. I am still able to login to this container correctly with that account. I've tried updating the docker image to latest, but am already using that.

I've also confirmed the username and password with `docker exec "container_name" cat /vpn/auth` and they are set correctly.

I've also tried to escape the + symbol in the username, ie `phil\+example` and `phil\\+example` but unfortunately still without success.

**Comment by bubuntux** [comment]
interesting, the email is being pass properly into the auth file.. 
so.. seems like an issue with openvpn more than anything else imo

**Comment by bubuntux** [comment]
getting an account to test this is an issue to me.. so.. not sure how can i help.
maybe try to connect using openvpn directly to discard a possible issue with it

**Comment by philhawthorne** [comment]
Thanks @bubuntux 

I ended up contacting NordVPN and got them to change my username. Now everything works again. So now I can't replicate this anymore,.

For now I'll close this issue. If anyone comes across this, I guess its a known issue for now. But I suspect you're right, and that it is the underlying openVPN library that is the cause.

Cheers!
