### ISSUE TITLE
NordVPN Login error

### ISSUE THREAD

**Issue by Bosco911** [bubuntux/nordvpn#301]
Same problem as walmer26. Can't connect anymore.

image version : ghcr.io/bubuntux/nordvpn:v3.12.2

```
version: '3'
services:
  app:
    image: ghcr.io/bubuntux/nordvpn
    container_name: bubuntux
    restart: always
    cap_add:
    - NET_ADMIN
    environment:
    - TECHNOLOGY=NordLynx
    - USER=xxxxxx@xxxx.com 
    - PASS='xxx'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

```
```
2021/12/19 17:19:11 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": dial tcp: i/o timeout
Whoops! /run/nordvpn/nordvpnd.sock not found
Invalid Username or password.
[cmd] /bin/sh exited 1
```

_Originally posted by @Bosco911 in https://github.com/bubuntux/nordvpn/issues/300#issuecomment-997428818_

**Comment by Muneer91** [comment]
I have exactly the same issue. Updated image to latest but issue still persists. Error message is exactly the same.

**Comment by walmer26** [comment]
I have tried removing MFA from my NordVPN account, tried using email as user and original pass in the compose file. Also tried usi8ng user code and pass code provided by NordVPN account to use it in the compose file. Nothing works so far. Pulled latest TAG and also v3.12.2 Tag and nothing works, same error and same results in the log.

I will keep truing things up and you guys know on any update.

**Comment by benjaminsabatini** [comment]
Pretty sure the container no longer recognizes environment variables, too.

**Comment by walmer26** [comment]
> Pretty sure the container no longer recognizes environment variables, too.

That is what I thought as NordVPN credentials works using others' image. I have it working temporary with another image until bubuntux fix this one.

**Comment by kawangwong** [comment]
> 

Which image version are you using? I'm currently having this issue as well and it seems like Nordvpn updated something their backend that has switched to a token verification auth, but CLI doesn't seem to work after the verification.

**Comment by walmer26** [comment]
> > > Pretty sure the container no longer recognizes environment variables, too.
> > 
> > 
> > That is what I thought as NordVPN credentials works using others' image. I have it working temporary with another image until bubuntux fix this one.
> 
> @walmer26 Which image version are you using? I'm currently having this issue as well and it seems like Nordvpn updated something their backend that has switched to a token verification auth, but CLI doesn't seem to work after the verification.

I am using another dev container from docker hub, none of bubuntux version working currently for me. I hope he fixes this and than I will switch back to this container.

**Comment by Muneer91** [comment]
> > > > Pretty sure the container no longer recognizes environment variables, too.
> 
> > > 
> 
> > > 
> 
> > > That is what I thought as NordVPN credentials works using others' image. I have it working temporary with another image until bubuntux fix this one.
> 
> > 
> 
> > @walmer26 Which image version are you using? I'm currently having this issue as well and it seems like Nordvpn updated something their backend that has switched to a token verification auth, but CLI doesn't seem to work after the verification.
> 
> 
> 
> I am using another dev container from docker hub, none of bubuntux version working currently for me. I hope he fixes this and than I will switch back to this container.

Which image are you using that works? I need something for the now whilst this issue gets resolved.

**Comment by walmer26** [comment]
> > > > > Pretty sure the container no longer recognizes environment variables, too.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > That is what I thought as NordVPN credentials works using others' image. I have it working temporary with another image until bubuntux fix this one.
> > 
> > 
> > > 
> > 
> > 
> > > @walmer26 Which image version are you using? I'm currently having this issue as well and it seems like Nordvpn updated something their backend that has switched to a token verification auth, but CLI doesn't seem to work after the verification.
> > 
> > 
> > I am using another dev container from docker hub, none of bubuntux version working currently for me. I hope he fixes this and than I will switch back to this container.
> 
> Which image are you using that works? I need something for the now whilst this issue gets resolved.

I am using this one until bubuntux fix the login issue

https://hub.docker.com/r/azinchen/nordvpn

This is my current compose file, modify as you need:

version: "2"
services:
  vpn:
    image: azinchen/nordvpn:latest
    network_mode: bridge
    container_name: nordvpnwireguard
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=
      - PASS=
      - COUNTRY=US
      - GROUP=P2P
      - TECHNOLOGY=openvpn_udp
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
    ports:
      - 9091:9091
      - 9117:9117
      - 6881:6881
      - 6881:6881/udp
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - USER=admin
      - PASS=password
    volumes:
      - /srv/Config/Transmission:/config
      - /srv/dev-disk-by-label-Files/Downloads:/downloads
      - /srv/dev-disk-by-label-Files/Downloads/Watch:/watch
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - AUTO_UPDATE=true
    volumes:
      - /srv/Config/Jackett:/config
      - /srv/dev-disk-by-label-Files/Downloads:/downloads
    restart: always
    network_mode: service:vpn
	depends_on:
      - vpn

**Comment by Muneer91** [comment]
@walmer26 Okay so I tried that image too and it didn't work for me.. 😑

**Comment by johnmain** [comment]
I just tried using -legacy in the Environment section and used my email / password and was able to get VPN to auth.
I had Auth errors on my Linux command line as well which --legacy option worked there as well.

**Comment by walmer26** [comment]
> I just tried using -legacy in the Environment section and used my email / password and was able to get VPN to auth. I had Auth errors on my Linux command line as well which --legacy option worked there as well.

Thanks, could you please send us the portion of your environment setup on the compose file? So I can test when I get home.

**Comment by johnmain** [comment]
`version: "3.5"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    network_mode: bridge
    container_name: nordvpnwireguard
    cap_add:
      - NET_ADMIN    # Required
    devices:
      - /dev/net/tun
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - legacy
      - USER=email
      - PASS=password
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.88.0/24  # So it can be accessed within the local network
    ports:
      - ports you want forwarded`

**Comment by walmer26** [comment]
> version: "3.5" services: vpn: image: bubuntux/nordvpn:latest network_mode: bridge container_name: nordvpnwireguard cap_add: - NET_ADMIN # Required devices: - /dev/net/tun environment: # Review https://github.com/bubuntux/nordvpn#environment-variables - legacy - USER=email - PASS=password - CONNECT=United_States - TECHNOLOGY=NordLynx - NETWORK=192.168.88.0/24 # So it can be accessed within the local network ports: - ports you want forwarded

Nice!! I will test when I get home and let you know. Thank you!!

**Comment by Muneer91** [comment]
> I just tried using -legacy in the Environment section and used my email / password and was able to get VPN to auth.
> 
> I had Auth errors on my Linux command line as well which --legacy option worked there as well.

I tried this and didn't work for me. 
I also had an error message show up saying that the legacy option has no value so it will be set to blank
Maybe I'm doing something else wrong

**Comment by Trakkasure** [comment]
The issue I'm having is that the configuration doesn't seem to be using the environment variables. However, locally building and testing the environment (from within nord_login script) shows the environment is there. Next is to run the scripts manually from within the container.

**Comment by kawangwong** [comment]
> The issue I'm having is that the configuration doesn't seem to be using the environment variables. However, locally building and testing the environment (from within nord_login script) shows the environment is there. Next is to run the scripts manually from within the container.

It may be possible to just have the repo owner add the --legacy flag in the command in Dockerfile and then rebuild the image and upload. This could solve most people's issue, though I don't know if it's possible to create an environment variable that can do the same.

**Comment by johnmain** [comment]
Only other change I made was to turn off MFA.

**Comment by Trakkasure** [comment]
> It may be possible to just have the repo owner add the --legacy flag in the command in Dockerfile and then rebuild the image and upload. This could solve most people's issue, though I don't know if it's possible to create an environment variable that can do the same.

The nord_login script already has the legacy option in the latest.

**Comment by Muneer91** [comment]
> Only other change I made was to turn off MFA.

I did that too  now I get too many login request error

**Comment by Muneer91** [comment]
> > It may be possible to just have the repo owner add the --legacy flag in the command in Dockerfile and then rebuild the image and upload. This could solve most people's issue, though I don't know if it's possible to create an environment variable that can do the same.
> 
> 
> 
> The nord_login script already has the legacy option in the latest.
> 
> 

So this would mean the legacy option in env vars is redundant?

**Comment by kawangwong** [comment]
> > > It may be possible to just have the repo owner add the --legacy flag in the command in Dockerfile and then rebuild the image and upload. This could solve most people's issue, though I don't know if it's possible to create an environment variable that can do the same.
> > 
> > 
> > The nord_login script already has the legacy option in the latest.
> 
> So this would mean the legacy option in env vars is redundant?

Sorry. No. @Trakkasure correctly pointed out to me that the legacy call is already built into the nord_login script, which is run on Dockerfile during build.

**Comment by Trakkasure** [comment]
> So this would mean the legacy option in env vars is redundant?
Indeed. 

What I would like to know is why I get a lot of these in my logs: (None of these values are correct)
Technology set to: OPENVPN
NordVPN App Connection Settings:
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
CyberSec: disabled
DNS: 
IPv6: disabled
Notify: disabled
Auto-connect: disabled
[services.d] done.

**Comment by Muneer91** [comment]
> > > > It may be possible to just have the repo owner add the --legacy flag in the command in Dockerfile and then rebuild the image and upload. This could solve most people's issue, though I don't know if it's possible to create an environment variable that can do the same.
> 
> > > 
> 
> > > 
> 
> > > The nord_login script already has the legacy option in the latest.
> 
> > 
> 
> > So this would mean the legacy option in env vars is redundant?
> 
> 
> 
> Sorry. No. @Trakkasure correctly pointed out to me that the legacy call is already built into the nord_login script, which is run on Dockerfile during build.

What I mean, adding -legacy in the docker compose file is redundant?

**Comment by Muneer91** [comment]
> > So this would mean the legacy option in env vars is redundant?
> 
> Indeed. 
> 
> 
> 
> What I would like to know is why I get a lot of these in my logs: (None of these values are correct)
> 
> Technology set to: OPENVPN
> 
> NordVPN App Connection Settings:
> 
> Technology: OPENVPN
> 
> Protocol: UDP
> 
> Firewall: enabled
> 
> KillSwitch: disabled
> 
> Obfuscate: disabled
> 
> CyberSec: disabled
> 
> DNS: 
> 
> IPv6: disabled
> 
> Notify: disabled
> 
> Auto-connect: disabled
> 
> [services.d] done.

Yes I agree, I get the same in the logs and I definitely changed some of these I.e technology should be nordlynx

**Comment by Trakkasure** [comment]
I see this in my logs...
Missing NORDVPN socket in /run/nordvpn/nordvpn.sock

This happens because the nordvpnd service isn't creating the socket. this happens before login.
I modified /etc/services.d/nordvpn/data/check  to log that message if the socket doesn't exist.
These could be that the service is starting, and the check is to wait for it to create the socket.

I also see: s6-maximumtime: warning: unable to wait for child process: Operation timed out

So I'm trying to figure out what is going on there.

**Comment by Trakkasure** [comment]
Ok.. so basically, the nordvpnd can't make a connection to get config params when starting: 
2021/12/22 error on making client request: Head "https://downloads.ns8469rfvth42.xyz/configs/dns/cybersec.json": dial tcp: i/o timeout

this leads to the other issues, and why the socket isn't created.

Anyone know why it would suddenly fail to be able to make calls to these services?
I'm using the default bridge as the gateway, using DNS parameter to my local DNS on same net, and have NETWORK set to local net.

I can also open a bash session on the container and manually CURL any one of the failing JSON url calls and get a response. So, this seems to be an issue with nordvpn and docker. Can anyone illuminate with a possible solution?

**Comment by Muneer91** [comment]
> Ok.. so basically, the nordvpnd can't make a connection to get config params when starting: 
> 
> 2021/12/22 error on making client request: Head "https://downloads.ns8469rfvth42.xyz/configs/dns/cybersec.json": dial tcp: i/o timeout
> 
> 
> 
> this leads to the other issues, and why the socket isn't created.
> 
> 
> 
> Anyone know why it would suddenly fail to be able to make calls to these services?
> 
> I'm using the default bridge as the gateway, using DNS parameter to my local DNS on same net, and have NETWORK set to local net.
> 
> 
> 
> I can also open a bash session on the container and manually CURL any one of the failing JSON url calls and get a response. So, this seems to be an issue with nordvpn and docker. Can anyone illuminate with a possible solution?

So there's another issue logged on this project, #297. 

In there it explains that nord has disable some features and only allow access through a web browser or something like that. 

There's apparently a solution to use wire guard and some instructions but I have yet to try it out.

**Comment by Trakkasure** [comment]
> There's apparently a solution to use wire guard and some instructions but I have yet to try it out.

Using --legacy should allow logging in without the 2FA requirement.
The issue I see above is the daemon, and happening before any login.

**Comment by bubuntux** [comment]
seems like you guys are running into an issue with s6-overlay, i don't have a synology system to test/fix this, so.. is up to you guys, once you guys find the solution lmk, so i can merge into the image ty,

**Comment by bubuntux** [comment]
in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx

**Comment by jibsaramnim** [comment]
Digging a little further, it seems like there might be something related to the container's firewall that prevents a successful login. By temporarily removing all iptables rules and setting up basic allow rules for everything, I was able to successfully log in using the container's `nord_login` command. 

Tested in a fresh container. To replicate:

- Launch a fresh container directly into a bash prompt (`docker run -it --rm --cap-add=NET_ADMIN -e USER='<<email>>' -e PASS='<<pass>>' ghcr.io/bubuntux/nordvpn:latest /usr/bin/with-contenv bash`)
- Clear all firewall rules and allow all trafic (`iptables -F && iptables -X && iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT && iptables -P FORWARD ACCEPT`)
- Run `nord_login`, login should as usual.

I ended up looking in this corner after noticing commands like `apt update` didn't work either. I am not sure if anything has recently changed in the firewall or DNS resolver corner, if that's the case, perhaps the solution is somewhere there.

> in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx

I suppose longer-term this might be the best solution (or a way to rely on the new `--nordaccount` login method, if a login token can be preserved after initial login anyway). The currently recommended way to obtain the private key would still benefit from this container working as before though. I suppose relying on a different container just to obtain the key could also work, but it'd certainly be nice if this one could be brought back, at least for as long as `--legacy` remains an available login method :).

**Comment by Bosco911** [comment]
> in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx

Thanks for the tip, I switched to nordlynx. Everything work perfectly!

**Comment by ginodesilva** [comment]
> Thanks for the tip, I switched to nordlynx. Everything work perfectly!
Do you have it working on a Synology DSM 7? I tried switching.

**Comment by Bosco911** [comment]
> in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx

Thanks for the tip, I switched to nordlynx. Everything work perfectly!

> > Thanks for the tip, I switched to nordlynx. Everything work perfectly!
> > Do you have it working on a Synology DSM 7? I tried switching.

Nope. I'm running in a Intel Nuc.

If you want to specify a country, I found this post :

 #https://github.com/bubuntux/nordlynx/discussions/8

**Comment by remeswim** [comment]
> > in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx
> 
> Thanks for the tip, I switched to nordlynx. Everything work perfectly!

Sorry for the noob question but how exactly did you get the needed private key variable to achieve this? been trying to get this one for a day using instructions found but 'nordvpn login' doesn't work anymore from a terminal and I can't seem to get it however I try, even with the direct container and 'nord_login' from jibsaramnim above... 

would really like to give nordlynx a try but stuck ...

**Comment by Bosco911** [comment]
# https://github.com/bubuntux/nordlynx#environment

https://forum.openwrt.org/t/instruction-config-nordvpn-wireguard-nordlynx-on-openwrt/89976

**Comment by Muneer91** [comment]
So I had the same issue, took me a couple days to figure it out but did the same as Bosco. 
Spun up a simple vm. Followed those instructions until the browser auth didn't work for me. 

So instead I ran 
sudo NordVPN login --username=email@email.com --password=Pa55w0rd

From this point I was able to change technology to nordlynx, connect to a server and extract the private key

**Comment by Mattie112** [comment]
I also have this issue, I did activate MFA not to long ago. Is this supposed to work with MFA? I can also generate a "service credentials" but that also don't seem to work. Would it be possible to support that? I can imagine that can work if you have MFA enabled for your account.

**Comment by remeswim** [comment]
Thx @Muneer91, so stupid ... it indeed has to be performed on a client with a gui, tried it on a Pi with Ubuntu first but failed, had to do it on a VM Ubuntu on the mac to get it working ...

@Mattie112 my MFA is still on, this is also separate from the service credentials

thx all

**Comment by Muneer91** [comment]
No problem @remeswim , glad you got it working in the end.

**Comment by cciechad** [comment]
Issue seems to be fixed. Not sure how Nord must have made a change. It's now working with the old user/password identical docker compose file no update to the docker image.

**Comment by M2k80** [comment]
on unraid nothing is working..never got this docker running
2021/12/25 09:04:51 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Failed sending data to the peer

[services.d] done.
Invalid Username or password.
[cmd] /bin/sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by Mattie112** [comment]
@cciechad With the NordVPN container or the NordLynx one? I still have the incorrect password error. (Have not yet tried the NordLynx).

**Comment by cciechad** [comment]
> @cciechad With the NordVPN container or the NordLynx one? I still have the incorrect password error. (Have not yet tried the NordLynx).

With the NordVPN container. It broke for me about 5 days ago(missing socket user/pass error) and I didn't have time to troubleshoot. I ended up trying to grab a console yesterday and it was magically connected(its the same image and compose file I was originally using so I assume it was something on the nord side?).

**Comment by kawangwong** [comment]
Just wanted to tell everyone who has been having issues who have tried above and didn't work, disable MFA first. There's something weird about MFA and the nordvpn login command. I tried on a headless and GUI linux, still doesn't work. Only Windows for me.

I switched over images, and used the instructions in the other repo with MFA off first to grab the private key, then switched MFA back on and logged in using private key.

**Comment by rexmen9999** [comment]
I'm running in unraid and turning off MFA lets me connect again, but if I turn MFA back on it won't connect on a restart of the container.

**Comment by cciechad** [comment]
Just an FYI I've always had MFA disabled on my account(never enabled) and I hit the issue. I feel like it has to be something on the Nord side as it magically fixed itself for me without any changes to the compose or the docker image. Also it appears like there are 2 issues.

1. The socket missing / logon. (Which I saw for multiple days and was resolved with no changes on my side)
2. The QUIC request fail(which I've never seen but many others seem to have reported concurrently with this issue).

**Comment by tschmoderer** [comment]
I have the same issue that was originally described. So what is the best way to solve it ?

**Comment by benjaminsabatini** [comment]
Eh... I removed MFA and used my ordinary login/password and now it works. It seems daft, but there you go...

**Comment by tschmoderer** [comment]
I do not have MFA activated on my account

**Comment by simzdk** [comment]
> Eh... I removed MFA and used my ordinary login/password and now it works. It seems daft, but there you go...

Same here. Removed MFA and it worked. Running unraid and the nordvpn container.

**Comment by tschmoderer** [comment]
I managed to solve the issue. For the record I will leave my solution here. 

Material : Running docker on raspberry pi 4 with debian 10 (that's the key point)

Detected problem: By running a docker container with s6on/ubuntu (base container of bubuntux/nordvpn), I observed that the command 'apt update' failed. Therefore, the tools 'curl/wireguard...' could not be installed, leading to a problem in the installation of nordvpn. 

Solution : 
The solution is to manually update the library libseccomp2 on the host machine (my pi) : https://packages.debian.org/sid/libseccomp2 to version 2.5.3 . 
After rebooting the pi, the issue was solved and I could normally connect to nordvpn.

**Comment by d-tork** [comment]
> Solution : The solution is to manually update the library libseccomp2 on the host machine (my pi) 

I thought the whole thing with Docker is that it's isolated from the host system... why would any of this depend on a library on your host, when the apt-update used by the container should be the one packaged up in the docker base image?

**Comment by tschmoderer** [comment]
Well, that's almost true. Docker still rely on the host system. For instance, you can not run x86 apps in docker on arm devices and reciprocally.

**Comment by lizardkingDOTca** [comment]
I had been running version '3.9.5-1' for a long time (synology nas DSM 7.0.1-42218), but today my internet when down for a long time and coming back up it wouldn't log in. So updated to  '3.12.2' but was still getting this log on issue. After trying multiple configuration and found the issue was due to TUN module.  All this to say, I follow the instruction here https://memoryleak.dev/post/fix-tun-tap-not-available-on-a-synology-nas/ and it works

**Comment by traxo-xx** [comment]
> Digging a little further, it seems like there might be something related to the container's firewall that prevents a successful login. By temporarily removing all iptables rules and setting up basic allow rules for everything, I was able to successfully log in using the container's `nord_login` command.
> 
> Tested in a fresh container. To replicate (Note that this only for testing/debugging purposes, not for actual usage with your setup):
> 
>     * Launch a fresh container directly into a bash prompt (`docker run -it --rm --cap-add=NET_ADMIN -e USER='<<email>>' -e PASS='<<pass>>' ghcr.io/bubuntux/nordvpn:latest /usr/bin/with-contenv bash`)
> 
>     * Clear all firewall rules and allow all trafic (`iptables -F && iptables -X && iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT && iptables -P FORWARD ACCEPT`)
> 
>     * Run `nord_login`, login should as usual.
> 
> 
> I ended up looking in this corner after noticing commands like `apt update` didn't work either. I am not sure if anything has recently changed in the firewall or DNS resolver corner, if that's the case, perhaps the solution is somewhere there.
> 
> > in any case i would recommend to migrate to https://github.com/bubuntux/nordlynx
> 
> I suppose longer-term this might be the best solution (or a way to rely on the new `--nordaccount` login method, if a login token can be preserved after initial login anyway). The currently recommended way to obtain the private key would still benefit from this container working as before though. I suppose relying on a different container just to obtain the key could also work, but it'd certainly be nice if this one could be brought back, at least for as long as `--legacy` remains an available login method :).

I'm facing the same problem. I ran bash inside the container and I couldn't curl anything unless I either flushed iptables as described by @jibsaramnim oder added this rule: `iptables -A OUTPUT -o eth0 -j ACCEPT`. After I did either of those things, everything worked fine.

Btw.: When the container can't connect to the outside world that will also cause a misleading "Invalid Username or password." error due to this block in the `nord_connect` script: 
```
nordvpn login --legacy --username "${USER}" --password "${PASS}" || {
  echo "Invalid Username or password."
  exit 1
}
```

**Comment by bubuntux** [comment]
adding 
`iptables -A OUTPUT -o eth0 -j ACCEPT`
will render useless the vpn lol 

i recommend migrate to the new container https://github.com/bubuntux/nordlynx this issue is probably the same as #309

**Comment by scana** [comment]
Hello @bubuntux thank you for working on this!
Is there any migration guide? Assuming that I already use `nordvpn` container with NordLynx?

**Comment by emrekasg** [comment]
Adding --cap-add=ALL solved the issue for me

**Comment by vvan16914** [comment]
You are in a country where NordVPN servers are not available for downloading boot files. To ensure successful installation, turn on any other VPN and run the installer.
