### ISSUE TITLE
Nordvpn failing overnight

### ISSUE THREAD

**Issue by pi-e-3** [bubuntux/nordvpn#303]
**Describe the bug**
Not entirely sure what is going on here, but I am running a stack with nordvpn and transmission on my DSM 7 Synology NAS. Some time overnight it appears to end up in a loop (see log bellow) and will no longer function until I rebuilt the stack. Prior to this it works just fine, no issues. I have been unable to catch the moment it happens, and due to the log spam it pushes any entries out that might provide a clue. 

**To Reproduce using docker-compose**

```
version: "3.5"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    cap_add:
      - NET_ADMIN               # Required
    environment:
    # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PUID=1026
      - PGID=101
      - USER=    # Required
      - PASS=     # Required
      - CONNECT=Canada
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
      - CYBER_SEC=disable
      - DNS=1.1.1.1
    ports:
      - 32771:9091
  torrent:
    image: ghcr.io/linuxserver/transmission:latest
    environment:
      - PUID=1026
      - PGID=101
    volumes:
      - /volume1/Server/Downloads:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: always
```

**Logs**
```
2021/12/22 12:56:07 error on making client request: Head "https://downloads.ltlxvxjjmvhn.me/configs/dns/cybersec.json": dial tcp: lookup downloads.ltlxvxjjmvhn.me on 1.1.1.1:53: write udp 172.18.0.2:38785->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:07 error on making client request: Head "https://downloads.tptn0rhbtj.info/configs/dns/cybersec.json": dial tcp: lookup downloads.tptn0rhbtj.info on 1.1.1.1:53: write udp 172.18.0.2:48522->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:07 error on making client request: Head "https://downloads.mxo4bkqvdityebzvp.xyz/configs/dns/cybersec.json": dial tcp: lookup downloads.mxo4bkqvdityebzvp.xyz on 1.1.1.1:53: write udp 172.18.0.2:52148->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:07 error on making client request: Head "https://downloads.wutlk3t9mybdz.info/configs/dns/cybersec.json": dial tcp: lookup downloads.wutlk3t9mybdz.info on 1.1.1.1:53: write udp 172.18.0.2:53658->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:07 rotating: transport rotator: can't find gateway
2021/12/22 12:56:08 [Info] Daemon has started
2021/12/22 12:56:08 Get "https://cdn.zwyr157wwiu6eior.com/configs/dns/cybersec.json": dial tcp: lookup cdn.zwyr157wwiu6eior.com on 1.1.1.1:53: write udp 172.18.0.2:36294->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.otmwumj6qw5em0zb.me/configs/dns/cybersec.json": dial tcp: lookup downloads.otmwumj6qw5em0zb.me on 1.1.1.1:53: write udp 172.18.0.2:58672->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.ns8469rfvth42.xyz/configs/dns/cybersec.json": dial tcp: lookup downloads.ns8469rfvth42.xyz on 1.1.1.1:53: write udp 172.18.0.2:40167->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.mzhlhrfr8z.info/configs/dns/cybersec.json": dial tcp: lookup downloads.mzhlhrfr8z.info on 1.1.1.1:53: write udp 172.18.0.2:49254->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.se3v5tjfff3aet.me/configs/dns/cybersec.json": dial tcp: lookup downloads.se3v5tjfff3aet.me on 1.1.1.1:53: write udp 172.18.0.2:57085->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.p99nxpivfscyverz.me/configs/dns/cybersec.json": dial tcp: lookup downloads.p99nxpivfscyverz.me on 1.1.1.1:53: write udp 172.18.0.2:50877->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.wutlk3t9mybdz.info/configs/dns/cybersec.json": dial tcp: lookup downloads.wutlk3t9mybdz.info on 1.1.1.1:53: write udp 172.18.0.2:42631->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.mxo4bkqvdityebzvp.xyz/configs/dns/cybersec.json": dial tcp: lookup downloads.mxo4bkqvdityebzvp.xyz on 1.1.1.1:53: write udp 172.18.0.2:49463->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.tptn0rhbtj.info/configs/dns/cybersec.json": dial tcp: lookup downloads.tptn0rhbtj.info on 1.1.1.1:53: write udp 172.18.0.2:57679->1.1.1.1:53: write: operation not permitted
2021/12/22 12:56:08 error on making client request: Head "https://downloads.nordcdn.com/configs/dns/cybersec.json": dial tcp: lookup downloads.nordcdn.com on 1.1.1.1:53: write udp 172.18.0.2:47995->1.1.1.1:53: write: operation not permitted
```

**Comment by wayne-robinson** [comment]
I had the same problem on my DSM 7 Synology NAS. The problem occurs on versions of the image after ghcr.io/bubuntux/nordvpn:v3.10.0-1-1. Try changing the image in your compose file to image:ghcr.io/bubuntux/nordvpn:v3.10.0-1-1

**Comment by Rickexe** [comment]
How are you even able to login? There's a massive issue on this repo about the problem that nobody can log in.

**Comment by pi-e-3** [comment]
I couldn't tell you. That aspect works fine for me.

**Comment by pi-e-3** [comment]
> I had the same problem on my DSM 7 Synology NAS. The problem occurs on versions of the image after ghcr.io/bubuntux/nordvpn:v3.10.0-1-1. Try changing the image in your compose file to image:ghcr.io/bubuntux/nordvpn:v3.10.0-1-1

Interestingly, using this build actually breaks my login info. 

I reverted to bubuntux/nordvpn:v3.9.5-1 (initially found in the guide I followed), I will see if this also causes issues.

**Comment by pi-e-3** [comment]
Reverting to 3.9.5-1 has fixed this issue. 

An entire day worth of logs is now quite brief:

'[2021-12-22T15:21:35+00:00] Enabling connection to nordvpn group
iptables: No chain/target/match by that name.
[2021-12-22T15:21:35+00:00] group match failed, fallback to open necessary ports
[2021-12-22T15:21:35+00:00] ip6 group match failed, fallback to open necessary ports
[2021-12-22T15:21:35+00:00] Enabling connection to docker network
[2021-12-22T15:21:35+00:00] Enabling connection to network 192.168.1.0/24
[2021-12-22T15:21:35+00:00] Restarting the service
[2021-12-22T15:21:35+00:00] Waiting for the service to start
[2021-12-22T15:21:35+00:00] Logging in

-
  

-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
[2021-12-22T15:21:39+00:00] Setting up NordVPN Version 3.9.5
CyberSec is already set to 'disabled'.
DNS is set to '1.1.1.1' successfully.
Technology is successfully set to 'NordLynx'.
Subnet 172.19.0.0/16 is whitelisted successfully.
Subnet 192.168.1.0/24 is whitelisted successfully.
[2021-12-22T15:21:39+00:00] Connecting...

-
  
A new version of NordVPN is available! Please update the application.

-
\
|
/
-
\
|
  
Connecting to Canada #1475 (ca1475.nordvpn.com)

-
  
You are connected to Canada #1475 (ca1475.nordvpn.com)!

-
  
[2021-12-22T19:52:10+00:00] Unstable connection detected!

-
  
A new version of NordVPN is available! Please update the application.

-
  
Status: Connected
Current server: ca1475.nordvpn.com
Country: Canada
City: Toronto
Your new IP: 37.19.213.192
Current technology: NordLynx
Current protocol: UDP
Transfer: 7.39 GiB received, 12.17 GiB sent
Uptime: 4 hours 30 minutes 30 seconds
[2021-12-22T19:52:10+00:00] Restarting the service
[2021-12-22T19:52:40+00:00] Waiting for the service to start
[2021-12-22T19:52:41+00:00] Connecting...

-
  

-
\
|
/
-
  
Connecting to Canada #1086 (ca1086.nordvpn.com)

-
  
You are connected to Canada #1086 (ca1086.nordvpn.com)!

-
  
[2021-12-23T00:13:08+00:00] Unstable connection detected!

-
  
A new version of NordVPN is available! Please update the application.

-
  
Status: Connected
Current server: ca1086.nordvpn.com
Country: Canada
City: Toronto
Your new IP: 172.98.66.15
Current technology: NordLynx
Current protocol: UDP
Transfer: 15.10 GiB received, 0.87 GiB sent
Uptime: 4 hours 20 minutes 26 seconds
[2021-12-23T00:13:08+00:00] Restarting the service
[2021-12-23T00:13:38+00:00] Waiting for the service to start
[2021-12-23T00:13:38+00:00] Connecting...

-
  

-
\
|
/
-
\
  
Connecting to Canada #1437 (ca1437.nordvpn.com)

-
  
You are connected to Canada #1437 (ca1437.nordvpn.com)!

-
  
[2021-12-23T04:34:11+00:00] Unstable connection detected!

-
  
A new version of NordVPN is available! Please update the application.

-
  
Status: Connected
Current server: ca1437.nordvpn.com
Country: Canada
City: Toronto
Your new IP: 37.19.213.2
Current technology: NordLynx
Current protocol: UDP
Transfer: 70.67 MiB received, 1.10 GiB sent
Uptime: 4 hours 20 minutes 31 seconds
[2021-12-23T04:34:11+00:00] Restarting the service
[2021-12-23T04:34:41+00:00] Waiting for the service to start
[2021-12-23T04:34:41+00:00] Connecting...

-
  

-
\
|
/
-
  
Connecting to Canada #1025 (ca1025.nordvpn.com)

-
  
You are connected to Canada #1025 (ca1025.nordvpn.com)!

-
  
[2021-12-23T08:55:07+00:00] Unstable connection detected!

-
  
A new version of NordVPN is available! Please update the application.

-
  
Status: Connected
Current server: ca1025.nordvpn.com
Country: Canada
City: Toronto
Your new IP: 66.115.145.42
Current technology: NordLynx
Current protocol: UDP
Transfer: 65.86 MiB received, 0.89 GiB sent
Uptime: 4 hours 20 minutes 25 seconds
[2021-12-23T08:55:07+00:00] Restarting the service
[2021-12-23T08:55:37+00:00] Waiting for the service to start
[2021-12-23T08:55:37+00:00] Connecting...

-
  

-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
  
Connecting to Canada #1015 (ca1015.nordvpn.com)

-
  
You are connected to Canada #1015 (ca1015.nordvpn.com)!

-
  
[2021-12-23T13:16:10+00:00] Unstable connection detected!

-
  
A new version of NordVPN is available! Please update the application.

-
  
Status: Connected
Current server: ca1015.nordvpn.com
Country: Canada
City: Toronto
Your new IP: 66.115.145.12
Current technology: NordLynx
Current protocol: UDP
Transfer: 50.11 MiB received, 0.67 GiB sent
Uptime: 4 hours 20 minutes 26 seconds
[2021-12-23T13:16:10+00:00] Restarting the service
[2021-12-23T13:16:40+00:00] Waiting for the service to start
[2021-12-23T13:16:40+00:00] Connecting...

-
  

-
\
|
/
-
  
Connecting to Canada #1471 (ca1471.nordvpn.com)

-
  
You are connected to Canada #1471 (ca1471.nordvpn.com)!'

**Comment by pi-e-3** [comment]
Fixed by reverting to 3.9.5-1.

Anyone else on DSM 7 I advise do the same.

**Comment by TheWhiteWarlock** [comment]
Had the same issue so glad I found this post, the only issue with 3.9.5-1 for what ever reason and I have only started on the docker journey a month ago is that it fails the health check in portainer which is stuck on a "starting" status although the container is up and running.

**Comment by Phamine** [comment]
I also found that I had this issue. Hopefully the next  update fixes this

**Comment by lfilho** [comment]
Reverting to 3.9.5 didn't help for me. Using it on Synology DSM 7 and got this:

```
luiz@balaio:/volume1/src/pipipitchu$ sudo docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW -e USER=myUser -e PASS=myPass -e TECHNOLOGY=NordLynx bubuntux/nordvpn:v3.9.5-1
[2022-03-30T01:40:29+00:00] Firewall is up, everything has to go through the vpn
[2022-03-30T01:40:29+00:00] Enabling connection to secure interfaces
[2022-03-30T01:40:29+00:00] Enabling connection to nordvpn group
iptables: No chain/target/match by that name.
[2022-03-30T01:40:29+00:00] group match failed, fallback to open necessary ports
[2022-03-30T01:40:29+00:00] ip6 group match failed, fallback to open necessary ports
[2022-03-30T01:40:29+00:00] Enabling connection to docker network
[2022-03-30T01:40:29+00:00] Restarting the service
[2022-03-30T01:40:29+00:00] Waiting for the service to start
[2022-03-30T01:40:29+00:00] Logging in
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
[2022-03-30T01:41:34+00:00] Invalid Username or password.
```

**Comment by lfilho** [comment]
And using latest version:

```
sudo docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW -e USER=myUser -e PASS=myPass -e TECHNOLOGY=NordLynx bubuntux/nordvpn
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] docker_utils: applying...
[fix-attrs.d] docker_utils: exited 0.
[fix-attrs.d] nord_utils: applying...
[fix-attrs.d] nord_utils: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-firewall: executing...
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-tun: executing...
[cont-init.d] 10-tun: exited 0.
[cont-init.d] 20-inet: executing...
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing...
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing...
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing...
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing...
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-maximumtime: warning: unable to wait for child process: Operation timed out
s6-svwait: fatal: timed out
Whoops! /run/nordvpn/nordvpnd.sock not found
Invalid Username or password.
[cmd] /bin/sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
