### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by Dimension02000** [bubuntux/nordvpn#309]
My setup has been working for months on end without any problems until recently I had to reboot my Ubuntu desktop. Once it was rebooted NordVPN would not work within my docker container. I removed the setup and ran docker-compose up command in the same directly as my yml file but still the VPN is not working correctly.  The issue appears to be a credential problem but it is the same credentials that I can log into NordVPN's site along with my Windows box.

Here is my yml file:
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USERNAME=xxxxxxx
      - PASSWORD=xxxxxxx
      - COUNTRY=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.10.0/24
      - KILLSWITCH=Enable
    ports:
      - 8080:8080
      - 6789:6789
      - 8989:8989
      - 7878:7878

Here is the output I am getting when I do a docker-compose up:
Recreating nordvpndockercompose_vpn_1 ... done
Attaching to nordvpndockercompose_vpn_1
vpn_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
vpn_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
vpn_1  | [fix-attrs.d] applying ownership & permissions fixes...
vpn_1  | [fix-attrs.d] docker_utils: applying... 
vpn_1  | [fix-attrs.d] docker_utils: exited 0.
vpn_1  | [fix-attrs.d] nord_utils: applying... 
vpn_1  | [fix-attrs.d] nord_utils: exited 0.
vpn_1  | [fix-attrs.d] done.
vpn_1  | [cont-init.d] executing container initialization scripts...
vpn_1  | [cont-init.d] 00-firewall: executing... 
vpn_1  | Firewall is up, everything has to go through the vpn
vpn_1  | [cont-init.d] 00-firewall: exited 0.
vpn_1  | [cont-init.d] 10-tun: executing... 
vpn_1  | [cont-init.d] 10-tun: exited 0.
vpn_1  | [cont-init.d] 20-inet: executing... 
vpn_1  | Enabling connection to secure interface and docker network
vpn_1  | [cont-init.d] 20-inet: exited 0.
vpn_1  | [cont-init.d] 20-inet6: executing... 
vpn_1  | No inet6 network
vpn_1  | [cont-init.d] 20-inet6: exited 0.
vpn_1  | [cont-init.d] 30-route: executing... 
vpn_1  | Enabling connection to network 192.168.10.0/24
vpn_1  | [cont-init.d] 30-route: exited 0.
vpn_1  | [cont-init.d] 30-route6: executing... 
vpn_1  | [cont-init.d] 30-route6: exited 0.
vpn_1  | [cont-init.d] 40-allowlist: executing... 
vpn_1  | [cont-init.d] 40-allowlist: exited 0.
vpn_1  | [cont-init.d] done.
vpn_1  | [services.d] starting services
vpn_1  | 2022/01/27 19:04:14 [Info] Daemon has started
vpn_1  | 2022/01/27 19:04:14 Kill Switch set to: disabled
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 Auto-connect set to: disabled
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 DNS set to: disabled
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 CyberSec set to: disabled
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 Protocol set to: UDP
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 Technology set to: OPENVPN
vpn_1  | NordVPN App Connection Settings:
vpn_1  | Technology: OPENVPN
vpn_1  | Protocol: UDP
vpn_1  | Firewall: enabled
vpn_1  | KillSwitch: disabled
vpn_1  | Obfuscate: disabled
vpn_1  | CyberSec: disabled
vpn_1  | DNS: 
vpn_1  | IPv6: disabled
vpn_1  | Notify: disabled
vpn_1  | Auto-connect: disabled
vpn_1  | 
vpn_1  | 2022/01/27 19:04:14 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Couldn't connect to server
vpn_1  | [services.d] done.
A new version of NordVPN is available! Please update the application.
Please enter your login details.
vpn_1  | Stdin/Stdout should be terminal
vpn_1  | Invalid Username or password.
vpn_1  | [cmd] /bin/sh exited 1
vpn_1  | [cont-finish.d] executing container finish scripts...
vpn_1  | [cont-finish.d] done.
vpn_1  | [s6-finish] waiting for services.
vpn_1  | [s6-finish] sending all processes the TERM signal.
vpn_1  | [s6-finish] sending all processes the KILL signal and exiting.
nordvpndockercompose_vpn_1 exited with code 1

**Comment by Dimension02000** [comment]
Made some adjustments to my yml file which now looks like this:
`version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn:latest
    dns:
      - 103.86.96.100 #NordVPN DNS
      - 103.86.99.100 #NordVPN DNS
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USERNAME=xxxxx
      - PASSWORD=xxxxxx
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.10.0/24
      - KILLSWITCH=Enable
    ports:
      - 8080:8080
      - 6789:6789
      - 8989:8989
      - 7878:7878`

But I am still having the same connection issue.

**Comment by sUyMur** [comment]
Seeing the same issue now. In my log I see "too many api requests", but can connect fine with other devices. 
Will provide logs/compose later.

**Comment by sUyMur** [comment]
I've build the image with the newest version 3.12.3 and it works again. Will you further maintain/build new versions for this image?

**Comment by Dimension02000** [comment]
I tired with the latest version but it did not help resolve my issue. I ended up unfortunately going with a different developers version. :(

**Comment by sUyMur** [comment]
I had to change the Version in the Dockerfile from 3.12.2 to 3.12.3 and then build the image manually.

Currently looking into forking this repo and building images automatically when a new version is released. I thought this was already the case for this repo. 

Waiting for a response from @bubuntux.

**Comment by Pluckerpluck** [comment]
Ah, clearly a new problem. Adding that I am too getting a Not Connecting error now. Which is unfortuante timing as I'm tired and ill, and I just don't want to be debugging this right now.

Let me know if you get a new build deployed to some repo @sUyMur , or what did you use @Dimension02000 ?

**Comment by sUyMur** [comment]
Set it up for now. [suymur/nordvpn](https://hub.docker.com/r/suymur/nordvpn/)

I guess I will have my update/build script running for now and just push new images out, when there is a new version of nordvpn in their [repo](https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/).

Replacing `image: bubuntux/nordvpn:latest` with `image: suymur/nordvpn:latest` will fix it for now.

**Comment by bubuntux** [comment]
i would recommend you guys to move to the new image using nordlynx more directly, making the container lighter and faster  https://github.com/bubuntux/nordlynx i'm happy to accept a merge request with the version bump in this repo

**Comment by bubuntux** [comment]
the autoupdate process in this repository is problematic since nordvpn changes dependencies and mess things up very often, by using the wireguard alone simplify things and an auto update was more straight forward.

**Comment by sUyMur** [comment]
> i would recommend you guys to move to the new image using nordlynx more directly, making the container lighter and faster  https://github.com/bubuntux/nordlynx i'm happy to accept a merge request with the version bump in this repo 

Fair enough, I couldn't get it to work when I tried. Guess I'll have a look again at some point.
I'll be looking into the merge request later, but it was just a version bump from 3.12.2 to 3.12.3.

**Comment by b-kamphorst** [comment]
> > i would recommend you guys to move to the new image using nordlynx more directly, making the container lighter and faster  https://github.com/bubuntux/nordlynx i'm happy to accept a merge request with the version bump in this repo
> 
> Fair enough, I couldn't get it to work when I tried. Guess I'll have a look again at some point. I'll be looking into the merge request later, but it was just a version bump from 3.12.2 to 3.12.3.

Hi @sUyMur, it took me quite some time and effort but I got it working for Synology now. Probably not optimal, but you might find it helpful: https://github.com/bubuntux/nordlynx/discussions/41. I know you are quite an expert, so please feel free to share your thoughts there as well :)

**Comment by sUyMur** [comment]
Thank you! After carefully reading it I got it working. 😁 
I'll have both running for a bit and see how nordlynx will work out for me.
