### ISSUE TITLE
How to use --net=container:vpn

### ISSUE THREAD

**Issue by VMax2** [bubuntux/nordvpn#31]
Hi, first thank you for this amazing container, i'm using it in docker/Openmediavault with the GUI and it work like a charm; as i'm new to docker i would need some tips...
I would like to use it just for what it has born, so,  for istance, to route Transmission container traffic throught the vpn container.
I read i should use --net=container:vpn in the Transmission container but i don't know how to do that or better where to add it in the graphic environment.
I don't know if this is the right place to ask this but could you help me anyway please?
Thank you in advance!!!!!

**Comment by bubuntux** [comment]
you will have to check the documentation for the GUI that you are using, sry there's not much i can do.
