### ISSUE TITLE
GLIBC_2.28 lib not found

### ISSUE THREAD

**Issue by Smiggel** [bubuntux/nordvpn#318]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**
Updated to the latest image (bubuntux/nordvpn). It seems the latest container image is missing files. Or it's missing for the Raspberry Pi.

**Logs**
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
s6-maximumtime: warning: unable to wait for child process: Operation timed out
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
s6-svwait: fatal: timed out
Whoops! /run/nordvpn/nordvpnd.sock not found

Invalid Username or password.

[cmd] /bin/sh exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

**Additional context**
Using the container image bubuntux/nordvpn. Updated to the latest release; Running on a Raspberry Pi 3 and Raspberry Pi 4

**Comment by Smiggel** [comment]
Issue remains with the new update:

[services.d] starting services
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
s6-maximumtime: warning: unable to wait for child process: Operation timed out

**Comment by toddnotplaying** [comment]
confirming issue still exists on Raspberry Pi 4, latest PI OS with this latest commit

**Comment by bubuntux** [comment]
please migrate to https://github.com/bubuntux/nordlynx
