### ISSUE TITLE
`GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)

### ISSUE THREAD

**Issue by Smiggel** [bubuntux/nordvpn#319]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**
Updated to the latest image (bubuntux/nordvpn). It seems the latest container image is missing files. Or it's missing for the Raspberry Pi.

**Logs**
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
s6-maximumtime: warning: unable to wait for child process: Operation timed out
/usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)
s6-svwait: fatal: timed out
Whoops! /run/nordvpn/nordvpnd.sock not found

Invalid Username or password.

[cmd] /bin/sh exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

**Additional context**
Using the container image bubuntux/nordvpn. Updated to the latest release; Running on a Raspberry Pi 3 and Raspberry Pi 4

Even with the last update (1 hour old), the issue remains. Build a new container. Same error.

**Comment by mattspruiell** [comment]
I have nothing to add, but I just wanted to chime in that I'm running into the same problem on my Raspberry Pi 4b running raspberry pi os lite. I've tried rebuilding the container as well, and the error persists.

**Comment by bubuntux** [comment]
Is libc installed in the host?

**Comment by bubuntux** [comment]
https://github.com/docker/compose/issues/8048

**Comment by mattspruiell** [comment]
Yes, libc is installed on the host. I should also note that I had been using this image without problem until recently.

**Comment by bubuntux** [comment]
If it's something recent you can always fallback to use a prev versión, but in any case I would recommend you guys migrate to the new Nord lynx container https://github.com/bubuntux/nordlynx/

**Comment by Project-42** [comment]
Hi, just hit the same issue with that library in Raspbian (11 - bullseye)
Is there any possible solution other than use previous image?
Added "image: bubuntux/nordvpn:v3.12.2" and confirmed the issue is not there, but not sure if you plan anything new for next version that can resolve the issue.
Regarding nordlynx image, will need to check, since I still use user/pass for nordvpn and no idea how to use it any other way :) (any hint welcome)

**Comment by Smiggel** [comment]
> Hi, just hit the same issue with that library in Raspbian (11 - bullseye)
> Is there any possible solution other than use previous image?
> Added "image: bubuntux/nordvpn:v3.12.2" and confirmed the issue is not there, but not sure if you plan anything new for next version that can resolve the issue.
> Regarding nordlynx image, will need to check, since I still use user/pass for nordvpn and no idea how to use it any other way :) (any hint welcome)

https://github.com/bubuntux/nordvpn/issues/319#issuecomment-1041086270

**Comment by jhoms** [comment]
I moved to Nordlynx container (I use a Raspberry Pi 4) because the GLIBC_2.28 error but I am unable to make it work. It says connected but the interface looks down.

This is my config:

```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PRIVATE_KEY=*******************************
      - NET_LOCAL=192.168.68.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
```

The log states that it is connected:

```
nordlynx    | [2022-02-26T10:39:31+00:00] Connecting...
nordlynx    | [#] 
nordlynx    | [#] ip link add wg0 type wireguard
nordlynx    | [#] wg setconf wg0 /dev/fd/63
nordlynx    | [#] ip -4 address add 10.5.0.2/32 dev wg0
nordlynx    | [#] ip link set mtu 1420 up dev wg0
nordlynx    | [#] resolvconf -a wg0 -m 0 -x
nordlynx    | [#] wg set wg0 fwmark 51820
nordlynx    | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
nordlynx    | [#] ip -4 rule add not fwmark 51820 table 51820
nordlynx    | [#] ip -4 rule add table main suppress_prefixlength 0
nordlynx    | [#] iptables-restore -n
nordlynx    | iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'
nordlynx    | Error occurred at line: 1
nordlynx    | Try `iptables-restore -h' or 'iptables-restore --help' for more information.
nordlynx    | [#] resolvconf -d wg0 -f
nordlynx    | [#] ip -4 rule delete table 51820
nordlynx    | [#] ip -4 rule delete table main suppress_prefixlength 0
nordlynx    | [#] ip link delete dev wg0
nordlynx    | [2022-02-26T10:39:31+00:00] Connected! \(ᵔᵕᵔ)/

```

But when I check container I got this:

```
~/docker/compose # docker-compose exec nordlynx bash
root@e4386b322b57:/# wg
root@e4386b322b57:/# 

```

Any clues?

**Comment by Smiggel** [comment]
It is connected then.

you can open the terminal and do a “curl ifconfig.me” to check the op of the container.

You can set other containers to use the NordLynx container now.

**Comment by jhoms** [comment]
> It is connected then.
> 
> you can open the terminal and do a “curl ifconfig.me” to check the op of the container.
> 
> You can set other containers to use the NordLynx container now.

curl ifconfig.me does not finishes. I had to cancel.

If I try ping it looks like I cannot reach it

```
root@2d213631c320:/# ping ifconfig.me
PING ifconfig.me (34.117.59.81): 56 data bytes
ping: sendto: Operation not permitted
```

I was able to get my nordvpn connection running again by using nordvpn previous tag (v3.12.2). I will keep it that way for now.

**Comment by kpnjacobstruiksma** [comment]
Version ghcr.io/bubuntux/nordvpn:v3.12.3 also work, ghcr.io/bubuntux/nordvpn:latest does not seem to work

**Comment by alfonsrv** [comment]
Issue still persists. 

And using `nordlynx` seems like a downgrade at best compared to this Docker container, since servers have to be specified statically via `END_POINT=us6285.nordvpn.com:51820` instead of being able to specify a country for dynamic connection. At that point one might as well just use the `dperson/openvpn-client` container again.

**Comment by sincze** [comment]
Still an issue in 2023
Using in docker on Pi4:

`usr/sbin/nordvpnd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/nordvpnd)`

**Comment by sincze** [comment]
Yes fixed it ;-) thank you.
Extracting the key needed some work but all operational now..
