### ISSUE TITLE
System will not start

### ISSUE THREAD

**Issue by henryjb99** [bubuntux/nordvpn#328]
Running RHEL 8.5 on a 64bit VM.
When running the latest nordvpn docker image, I get errors about the IPTables. It seems to be referencing a module that doesn't exist. I can go into the /lib/modules folder of the container and I only see a folder for  "4.15.0-167-generic"

Docker Compose file setup is as follows:
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=XXXXXXXXXXXXXx     # Required
      - "PASS=XXXXXXXXXXXXXXXXXXXXXXx"         # Required
      - CONNECT=P2P
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    ports:
      - 8080:8080
    restart: unless-stopped

Logs:

[cont-init.d] 00-firewall: executing...
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bubuntux: https://github.com/sponsors/bubuntux
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-tun: executing...
[cont-init.d] 10-tun: exited 0.
[cont-init.d] 20-inet: executing...
Enabling connection to secure interface and docker network
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[cont-init.d] 20-inet: exited 3.
[cont-init.d] 20-inet6: executing...
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing...
Enabling connection to network 192.168.1.0/24
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.20.1.el8_5.x86_64
iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[cont-init.d] 30-route: exited 3.
[cont-init.d] 30-route6: executing...
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing...
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
FATAL: iptables is not functional. Ensure your container config adds --cap-add=NET_ADMIN,NET_RAW
--- Due to errors, routing has been disabled ---
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.

**Comment by henryjb99** [comment]
Ok, so I tried a bunch of things, and I don't know what fixed it. For anyone else that runs into this, I did the following:

- Downgrade recently installed upgrades to containerd.io and docker packages.
- Verify I was using the latest versions.
- Deleted existing container images (docker system prune -a).
None of this worked. So I tried the following:

- Performed a fresh install of RHEL 8.5
- Reinstalled Docker, docker compose, and containerd using the instructions from docker for RHEL 8.
Issue was still not fixed.

- Played around with the privileged: true setting. Still not fixed.
- Uninstalled and reinstalled Docker. Still not fixed.
- Rebooted again. Still not fixed.
- Removed the privileged setting and deleted images from /var/lib/docker/containerd. 
Suddenly, everything worked again.

**Comment by stevenlafl** [comment]
I get the same problem, but I am using RHEL 9, podman-docker package with docker-compose because as of podman 3 it is supported. I suppose it is ignoring NET_ADMIN and NET_RAW. Running as root does not solve the issue.

SELinux reports: 

```
SELinux is preventing /usr/sbin/xtables-nft-multi from ioctl access on the directory /sys/fs/cgroup. 
```

You may have turned off SELinux. Can you confirm?

**Comment by henryjb99** [comment]
Disabling SElinux from my RHEL 9 system worked great. Thanks!

**Comment by jmarshall120** [comment]
Hey all,
For me what worked was adding "SYS_MODULE" to the environment variables, and adding "/lib/modules" to the volumes.

Full compose:
`vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
      - SYS_MODULE              # Required to ensure iptables module is loaded, may be able to remove in future
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=xxxxxx
      - CONNECT=p2p
      - NETWORK=192.168.2.0/24  # So it can be accessed within the local network
      - CONNECT=P2P
      - TECHNOLOGY=NordLynx
    ports:
      - 9091:9091 # Transmission
      - 9117:9117 # Jackett
    volumes:
      - /lib/modules:/lib/modules # Required to ensure iptables module is loaded, may be able to remove in future
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only`
