### ISSUE TITLE
 invalid CapAdd: unknown capability: "CAP_NET_ADMIN,NET_RAW".

### ISSUE THREAD

**Issue by Dinibewerbig** [bubuntux/nordvpn#331]
Can somebody help me?

 invalid CapAdd: unknown capability: "CAP_NET_ADMIN,NET_RAW".

Thanks!

**Comment by Hex-99** [comment]
Try NET_ADMIN, not CAP_NET_ADMIN as in --cap-add=NET_ADMIN,NET_RAW

**Comment by Dinibewerbig** [comment]
I actually did that, like so... 

docker run -ti --cap-add=NET_ADMIN,NET_RAW --name vpn \
           -e USER=user@email.com -e PASS='pas$word' \
           -e TECHNOLOGY=NordLynx -d ghcr.io/bubuntux/nordvpn

Still the same Error both on UBUNTU and OSX Docker.

**Comment by joelstitch** [comment]
I was having the same issue running it on my Synology NAS. I got it working with this command:

sudo docker run -ti \
--cap-add=NET_ADMIN \
--cap-add=SYS_MODULE \
--device /dev/net/tun \
--name nordvpn \
-e USER=USERNAME \
-e PASS='PASSWORD' \
-e CONNECT=us \
-e TECHNOLOGY=NordLynx \
-e NETWORK=192.168.69.1/24 \
-e TZ=America/Chicago \
-p 6077:6077 \  #THIS IS THE PORT I NEED OPEN FOR A SPECIFIC APP THATS USING THE NETWORK
-d bubuntux/nordvpn
