### ISSUE TITLE
Seems like a new version of NordVPN is out and not connecting anymore to bubuntux. 

### ISSUE THREAD

**Issue by Dinibewerbig** [bubuntux/nordvpn#333]
A new version of NordVPN is available! Please update the application.

The specified server is not available at the moment or does not support your connection settings.

Unable to connect retrying in 1 seconds.

**Comment by bubuntux** [comment]
use nordlynx container

**Comment by MrCTS** [comment]
More information from mine, granted I am running it as a docker on Unraid.

When I open the docker console and enter "nordvpn status", I get a message of "Whoops! /run/nordvpn/nordvpnd.sock not found"

Not sure if this helps anything outside of using the nordlynx option
