### ISSUE TITLE
Readme does not mention kill switch

### ISSUE THREAD

**Issue by Archmonger** [bubuntux/nordvpn#341]
The readme currently doesn't mention whether or not this container utilizes a kill switch. 

It is important to a lot of people to ensure their IP never gets leaked, even if the VPN server goes down.

Clarifying this detail would be a great addition.

**Comment by Archmonger** [comment]
I would, but unfortunately I don't know whether or not this repo uses a kill switch.

**Comment by bubuntux** [comment]
https://github.com/bubuntux/nordvpn/discussions/235
