### ISSUE TITLE
Nord Meshnet / traffic routing

### ISSUE THREAD

**Issue by browntownington** [bubuntux/nordvpn#346]
**Describe the solution you'd like**
Meshnet is new and has come about since after last update of this container.
https://nordvpn.com/features/meshnet/
https://support.nordvpn.com/General-info/Features/1845333902/What-is-Meshnet.htm

It would be great to have the features of meshnet / traffic routing supported by the container. 
But what would also be super interesting to see is what potential this opens up.
For example, could we we access all our apps via reverse proxy on meshnet? If so we could limit exposure of apps on the public internet! Security game changer?!

**Comment by Fabix1984** [comment]
will there be a correction in order not to be blocked by the meshnet?

**Comment by rfg81** [comment]
My docker stopped working after latest update. I'm getting:
Connecting to Canada #1611 (ca1611.nordvpn.com)

-
  


Whoops! We couldn't connect you to 'Canada'. Please try again. If the problem persists, contact our customer support.

**Comment by Deathspike** [comment]
Same here @rfg81 

Reverting to `v3.12.31` works.

I get the sense that the NordLynx/Wireguard container is the way forward, but that has it's own share of issues.

**Comment by rfg81** [comment]
@Deathspike 

Did you mean v3.12.2? I couldn't find the version you mentioned but v3.12.2 worked for me.

**Comment by Fabix1984** [comment]
> @Deathspike
> 
> Did you mean v3.12.2? I couldn't find the version you mentioned but v3.12.2 worked for me.

3.12.3

**Comment by Deathspike** [comment]
Yep, `3.12.3`. I typo'd there. Apologies 👍

**Comment by BobCelso** [comment]
Yes, 3.12.3 works.

**Comment by sdvaletone** [comment]
is there a way to specify versions when pulling the image?

**Comment by BobCelso** [comment]
@sdvaletone   bubuntux/nordvpn:latest or bubuntux/nordvpn:v3.12.3 

hope that helps .
