### ISSUE TITLE
Nord VPN blocks after 2 hours

### ISSUE THREAD

**Issue by Fabix1984** [bubuntux/nordvpn#349]
2022/07/29 18:35:50 error on making client request: Head "https://downloads.mxo4bkqvdityebzvp.xyz/configs/dns/cybersec.json": dial tcp: lookup downloads.mxo4bkqvdityebzvp.xyz on 103.86.99.100:53: write udp 172.23.0.5:44899->103.86.99.100:53: write: operation not permitted.

I tried to change the DNS, the problem still persists

An idea of ​​the problem

**Comment by FaizVisram** [comment]
I've been having the same issue for a long time. I'm pointing to NL. I can provide logs if needed.

**Comment by luluhoc** [comment]
I'm having the same issue

**Comment by luluhoc** [comment]
Any help
