### ISSUE TITLE
Multiple opened connections and balancing between them

### ISSUE THREAD

**Issue by MacGyver27** [bubuntux/nordvpn#35]
Hi,

I am trying to build a following setup. I have a separate docker container establishing a single nordvpn connection and couple services using this gateway via `network_mode: container:nordvpn`.

My concern is that sometimes a single connection won't utilize my full bandwidth (600mbps), so I am trying to build a container which would open multiple connections (possibly also to different nordvpn servers) and balance between them. From the licensing I am allowed to have 5 simultaneous connections..

Possible solution?
Have an env variable `CONNECTIONS`, which will open between 1-5 connections to the specified server and balance per destination IP for example..

Or if you can point me other direction user can achieve full UPLINK bandwidth.

Appreciate, Michal

**Comment by bubuntux** [comment]
there's always overhead on the vpn connection, the idea of having multiple connections is interesting, but not sure if is possible and really useful, can you provide some sort of example scenario on this approach being used ?

**Comment by bubuntux** [comment]
i'm thinking on abetter solution to speed up the connection would be change the container to use WireGuard instead of openvpn

**Comment by MacGyver27** [comment]
yeah,, I've heard of them but haven't yet done any comparisons.. locally an still on openvpn.. do you have some experience how well it can scale? any drawbacks maybe?

**Comment by MacGyver27** [comment]
so did some reading and the final conclusion is not yet recommended (due to not being audited yet and some privacy concerns because is inherent with WireGuard by design).. anyway they should support nordvpn but currently its in testing stage.. i would recommend to keep openvpn default and allow an option to switch to wireguard :)

**Comment by Groofster** [comment]
I think your performance issue is either a CPU bottleneck or a Nordvpn server limit. I think neither will be resolved by more vpn connections. But if you really wanna go that way, what is prohibiting you from running multiple of these containers in a private docker network and loadbalance on them ?

I've been using this container for quite some time now and I get line speeds (+/- 58 MB/s) with my 500 Mbit internet when using the correct Nordvpn servers (mostly Suisse)

**Comment by MacGyver27** [comment]
> But if you really wanna go that way, what is prohibiting you from running multiple of these containers in a private docker network and loadbalance on them ?

That would be ideal solution! Can you provide me with implementation example? As I mentioned I have a standalone container and am using `network_mode: container:nordvpn` in others as a network adapter.. but reading official docs I am not seeing load-balancing solution..

**Comment by Groofster** [comment]
To be clear, openvpn is NOT using a single tcp connection but creates a tunnel between 2 endpoints on which multiple connections can be opened by any program having the tunnel as gateway address.

Regarding your question on how to implement a multi-openvpn setup:

What kind of application(s) are using the vpn connection ? Can they use a proxy ? Either http of socks ?

**Comment by bubuntux** [comment]
i'm gonna close this issue, if you need more speed please use wireguard implementation (from 3-5x faster), check here https://github.com/bubuntux/nordvpn/issues/47 for more detail
