### ISSUE TITLE
Cannot Connect to NORD Server

### ISSUE THREAD

**Issue by ZaxLofful** [bubuntux/nordvpn#351]
**Describe the bug**
Up until about a week ago, I could use this container just fine with my config. All of a sudden it will not "connect" it is able to login, and I tried the stuff listed in this topic:

https://github.com/bubuntux/nordvpn/issues/199

Output:

Whoops! We couldn't connect you to 'nord server'. Please try again. If the problem persists, contact our customer support.

Unable to connect retrying in 128 seconds.

**Comment by bubuntux** [comment]
probably an issue with nordvpn itself and not this container

**Comment by avaryx** [comment]
@ZaxLofful did you ever get this working? I'm new to this solution and I cannot get a successful connection.
