### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by gpascualg** [bubuntux/nordvpn#36]
This is not a bug but rather a question.

My scenario is similar to the example provided in section 'Local Network access to services connecting to the internet through the VPN.'.

Let's suppose I setup a webserver to be served at 8080, by `-p 8080:8080` on the VPN docker. I can successfully access it through `localhost:8080` and `192.168.1.xxx:8080`. But, in addition to those, I'd need to access it from `<subdomain>.asuscomm.com`, that is, from a DDNS service.

Is that possible? If so, how could it be done?

Thank you

**Comment by bubuntux** [comment]
i imagine it can be done through the NETWORK env variable, but not sure tbh, i haven't done that, this is not an issue referent to the image so i'm gonna close it, please if you find a solution post it here so i can add it into the wiki or readme for future reference, thanks

**Comment by tfonfara** [comment]
Would be interested in a solution as well 😐
