### ISSUE TITLE
Woops can't connect to...

### ISSUE THREAD

**Issue by BelgianMonster** [bubuntux/nordvpn#360]
I tried specifying the server with country code, server, full country, even removing the "connect=" env variable but always get the message oops can't connect to... contact support. I contacted nordvpn support but they can't help with docker version of nordvpn because it's not official

**Comment by guisua** [comment]
Same issue here. Nothing worked except reverting to using `v3.12.2`.
@bubuntux maybe this is related to https://www.reddit.com/r/nordvpn/comments/ud7r9a/connection_failed_on_linux/ on the latest version?

**Comment by Dinul2694** [comment]
I was getting the following with latest version (currently: v3.12.3):

`Unable to connect retrying in 1 seconds.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
The specified server is not available at the moment or does not support your connection settings.`

Only after following what @guisua did and reverting to v3.12.2 was I able to connect again.

**Comment by Friday13th87** [comment]
same here, all versions till 3.12.3 are not working for me - v3.12.3 is working

**Comment by jamiejones1997** [comment]
Having the same problem, does anyone have the fix?

**Comment by Friday13th87** [comment]
> Having the same problem, does anyone have the fix?

Yeah, switching to a openvpn docker image, as this build is never really working and it is always just painfull working with it.

**Comment by msrodrigobr** [comment]
@Friday13th87 could you point to which one u are using? thx

**Comment by SachaTe** [comment]
Same problem, any solution ?

**Comment by desaih** [comment]
Is development dead for this image? It seems like Nordvpn is not anymore working on it. Is there any good alternative?

**Comment by bubuntux** [comment]
there is nothing to develop, this image is just a wrapper of the official client, i move efforts into nordlynx container, and gonna try to consolidate efforts into gluetun container, if this container doesn't work sry but it's up to you to figure it out.

**Comment by guisua** [comment]
for me, migration to gluetun took less than 10 minutes and everything works perfectly now. 100% recommend. @bubuntux thanks anyways for all the years this image did it's thing!

**Comment by bubuntux** [comment]
yup https://github.com/qdm12/gluetun is a great alternative, it lacks wireguard support for nordvpn, i actually have a merge request to add that functionality, i haven't work on it a while but will try to collaborate in that repo, highly recommended project.
