### ISSUE TITLE
DNS leak when nordvpn is disconnected

### ISSUE THREAD

**Issue by BlackDark** [bubuntux/nordvpn#361]
**Describe the bug**
DNS leaks when the nordvpn connection is down.

**To Reproduce using docker CLI**
Run container (either nordvpn alone or even with other container connected.
Stop the nordvpn connection `nordvpn disconnect` and then run script from here: https://github.com/macvk/dnsleaktest
Probably also happens during startup of container while nordvpn connection is not up.
Killswitch of NordVPN handles this case without leaking IP or DNS.

**Expected behavior**
No DNS leak at all even if nordvpn connection is down.

**Comment by przemo** [comment]
Can using the NordVPN dedicated DNSs help ?
