### ISSUE TITLE
Wrong server

### ISSUE THREAD

**Issue by modzilla99** [bubuntux/nordvpn#38]
Similar to the the other bug report, the client doesn't connect to the desired Country/Server!

When I boot up the container with the env COUNTRY=Netherlands this output will show up:

```
nordvpn    | Selecting the best server...
nordvpn    | jq: error: syntax error, unexpected IDENT, expecting ';' or ')' (Unix shell quoting issues?) at <top-level>, line 2:
nordvpn    |                           select( (.name|test("^"Netherlands"$";"i")) or                                                 
nordvpn    | jq: error: syntax error, unexpected IDENT, expecting ';' or ')' (Unix shell quoting issues?) at <top-level>, line 3:
nordvpn    |                                   (.code|test("^"Netherlands"$";"i")) ) |                                                 
nordvpn    | jq: 2 compile errors
nordvpn    | Searching for technology: openvpn_tcp
nordvpn    | Best server : de542.nordvpn.com

```

**Comment by Groofster** [comment]
I had to do a 'doocker rm nordvpn'  and recreate it. Before that the /vpn/ovpn/ directory in the container was missing a lot of new nordvpn server configs, including the one the API was giving me as the best option. Seems like updating the image with only a docker pull is not updating the new configs correctly.

Please give it a try......

**Comment by modzilla99** [comment]
Thx but that's not it, it already happened with a fresh install!

Pascal Peetoom <notifications@github.com> schrieb am Di., 6. Aug. 2019,
14:11:

**Comment by modzilla99** [comment]
My bad  I just had to use netherlands without quotation marks
