### ISSUE TITLE
Probably insignificant but Icon is missing

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [bubuntux/nordvpn#383]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**

Probably insignificant but the icon on my Unraid dash/Docker page is just a grey question mark after this latest update. I went into advanced options (in edit) to find the path to the icon file (https://raw.githubusercontent.com/josopu/unraid-template/main/nordvpn.png) and it came back a 404 error. my "Arrs" seem to be working, but I don't know how to verify.

**To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run ... nrdvpn/client `

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: '3'
services:
  vpn:
    image: nrdvpn/client
  ...
```

**Expected behavior**
A clear and concise description of what you expected to happen and a simple way for someone else to test it.

**Logs**
Focus on errors or warnings messages, if not available post entire logs

**Additional context**
Distribution used, versions, architecture and any other context about the problem here.

**Comment by bubuntux** [comment]
this project does not maintain the unrated app
