### ISSUE TITLE
NordVPN not establishing outside connection

### ISSUE THREAD

**Issue by Hawkins1212** [bubuntux/nordvpn#384]
After doing all of the most recent updates, docker still doesn't generate IP.  Here are my docker logs after executing:

A new version of NordVPN is available! Please update the application.
Logging in via ‘--legacy’, ‘--username’, and ‘--password’ flags is deprecated. Use ‘nordvpn login' or ‘nordvpn login --nordaccount’ to log in via browser. Alternatively, you can use ‘nordvpn login --token’ to log in with a generated token.
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
DNS is already set to '1.0.0.1, 1.1.1.1'.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Threat Protection Lite is already set to 'disabled'.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Technology is already set to 'OPENVPN'.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Subnet 172.17.0.0/16 is whitelisted successfully.
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Subnet 192.168.1.0/24 is whitelisted successfully.
Connecting...
A new version of NordVPN is available! Please update the application.
New feature - Meshnet! Link remote devices in Meshnet to connect to them directly over encrypted private tunnels, and route your traffic through another device. Use the `nordvpn meshnet --help` command to get started. Learn more: https://nordvpn.com/features/meshnet/
Connecting to United States #9893 (us9893.nordvpn.com)
You are connected to United States #9893 (us9893.nordvpn.com)!

Even though it says connected, when I try to run  `curl ifconfig.io` to determine ip address, I get the following response:
`Could not resolve host: ifconfig.io`

**Comment by TheTaylorLee** [comment]
I've been having the same issue. I've found if you run docker exec to manually disconnect and reconnect the vpn it then works. Hopefully this gets fixed soon. The NordVPN package is also pretty out of date I think.

**Comment by Taeleus** [comment]
I was having the same issue. Delugevpn worked with nordvpn settings, but the actual norvpn docker was not gettin an IP. curl ifconfig.io kept failing. Rolled back repo from bubuntux/nordvpn to bubuntux/nordvpn:dev and its now resolving an IP and working properly.

**Comment by DeadShotCS** [comment]
@Taeleus How did you do this? I can't seem to find a ghcr.io/bubuntux/nordvpn:dev. Very possible this is me just overlooking something. Can't get this repo or nordlynx working right now.

**Comment by UniqueName992** [comment]
I was using v3.12.3 successfully but it stopped working the other day, I think login with username and password has been fully deprecated now, and v3.12.3  doesn't support token login (at least I couldn't get it to work).

On Latest I can login with token but still can't ping / curl externally. I also couldn't find the dev tag image.

For now i went to Gluetun with ovpn auth which is working.

**Comment by DeadShotCS** [comment]
@UniqueName992 appreciate the response a ton. I was very lost on what to do, and I got everything working again following the same path you did

**Comment by Taeleus** [comment]
Update. Mine is now doing this regardless of if im using the dev version or latest version. Tried specific other versions as well. None of them connect for some reason.
