### ISSUE TITLE
Update NordVPN

### ISSUE THREAD

**Issue by fivebigmacs** [bubuntux/nordvpn#394]
It seems that the NordVPN docker image is using an old version of NordVPN. Would it make sense to update to the latest version?

**Comment by patrickh217** [comment]
> It seems that the NordVPN docker image is using an old version of NordVPN. Would it make sense to update to the latest version?

Samething on my side

**Comment by ozone38** [comment]
> It seems that the NordVPN docker image is using an old version of NordVPN. Would it make sense to update to the latest version?

Same problem here. 
Log:
`-A new version of NordVPN is available! Please update the application.
--It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.`

**Comment by xucian** [comment]
Same question. It's pretty annoying, and there's no quick param to disable the warning

**Comment by bubuntux** [comment]
feel free to create a pull request

**Comment by pe1uca** [comment]
> feel free to create a pull request

Shouldn't you as the maintainer also check this if it's just a version upgrade?  
I could create a PR but I'd just bump the number, not sure what other side effects it could have which probable you as the maintainer are probably more aware than us just seeing a warning.

**Comment by landcraft** [comment]
any update on this? I'm also getting a message saying I should migrate to NordLynx container - how to do that?
Thanks in advance for your help!
