### ISSUE TITLE
I only want to use Meshnet

### ISSUE THREAD

**Issue by petersenna** [bubuntux/nordvpn#403]
I am trying to use the container for using Meshnet. This is a much simpler network setup as in my case the only thing I need is to be able to connect on the host ssh port from the container.

Is it possible to do that without needing the root permissions for the network?

**Comment by MattsBos** [comment]
I'm actually looking for the same and found this issue searching Google, but it's a completely different use and will require a different approach. So I doubt it's easy to add the functionality to this project just by looking at how it currently works to set up an actual NordVPN, not Meshnet.

Also, I'm afraid Meshnet still requires permissions to create networking interfaces and configs, which means NET_ADMIN permission/capability is required.

**Comment by MattsBos** [comment]
I decided to build a Meshnet docker container for my own use-case. Not sure if it covers your exact use-case, but feel free to create an issue there and I'll see what I can do.
https://github.com/MattsTechInfo/Meshnet

**Comment by petersenna** [comment]
@MattsBos man thank you! I will definitively give this a try as soon as I can!
