### ISSUE TITLE
Openvpn gateway on lan 

### ISSUE THREAD

**Issue by grad76** [bubuntux/nordvpn#41]
Hi, 

I want to use my vpn connection from my docker container with my tv where I can't specify proxy.
How can I do it ?

**Comment by bubuntux** [comment]
probably adding another container inside the same network to do the proxy, issue not really related to this project, if you find a way to do it please consider contribute with documentation

**Comment by Xaero252** [comment]
I almost have this working; and it was working at one point, I've used both pproxy and 3proxy docker containers. I can verify that the Socks5 works for HTTP traffic by setting it in Windows - but using it for downloading Linux ISOs via torrent I am unable to complete an announce or connect to any peers. I feel like it's related to needing another iptables rule - but I haven't been able to figure out what special sauce is missing.

pproxy was the simplest to set up - but there is a decent amount of CPU overhead with many concurrent connections:
`docker run -d --name='pproxy' --net='container:nordvpn' --privileged=true -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" 'mosajjal/pproxy:latest' -l socks5://:1080/ -v`

Obviously on your nordvpn docker you will want to set 1080 to be an open port. 

I see a lot of traffic going out but most traffic not making it's way back in and I'm not sure how to troubleshoot it.
