### ISSUE TITLE
Problem with connection

### ISSUE THREAD

**Issue by nmozol-berta** [bubuntux/nordvpn#416]
Hi, i have a problem with this container-- i have not internet after successfull connection to any server(like any country with standart connection, or any special technology, that nordvpn provided(P2P, double vpn and etc.))

I have tried any other dns like 8.8.4.4-- again there is no connection

version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    network_mode: bridge
    container_name: vpn
    ports:
      - 3000:3000
    cap_add:
      - NET_ADMIN # Required
      - NET_RAW # Required
    environment: # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=<token> # Required
      - TECHNOLOGY=NordLynx
      - DNS=8.8.8.8
      - CYBER_SEC=Disable
      - FIREWALL=Disable
      - OBFUSCATE=Enable
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    user: "root"
    privileged: true
    network_mode: container:vpn
    depends_on:
      - vpn

**Comment by lobf** [comment]
I'm having this same issue, came here looking for help
