### ISSUE TITLE
Environment variables not loaded with compose

### ISSUE THREAD

**Issue by fidodido1202** [bubuntux/nordvpn#42]
New to github so i hope i entered the issue correctly. Struggeling with the getting the code in correctly in the issue my excuses for this. Regarding the code is checked  and don't get errors that something is wrong with it.

**Describe the bug**
When i use docker-compose the environment variables are not set. When i use docker then the environment variables are set correctly. With docker-compose the container gets into an restarting loop and never goes up.
when i use docker-compose logs it says the parameters user and password are missing

When i start the container and do an docker inspect the following variables are missing:
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "UDEV=off",
                "NET_IFACE=eth0"
            ],

With docker i got the following results with docker inspect and the container runs:
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "UDEV=off",
                "NET_IFACE=eth0",
                "NETWORK=192.168.1.0/24",
                "USER=email@email.com",
                "PASS=password"

**To Reproduce**

docker-compose up -d
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=email@email.com
      - PASS='password'
      - COUNTRY=Netherlands
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=Europe/Amsterdam
    ports:
      - 8081:8080
      - 8990:8989
      - 7879:7878
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"

**I also tried to use the envorinment variables with : instead of = but then i have got the same result**

version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      USER: email@email.com
      PASS: password
      COUNTRY: Netherlands
      PROTOCOL: UDP
      CATEGORY: P2P
      NETWORK: 192.168.178.0/24
      #- OPENVPN_OPTS:--pull-filter ignore "ping-restart" --ping-exit 180
      TZ: Europe/Amsterdam
    ports:
      - 8081:8080
      - 8990:8989
      - 7879:7878
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"

**with docker run**
``
docker run -d\
  --name vpn \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  -p 9117:9117 \
  -e NETWORK=192.168.178.0/24 \
  -e USER=email@email.com \
  -e PASS='password' \
  bubuntux/nordvpn
``

I am getting a little bot lost what the issue can be thats the reason i created the issue. Hopefully someone can help me out, did a lot of research on the internet but reall can't solve the issue. Maybe i am overlookin something.

I am running this on Synology with the following version
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2

Docker Version:           18.09.6

**Comment by Groofster** [comment]
I'm using docker-compse as well and have no issue with the following config. Please try and find out what the differences are:

services:
  nordvpn:
    image: "bubuntux/nordvpn"
    container_name: nordvpn
    restart: on-failure:3
    stdin_open: true
    dns: 1.0.0.1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Amsterdam
      - USER=<username>
      - PASS=<password>
      - COUNTRY=Switzerland;
      - NETWORK=<localsubnet>
      - CATEGORY=P2P
      - PROTOCOL=UDP
      - 'OPENVPN_OPTS=--mute-replay-warnings --ping-restart 180 --pull-filter ignore "dhcp-option DNS" --dhcp-option DNS 127.0.0.1'

Maybe try the single quotes around the OPENVPN_OPTS
