### ISSUE TITLE
Prevent connection to the best server

### ISSUE THREAD

**Issue by egonyans** [bubuntux/nordvpn#46]
**Is your feature request related to a problem? Please describe.**
I want to avoid connection the best server in my country if it fails for some reason to connect to the server with the COUNTRY or some other restriction defined. I don't want the container to silently reconnect to the  proxy  in my country and act as if nothing happened when nordvpn changes their api or some other reason

**Describe the solution you'd like**
Add an env. variable like FALLBACK_BEST_SERVER=false which controls the behavior

**Comment by bubuntux** [comment]
please check the new latest version, the CONNECT env variable can be very broad or specific, and it will reconnect in base of whatever you set in there.
