### ISSUE TITLE
Auth issue 

### ISSUE THREAD

**Issue by shiftylilbastrd** [bubuntux/nordvpn#48]
I install via a docker-compose file and have an env file that had to be recreated after an accidental overwrite. Now for some reason I'm getting a auth_failure. I've verified I'm using the correct username/pass. In the env file both are contained in single quotes and I've also tried placing them both in the compose file as well. I've stopped and pruned all containers then redeployed. Also now getting the parse errors below.

Whitelisting api.nordvpn.com...
Selecting the best server...
parse error: Invalid numeric literal at EOF at line 1, column 4
parse error: Invalid numeric literal at EOF at line 1, column 4
Searching for technology: openvpn_tcp
parse error: Invalid numeric literal at EOF at line 1, column 4
Unable to find a server with the specified parameters, using any recommended server
parse error: Invalid numeric literal at EOF at line 1, column 4
Best server : 
Using config file /vpn/ovpn/uk-nl2.nordvpn.com.tcp.ovpn...
Connecting ... 
+ sg vpn -c 'openvpn --config /vpn/ovpn/uk-nl2.nordvpn.com.tcp.ovpn --auth-user-pass /vpn/auth --auth-nocache                                 --script-security 2 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh                                 --pull-filter ignore "ping-restart" --ping-exit 180'
Wed Nov 27 18:50:31 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 26 2018
Wed Nov 27 18:50:31 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Wed Nov 27 18:50:31 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Nov 27 18:50:31 2019 NOTE: --fast-io is disabled since we are not using UDP
Wed Nov 27 18:50:31 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Nov 27 18:50:31 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Nov 27 18:50:31 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]194.36.110.132:443
Wed Nov 27 18:50:31 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 27 18:50:31 2019 Attempting to establish TCP connection with [AF_INET]194.36.110.132:443 [nonblock]
Wed Nov 27 18:50:32 2019 TCP connection established with [AF_INET]194.36.110.132:443
Wed Nov 27 18:50:32 2019 TCP_CLIENT link local: (not bound)
Wed Nov 27 18:50:32 2019 TCP_CLIENT link remote: [AF_INET]194.36.110.132:443
Wed Nov 27 18:50:32 2019 TLS: Initial packet from [AF_INET]194.36.110.132:443, sid=908ce2d1 77b384d1
Wed Nov 27 18:50:33 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Wed Nov 27 18:50:33 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA3
Wed Nov 27 18:50:33 2019 VERIFY KU OK
Wed Nov 27 18:50:33 2019 Validating certificate extended key usage
Wed Nov 27 18:50:33 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Nov 27 18:50:33 2019 VERIFY EKU OK
Wed Nov 27 18:50:33 2019 VERIFY OK: depth=0, CN=uk-nl2.nordvpn.com
Wed Nov 27 18:50:35 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Wed Nov 27 18:50:35 2019 [uk-nl2.nordvpn.com] Peer Connection Initiated with [AF_INET]194.36.110.132:443
Wed Nov 27 18:50:36 2019 SENT CONTROL [uk-nl2.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Wed Nov 27 18:50:37 2019 AUTH: Received control message: AUTH_FAILED
Wed Nov 27 18:50:37 2019 SIGTERM[soft,auth-failure] received, process exiting

**Comment by shiftylilbastrd** [comment]
It appears that the parse errors are in reference to the environment variables inside the compose file.The thing is they don't show up every time I compile the container.

    vpn:
        image: bubuntux/nordvpn:latest
        container_name: nordvpn
        cap_add:
            - net_admin
        devices:
            - /dev/net/tun
        restart: always
        environment:
            - USER=${nord_user}
            - PASS=${nord_pass}
            - COUNTRY=United_States
            - PROTOCOL=UDP
            - CATEGORY=P2P
            - NETWORK=192.168.1.0/24,10.0.75.0/24
            - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
            - TZ=${TZ}
        ports:
            #qbittorrent
            - 6881:6881
            - 6881:6881/udp
            - 8113:8113
            #deluge
            - 8112:8112
            - 58846:58846

**Comment by shiftylilbastrd** [comment]
worked once now getting the parse errors again

**Comment by bubuntux** [comment]
have you checked https://github.com/bubuntux/nordvpn/wiki/Troubleshooting#authentication-issues ?? 
is the content inside /vpn/auth looking good ?

**Comment by LexJackson** [comment]
Similar issue. Contents of /vpn/auth are as they should be. Container is looping and U/P are verified good for Nord. Thoughts?

version: '3.4'
services:

vpn:
     image: bubuntux/nordvpn
     container_name: vpn
     cap_add:
        - net_admin
     tmpfs:
        - /tmp
     restart: unless-stopped
     security_opt:
        - label:disable
     stdin_open: true
     tty: true
     volumes:
        - ../openvpn:/vpn
        - /dev/net:/dev/net:z
     environment:
      - USER=someone@somemail.com
      - PASS='awesomepass'
      - COUNTRY=United_States
      - PROTOCOL=UDP
      - CATEGORY=P2P
      # - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ='America/Kentucky/Louisville'
     network_mode: "default"



I get the following -

vpn       | + set +x
vpn       | Whitelisting api.nordvpn.com...
vpn       | Selecting the best server...
vpn       | Searching for country : United States (228)
vpn       | Searching for group: legacy_p2p
vpn       | Searching for technology: openvpn_udp
vpn       | Best server : us4607.nordvpn.com
vpn       | Using config file /vpn/ovpn/us4607.nordvpn.com.udp.ovpn...
vpn       | Connecting ...
vpn       | + sg vpn -c 'openvpn --config /vpn/ovpn/us4607.nordvpn.com.udp.ovpn --auth-user-pass /vpn/auth --auth-nocache                                 --script-security 2 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh                                 '
vpn       | Fri Dec 27 02:28:12 2019 OpenVPN 2.4.7 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
vpn       | Fri Dec 27 02:28:12 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
vpn       | Fri Dec 27 02:28:12 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit
vpn       | Fri Dec 27 02:28:12 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
vpn       | Fri Dec 27 02:28:12 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
vpn       | Fri Dec 27 02:28:12 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
vpn       | Fri Dec 27 02:28:12 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]192.158.226.27:1194
vpn       | Fri Dec 27 02:28:12 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
vpn       | Fri Dec 27 02:28:12 2019 UDP link local: (not bound)
vpn       | Fri Dec 27 02:28:12 2019 UDP link remote: [AF_INET]192.158.226.27:1194
vpn       | Fri Dec 27 02:28:12 2019 TLS: Initial packet from [AF_INET]192.158.226.27:1194, sid=68965c63 bfcb9d97
vpn       | Fri Dec 27 02:28:12 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
vpn       | Fri Dec 27 02:28:12 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
vpn       | Fri Dec 27 02:28:12 2019 VERIFY KU OK
vpn       | Fri Dec 27 02:28:12 2019 Validating certificate extended key usage
vpn       | Fri Dec 27 02:28:12 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
vpn       | Fri Dec 27 02:28:12 2019 VERIFY EKU OK
vpn       | Fri Dec 27 02:28:12 2019 VERIFY OK: depth=0, CN=us4607.nordvpn.com
vpn       | Fri Dec 27 02:28:12 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
vpn       | Fri Dec 27 02:28:12 2019 [us4607.nordvpn.com] Peer Connection Initiated with [AF_INET]192.158.226.27:1194
vpn       | Fri Dec 27 02:28:13 2019 SENT CONTROL [us4607.nordvpn.com]: 'PUSH_REQUEST' (status=1)
vpn       | Fri Dec 27 02:28:13 2019 AUTH: Received control message: AUTH_FAILED
vpn       | Fri Dec 27 02:28:13 2019 SIGTERM[soft,auth-failure] received, process exiting
vpn       | + set +x

**Comment by LexJackson** [comment]
Update, tried it with TCP also. Same result.

**Comment by LexJackson** [comment]
Update: Container started with the following results in the same auth issues.

docker run -ti --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -e USER=someuser@somemail.com -e PASS='awesomepassword' \
            -e COUNTRY=country -e CATEGORY=category \
            -e PROTOCOL=protocol -d bubuntux/nordvpn

+ set +x
Whitelisting api.nordvpn.com...
Selecting the best server...
Best server : us4607.nordvpn.com
Using config file /vpn/ovpn/us4607.nordvpn.com.udp.ovpn...
Connecting ... 
+ sg vpn -c 'openvpn --config /vpn/ovpn/us4607.nordvpn.com.udp.ovpn --auth-user-pass /vpn/auth --auth-nocache                                 --script-security 2 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh                                 '
Fri Dec 27 03:43:34 2019 OpenVPN 2.4.7 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Fri Dec 27 03:43:34 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Fri Dec 27 03:43:34 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Fri Dec 27 03:43:34 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Dec 27 03:43:34 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Dec 27 03:43:34 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Dec 27 03:43:34 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]192.158.226.27:1194
Fri Dec 27 03:43:34 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Fri Dec 27 03:43:34 2019 UDP link local: (not bound)
Fri Dec 27 03:43:34 2019 UDP link remote: [AF_INET]192.158.226.27:1194
Fri Dec 27 03:43:34 2019 TLS: Initial packet from [AF_INET]192.158.226.27:1194, sid=7e23cea3 2ea9ce56
Fri Dec 27 03:43:34 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Dec 27 03:43:34 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Dec 27 03:43:34 2019 VERIFY KU OK
Fri Dec 27 03:43:34 2019 Validating certificate extended key usage
Fri Dec 27 03:43:34 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Dec 27 03:43:34 2019 VERIFY EKU OK
Fri Dec 27 03:43:34 2019 VERIFY OK: depth=0, CN=us4607.nordvpn.com
Fri Dec 27 03:43:34 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Dec 27 03:43:34 2019 [us4607.nordvpn.com] Peer Connection Initiated with [AF_INET]192.158.226.27:1194
Fri Dec 27 03:43:35 2019 SENT CONTROL [us4607.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Fri Dec 27 03:43:35 2019 AUTH: Received control message: AUTH_FAILED
Fri Dec 27 03:43:35 2019 SIGTERM[soft,auth-failure] received, process exiting
++ exit 1

**Comment by LexJackson** [comment]
I believe I have some insight into the issue. Apparently some of the Nord servers aren't accepting auth from this style of client. (not certain how best to put it) In both cases in the logs posted above, the us4607 server was what the vpn client was attempting to access. This was true for 2 days. So I tried my IOS client and targeted us4607 server. No problems logging in. Then I tried the docker vpn again and it worked on another server. Seems as if we need a way for the bubuntux client to choose another server after x failed attempts.

**Comment by bubuntux** [comment]
hmmm interesting..
i'm thinking on going for a complete diff approach tho, to take advantage of wireguard

**Comment by LexJackson** [comment]
> hmmm interesting..
> i'm thinking on going for a complete diff approach tho, to take advantage of wireguard

Thanks for the reply and letting us know. All good. Have a happy New Years!

**Comment by bubuntux** [comment]
@LexJackson  can you try new implementation ? 
please read thread https://github.com/bubuntux/nordvpn/issues/47

**Comment by LexJackson** [comment]
@bubuntux happy to! You can close this bug I think and ping me on the other thread if you wish -
