### ISSUE TITLE
Slow bandwidth ?

### ISSUE THREAD

**Issue by Sungray** [bubuntux/nordvpn#49]
Hi,

I have 400mbps bandwidth. I have your vpn container running on a Synology, and a qbittorrent container (from linuxserver) running on another container on the same Synology, along with other containers.

Running a speedtest on the synology (I'm using the 'fast' tool from Netflix https://github.com/ddo/fast/releases), I get an acceptable bandwidth, ~370mbps. When I connect the synology to NordVPN, the bandwidth is a bit slower depending on the server, but usually acceptable, always above 250mbps. Running the same speedtest on another container gives me similar results.

But when I run the speedtest on a container using the --net=container:vpn, I get slow results, around 50-100mbps. I tried running a speedtest on the vpn container itself but didn't succeed, the tool doesn't seem compatible with the architecture.

Any idea on how to fix this ?

For the vpn container, I'm using -e CATEGORY=P2P -e PROTOCOL=UDP -e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180' --cap-add=NET_ADMIN --device /dev/net/tun.

Thanks

**Comment by bubuntux** [comment]
it must be related to the server you are connecting to, don't think is an issue with the docker container or image

**Comment by Yooooomi** [comment]
I'm also having this issue. I tried to speedtest-cli inside the container, it shows 23mbps. When I connect to nordvpn via openvpn without docker and speedtest it I get about 130mbps.
