### ISSUE TITLE
openpyn integration

### ISSUE THREAD

**Issue by lavaguy1** [bubuntux/nordvpn#5]
It would be nice to be able to interactively control the selection of a specific nordvpn gateway... openpyn (https://github.com/jotyGill/openpyn-nordvpn)  seems to provide this function... would it be possible (and even make sense?) to integrate this package into your nordvpn project? I'd do it myself, but I'm unfortunately no developer...

Thanks!

**Comment by bubuntux** [comment]
not sure this is need it, can you provide an example of something that can be done with openpyn and not this image ?
