### ISSUE TITLE
How did i route all traffic to the VPN?

### ISSUE THREAD

**Issue by Zororor11** [bubuntux/nordvpn#54]
Hi dear,

i hope your going well? Thank you for your great work!
Im sure that you help me very fast because i have only one simple question.
I got the connection to nordvpn without problems ( i see the sucess login in the logs ).

How did i now make a route to the the working vpn?

I use your docker-compose
And choose the network: 192.168.2.0/24 Ports: 9104:80

Thank you very much!

**Comment by bubuntux** [comment]
this is not an issue, please read the documentation available
