### ISSUE TITLE
How to reconnect "client" containers once vpn dropped?

### ISSUE THREAD

**Issue by H34dl3ss** [bubuntux/nordvpn#56]
I wanted to use the VPN network to route a headless jdownloader container and this docker is simply fantastic! So many thanks for this!
I managed to set it up and get it running as intended. 
The next step is to provide some reconnect functionality to shorten wait times between downloads.
I tried to simply restart the vpn docker but the client docker is not automatically reconnecting once the vpn container drops.
Of course, this is probably not the most elegant solution to reconnect to a different nordVPN server, but I don't know better yet.
So, how do I:
1. have the client docker automatically reconnecting
or
2. issue a reconnect command from the host console to the vpn docker to reconnect the vpn.
Option, and this is actually the feature request:
3. Add an option to the vpn docker, to connect to a random nordVPN location and make sure not to reconnect to the most recent server.

In the end, the plan is to have jdownloader trigger a reconnect action. Maybe via a file that is created somewhere on the host filesystem (download folder). A shell script will constantly scan for this file and issue the above command to reconnect to another VPN server.
Thanks for your support and once again: nice work this container!

**Comment by bubuntux** [comment]
i would encourage to try the new 'bin' tag `bubuntux/nordvpn:bin` soon will replace the current latest tag

if you do not specify a "CONNECT" variable it will automatically reconnect to the optimal server according to NordVPN so you don't have to worry about it.

for point 2, you could do `docker exec container nordvpn c`
or something similar

**Comment by bubuntux** [comment]
review latest env variables as well 
https://github.com/bubuntux/nordvpn/blob/nordvpn-bin/README.md
