### ISSUE TITLE
the latest update doesnt work

### ISSUE THREAD

**Issue by ikomhoog** [bubuntux/nordvpn#58]
I just updated to latest and now it just crashes/shutsdown with just this in the log:
"Stdin/Stdout should be terminal"

I am using Unraid 6.8.2 and had nordvpn running for a few months until i updated just now.

Edit: i tried re-entering all the config values since mine were a bit different than those on the dockerhub, but i still get these errors:
+ [[ -n '' ]]
+ [[ 1 =~ ^[0-9]+$ ]]
+ groupmod -g 1 -o vpn
+ NET_IFACE=eth0
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
+ DOCKER_NET=10.5.0.2/16
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
+ DOCKER_6NET=
+ kill_switch
+ iptables -F OUTPUT
+ ip6tables -F OUTPUT
+ iptables -P OUTPUT DROP
+ ip6tables -P OUTPUT DROP
+ iptables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ [[ -n 10.5.0.2/16 ]]
+ iptables -A OUTPUT -d 10.5.0.2/16 -j ACCEPT
+ [[ -n '' ]]
+ iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ [[ -n 10.5.0.2 ]]
+ for net in ${NETWORK//[;,]/ }
+ return_route 10.5.0.2
++ ip route
++ awk '/default/ {print $3}'
+ local network=10.5.0.2 gw=10.5.0.1
+ ip route add to 10.5.0.2 via 10.5.0.1 dev eth0
+ iptables -A OUTPUT --destination 10.5.0.2 -j ACCEPT
+ [[ -n '' ]]
+ [[ -n '' ]]
+ pkill nordvpnd
+ rm -f /run/nordvpnd.sock
+ sleep 0.5
+ sg vpn -c nordvpnd
+ nordvpn login -u me@hotmail.com -p password
+ setup_nordvpn
+ [[ -n NordLynx ]]
+ nordvpn set technology NordLynx
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n Enable ]]
+ nordvpn set cybersec Enable
+ [[ -n Disable ]]
+ nordvpn set dns Disable
+ [[ -n 10.5.0.2/16 ]]
+ nordvpn whitelist add subnet 10.5.0.2/16
+ [[ -n 10.5.0.2 ]]
+ for net in ${NETWORK//[;,]/ }
+ nordvpn whitelist add subnet 10.5.0.2
+ [[ -n on ]]
+ nordvpn settings
Kill Switch: disabled

CyberSec: enabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
10.5.0.0/16
+ nordvpn connect Switzerland -g p2p
Stdin/Stdout should be terminal
+ exit 1

my config is:
USER:		  me@hotmail.com
PASS:		  MyPassword
CONNECT:	  Switzerland -g p2p
TECHNOLOGY:  NordLynx
CYBER_SEC:	  Enable
DNS:		  Disable
WHITELIST:
NETWORK:	  10.5.0.2
NETWORK6:	
TZ:		          Europe/Amsterdam
GROUPID:
NET_IFACE:
DEBUG:		  on

**Comment by bubuntux** [comment]
You can use prev versión under de openvpn tag, if you provide proper
information we could solve the issue with the latest version.

**Comment by ikomhoog** [comment]
What info do you need?, you haven't seen the edited message from you email

**Comment by ikomhoog** [comment]
this was the edit on the first comment:

Edit: i tried re-entering all the config values since mine were a bit different than those on the dockerhub, but i still get these errors:

[[ -n '' ]]
[[ 1 =~ ^[0-9]+$ ]]
groupmod -g 1 -o vpn
NET_IFACE=eth0
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
DOCKER_NET=10.5.0.2/16
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
DOCKER_6NET=
kill_switch
iptables -F OUTPUT
ip6tables -F OUTPUT
iptables -P OUTPUT DROP
ip6tables -P OUTPUT DROP
iptables -A OUTPUT -o lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT
[[ -n 10.5.0.2/16 ]]
iptables -A OUTPUT -d 10.5.0.2/16 -j ACCEPT
[[ -n '' ]]
iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
[[ -n 10.5.0.2 ]]
for net in ${NETWORK//[;,]/ }
return_route 10.5.0.2
++ ip route
++ awk '/default/ {print $3}'
local network=10.5.0.2 gw=10.5.0.1
ip route add to 10.5.0.2 via 10.5.0.1 dev eth0
iptables -A OUTPUT --destination 10.5.0.2 -j ACCEPT
[[ -n '' ]]
[[ -n '' ]]
pkill nordvpnd
rm -f /run/nordvpnd.sock
sleep 0.5
sg vpn -c nordvpnd
nordvpn login -u me@hotmail.com -p password
setup_nordvpn
[[ -n NordLynx ]]
nordvpn set technology NordLynx
[[ -n '' ]]
[[ -n '' ]]
[[ -n Enable ]]
nordvpn set cybersec Enable
[[ -n Disable ]]
nordvpn set dns Disable
[[ -n 10.5.0.2/16 ]]
nordvpn whitelist add subnet 10.5.0.2/16
[[ -n 10.5.0.2 ]]
for net in ${NETWORK//[;,]/ }
nordvpn whitelist add subnet 10.5.0.2
[[ -n on ]]
nordvpn settings
Kill Switch: disabled
CyberSec: enabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
10.5.0.0/16

nordvpn connect Switzerland -g p2p
Stdin/Stdout should be terminal
exit 1
my config is:
USER: me@hotmail.com
PASS: MyPassword
CONNECT: Switzerland -g p2p
TECHNOLOGY: NordLynx
CYBER_SEC: Enable
DNS: Disable
WHITELIST:
NETWORK: 10.5.0.2
NETWORK6:
TZ: Europe/Amsterdam
GROUPID:
NET_IFACE:
DEBUG: on

**Comment by bubuntux** [comment]
are you suing docker-compose ??

please add `network_mode: bridge`

**Comment by bubuntux** [comment]
is the issue happening using docker cli ??
`docker run ... `

**Comment by ikomhoog** [comment]
This is the command:
docker run -d --name='nordvpn-NordLynx' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'USER'='me@hotmail.com' -e 'PASS'='MyPassword' -e 'CONNECT'='Switzerland -g p2p' -e 'TECHNOLOGY'='NordLynx' -e 'CYBER_SEC'='Enable' -e 'DNS'='Disable' -e 'WHITELIST'='' -e 'NETWORK'='' -e 'NETWORK6'='' -e 'TZ'='Europe/Amsterdam' -e 'GROUPID'='' -e 'NET_IFACE'='' -e 'DEBUG'='on' -p '9117:9117/tcp' -p '58846:58846/tcp' -p '58946:58946/tcp' -p '58946:58946/udp' -p '8112:8112/tcp' -p '7878:7878/tcp' -p '8989:8989/tcp' -p '8686:8686/tcp' -p '3579:3579/tcp' -p '8096:8096/tcp' -p '1900:1900/udp' -p '8920:8920/tcp' --device /dev/net/tun --cap-add=NET_ADMIN 'bubuntux/nordvpn' 

Those ports are for all my other containers that should be using this

**Comment by ikomhoog** [comment]
I also tried copying the docker compose on the docker hub page, i dont know compose so i did it in the variables:
docker run -d --name='nordvpn-test' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'USER'='me@hotmail.com' -e 'PASS'='MyPassword' -e 'CONNECT'='United_States' -e 'TECHNOLOGY'='NordLynx' -e 'DEBUG'='on' -e 'NETWORK'='172.17.0.0/16' --device /dev/net/tun --cap-add=NET_ADMIN 'bubuntux/nordvpn' 

And then it connects, but it never wants to stop, so now i have 6 nordvpn containers because of testing. 
after a restart those were gone.
Also i cannot use the vpn altough it seems like its connected(or at least trying):
+ [[ -n '' ]]
+ [[ '' =~ ^[0-9]+$ ]]
+ NET_IFACE=eth0
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
+ DOCKER_NET=172.17.0.5/16
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
+ DOCKER_6NET=
+ kill_switch
+ iptables -F OUTPUT
+ ip6tables -F OUTPUT
+ iptables -P OUTPUT DROP
+ ip6tables -P OUTPUT DROP
+ iptables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ [[ -n 172.17.0.5/16 ]]
+ iptables -A OUTPUT -d 172.17.0.5/16 -j ACCEPT
+ [[ -n '' ]]
+ iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ [[ -n 172.17.0.0/16 ]]
+ for net in ${NETWORK//[;,]/ }
+ return_route 172.17.0.0/16
++ ip route
++ awk '/default/ {print $3}'
+ local network=172.17.0.0/16 gw=172.17.0.1
+ ip route add to 172.17.0.0/16 via 172.17.0.1 dev eth0
RTNETLINK answers: File exists
+ iptables -A OUTPUT --destination 172.17.0.0/16 -j ACCEPT
+ [[ -n '' ]]
+ [[ -n '' ]]
+ pkill nordvpnd
+ rm -f /run/nordvpnd.sock
+ sleep 0.5
+ sg vpn -c nordvpnd
+ nordvpn login -u Me@hotmail.com -p MyPassword
+ setup_nordvpn
+ [[ -n NordLynx ]]
+ nordvpn set technology NordLynx
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 172.17.0.5/16 ]]
+ nordvpn whitelist add subnet 172.17.0.5/16
+ [[ -n 172.17.0.0/16 ]]
+ for net in ${NETWORK//[;,]/ }
+ nordvpn whitelist add subnet 172.17.0.0/16
+ [[ -n on ]]
+ nordvpn settings
Kill Switch: disabled

CyberSec: disabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
172.17.0.0/16
+ nordvpn connect United_States
INFO: (nordvpn-us3311) 2020/02/11 09:39:09 Interface set up
INFO: (nordvpn-us3311) 2020/02/11 09:39:09 Device started
2020/02/11 09:39:09 address :10.5.0.2/16
2020/02/11 09:39:09 [nordlynx] ip -4 address add 10.5.0.2/16 dev nordvpn-us3311
2020/02/11 09:39:09 [nordlynx] ip link set mtu 1420 up dev nordvpn-us3311
2020/02/11 09:39:10 [nordlynx] ip -4 rule add not fwmark 51820 table 51820
2020/02/11 09:39:10 [nordlynx] ip -4 rule add table main suppress_prefixlength 0
++ pidof nordvpnd
+ tail -f --pid=40 /var/log/nordvpn/daemon.log
2020/02/11 09:39:09 [nordlynx] ip -4 address add 10.5.0.2/16 dev nordvpn-us3311
2020/02/11 09:39:09 [nordlynx] ip link set mtu 1420 up dev nordvpn-us3311
2020/02/11 09:39:10 [nordlynx] ip rule add to 5.181.234.171 lookup main
2020/02/11 09:39:10 [nordlynx] ip -4 route add 0.0.0.0/0 dev nordvpn-us3311 table 51820
2020/02/11 09:39:10 [nordlynx] ip -4 rule add not fwmark 51820 table 51820
2020/02/11 09:39:10 [nordlynx] ip -4 rule add table main suppress_prefixlength 0


this is the error i get when trying to run jackett with the vpn
docker run -d --name='jackett' --net='container:nordvpn' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/Jellyfin/Downloads/Jackett':'/downloads':'rw' -v '/mnt/user/appdata/jackett':'/config':'rw' 'linuxserver/jackett' 
64cbf44f7af8a8da991aa4a863819ca8a57c11a620f3424a0a9bb0fa3cdbefa4
/usr/bin/docker: Error response from daemon: chown /var/lib/docker/containers/68044438af203b212acb0aa8fe1f3c489e2155b501aca88be3aedce7172bdbd1/resolv.conf: operation not permitted.

**Comment by ikomhoog** [comment]
Edit: I used the old docker compose in the previous message, the actual one i got these comments from has the correct name 'nordvpn' and the ports for jackett

**Comment by ikomhoog** [comment]
Also, the openVPN image does still work but i want to help find the problem with nordlynx

**Comment by mindtripper** [comment]
I think NordLynx is broken ATM. ref: https://forum.manjaro.org/t/nordvpn-w-wireguard-nordlynx-stopped-working/122305
Connecting to Sweden does not work at all. But nl701.nordvpn.com works.

**Comment by ikomhoog** [comment]
Ill try the nl701
the bug still remains that i cannot delete a container, is that something you might already be able to work on?
Or is that tied to the nordvpn servers not working and the container waiting on a response that is never coming?

**Comment by lj020326** [comment]
I recently experienced issues with the latest bubuntux/nordvpn container.
When enabling the DEBUG envvar and running the container, I was getting the following error:

`
openvpn              | + nordvpn connect United_States
Please enter your login details.
openvpn              | Stdin/Stdout should be terminal
openvpn              | + exit 1
`

I found that if I switched the container to the following forked version of the container - all works again:

`
  ## ref: https://github.com/bubuntux/nordvpn (no longer works with this traefik docker-compose config)
  openvpn:
#    image: bubuntux/nordvpn:latest
    image: azinchen/nordvpn:latest
`

For any interested, my [docker-compose.yml](https://gist.github.com/lj020326/c24f2f642ea6b3014836f0cae845b9d9).

Note: I use ansible to deploy my media stack, so variables appear enclosed with {{}} which are replaced upon playbook deployment.

**Comment by bubuntux** [comment]
I made this image to fulfill my needs, i'm gonna keep it public and you can use it at your own risk, if something doesn't work for you, sry but is up to you to fix it, unfortunately i don't have time to keep addressing ppls issues, from now on i'm only accepting pull requests.

**Comment by bubuntux** [comment]
this issues should be fix now

**Comment by adgoncal** [comment]
@bubuntux I ran into this exact issue today. I already made sure I have the latest version of this service 
(`image: bubuntux/nordvpn:latest`).

```
vpn_1            | + nordvpn connect ch -g p2p
Please enter your login details.
vpn_1            | Stdin/Stdout should be terminal
vpn_1            | + exit 1
vpn_1            | + cleanup
vpn_1            | + nordvpn disconnect
You are not connected to NordVPN.
vpn_1            | + pkill nordvpnd
-2021/04/06 02:37:14 releasing /etc/resolv.conf
vpn_1            | + trap - SIGTERM SIGINT EXIT
vpn_1            | + exit 0
docker_vpn_1 exited with code 0
```
