### ISSUE TITLE
Server Files are out of date

### ISSUE THREAD

**Issue by lavaguy1** [bubuntux/nordvpn#6]
Hi 

I am getting a lot of fallback errors when starting the connection to Nordvpn:

```
UDP config for server de439.nordvpn.com not found
Filtered pool is empty or configs not found. Select server from recommended list
```

Is there any way to pull the current server config list from Nordvpn, or are the server config lists only updated when the image is updated?

Thanks (also thanks for making this Image in general - it works like a charm, I'd just like to have a little more control over where it's connecting)

**Comment by bubuntux** [comment]
The ovpn files are downloaded when the container is created, 
so you can try recreate the container, also you can mount a directory (/vpn/ovpn) that contain the ovpn files so you can update them manually

**Comment by bubuntux** [comment]
also if you do NOT specify Category, Country and PROTOCOL it will use the server recommended by the nordvpn api

**Comment by lavaguy1** [comment]
Thanks, I'll try that with the recreate. Also, this is happening when I am specifying Protocol, Country AND Category (UDP, Switzerland;Germany, and Category)
