### ISSUE TITLE
using as a proxy

### ISSUE THREAD

**Issue by thijmenboot** [bubuntux/nordvpn#60]
Hello, I am using the default configuration from your docker-compose.yml

I was wondering if it is possible to use this container as a proxy for applications that dont run inside a docker container. For instance I have an application that asks for an IP address and port to use as a proxy. What IP address or port should I use? Do I need to expose another port if I want to use the image like this?

This is kind of new to me so thank you for your patience.

**Comment by bubuntux** [comment]
it's possible, unfortunately outside the scope of this image/project

you would need to add an extra container that will function as proxy and set it up in a way that serve thing outside the container networks. 

Please if you find a tutorial or make it work let me know so we can add it as part of the documentation for future reference.

**Comment by wgorczyca** [comment]
You can use squid container from datadog as http proxy, in docker compose use network_mode: service:<vpn-container-name>
https://hub.docker.com/r/datadog/squid/

If you need custom logic in proxy you can use https://github.com/elazarl/goproxy (that's what I've done).

**Comment by bubuntux** [comment]
@wgorczyca thanks for the contribution !
