### ISSUE TITLE
Container gets unhealthy and unresponsive

### ISSUE THREAD

**Issue by H34dl3ss** [bubuntux/nordvpn#62]
**Describe the bug**
The container gets unhealthy after a random period of time. This time ~20 hours. The time before it was up several days.
Any docker command against the container is not executed in a reasonable timeframe (30 min. wait)
Restarting the docker service to regain control is also not executed successfully.
Fetching a log with "docker logs vpn" in that state is not possible.
Only a reboot of the physical machine will work.
The shutdown sequence will take ~20-30 min. until the reboot finally succeeds.
Although the vpn container is unresponsive, the connected docker is still able to use the vpn connection.

bubuntux/nordvpn:latest          "/usr/bin/entry.sh /…"   2 weeks ago         Up 27 hours (unhealthy)                                                             vpn

**To Reproduce using docker CLI**
docker run -ti --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
-e USER=removed -e PASS=removed \
-e COUNTRY=switzerland -e CATEGORY='Standard VPN servers' \
-e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180' \
-e TECHNOLOGY=OpenVPN \
-e PROTOCOL=TCP -e TZ=DE -d bubuntux/nordvpn:latest

**Logs**
Add DEBUG=on and copy the logs here (make sure to remove you user and password from the logs as well).

**Additional context**
`Linux bananapim2 5.3.7-sunxi #5.98.191018 SMP Fri Oct 18 02:04:52 CEST 2019 armv7l GNU/Linux`

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2
 Built:             Tue Oct  8 01:12:57 2019
 OS/Arch:           linux/arm
 Experimental:      false
```
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2
  Built:            Tue Oct  8 01:06:58 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 7
 Server Version: 19.03.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.7-sunxi
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 997.8MiB
 Name: bananapim2
 ID: ZPLT:GPC4:S4MZ:X7Q4:KCHQ:DQXK:QU7P:YFLL:CI5K:SZZ3:6TZK:2NAE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
top - 15:15:44 up 1 day,  3:39,  1 user,  load average: 1.76, 1.50, 1.42
Tasks: 174 total,   1 running, 103 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.5 us,  0.3 sy,  0.0 ni, 97.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  1021728 total,    60240 free,   482224 used,   479264 buff/cache
KiB Swap:   383136 total,   260768 free,   122368 used.   507644 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9054 root      20   0    4020   1876   1488 S   7.2  0.2  40:17.82 openvpn
 8624 root      20   0  404696  95432   5796 S   2.6  9.3   4:34.13 java
27515 root      20   0    8804   2832   2312 R   1.0  0.3   0:00.38 top
   10 root      20   0       0      0      0 I   0.3  0.0   1:29.65 rcu_sched
 1566 root      20   0  805736  25608   1564 S   0.3  2.5  10:21.94 nordvpnd
 1571 root      20   0  980500  22000   6588 S   0.3  2.2   3:55.63 dockerd
 2136 redis     20   0   34704   3216   1432 S   0.3  0.3   3:14.86 redis-server
 3200 root      20   0  799872    864    228 S   0.3  0.1   0:16.55 containerd-shim
 3524 root      20   0  799872   3436    892 S   0.3  0.3   6:39.81 containerd-shim
 3636 root      20   0  805768  21816   1504 S   0.3  2.1   9:15.89 nordvpnd
20125 root      20   0       0      0      0 I   0.3  0.0   0:05.81 kworker/2:1-eve
    1 root      20   0   26648   3684   2696 S   0.0  0.4   0:46.17 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.16 kthreadd
    3 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_gp
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_par_gp
    8 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq
    9 root      20   0       0      0      0 S   0.0  0.0   0:16.33 ksoftirqd/0
   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 migration/0
   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1
   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.09 migration/1
   15 root      20   0       0      0      0 S   0.0  0.0   0:01.24 ksoftirqd/1
   17 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:0H-kb
   18 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/2
   19 root      rt   0       0      0      0 S   0.0  0.0   0:00.08 migration/2
   20 root      20   0       0      0      0 S   0.0  0.0   0:00.79 ksoftirqd/2
   23 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/3
   24 root      rt   0       0      0      0 S   0.0  0.0   0:00.08 migration/3
   25 root      20   0       0      0      0 S   0.0  0.0   0:01.19 ksoftirqd/3
   27 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/3:0H-kb
   28 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs
   29 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 netns
   34 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kauditd
   35 root      20   0       0      0      0 S   0.0  0.0   0:00.00 oom_reaper
   36 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 writeback
   37 root      20   0       0      0      0 S   0.0  0.0   0:02.44 kcompactd0
   38 root      25   5       0      0      0 S   0.0  0.0   0:00.00 ksmd
  136 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kintegrityd

```

**Comment by H34dl3ss** [comment]
Meanwhile I restarted the machine and grabbed the container logs.
https://pastebin.com/3bKXcJc9
How to enable debugging for this container?

**Comment by icecream42** [comment]
Using NordLynx, got similar happening to me.

I'm not certain if it's related to I/O heavy applications, but I had my downloader unpacking while the vpn container became unhealthy and unresponsive. All connected dockers lost their respective networking.

All other containers keep running normally, server resources aren't exhausted either at that point.

**Comment by bubuntux** [comment]
As a temporal mesure i would recomend use [autoheal](https://hub.docker.com/r/willfarrell/autoheal/ )

**Comment by H34dl3ss** [comment]
> As a temporal mesure i would recomend use autoheal

Autoheal is available as 64bit only - I'm using the armhf version on the banana pi.
Also I'm not sure if auto-restarting the vpn docker is a desirable task, because the connected dockers will loose the connection and not reestablish it automatically. Those containers have to be restarted also.

You added the "help wanted" flag.
Anything we can do to help?

**Comment by LexJackson** [comment]
@bubuntux are you seeing similar behavior? I’m running the latest container with Lynx and I’m seeing this issue to some extent also. I run three different nordlynx containers in a stack unfortunately I have dependent containers attached behind the Nord VPN containers so, just rebooting the VPNs works for fixing the container unhealthy issue but breaks the networking with the dependent containers until they are rebooted also due to due networking dependency. At this point I’m considering a cron script to bounce the stacks daily. Which should solve 95% of my issue.

**Comment by bubuntux** [comment]
i'm not having this behavior, my container has being running for a few weeks now with no issues.. 

the helthcheck command should be restarting the service when unhealthy... so maybe there is room for improvement there

**Comment by H34dl3ss** [comment]
@icecream42 , @LexJackson 
What architecture are you running the container on?
Is it also the 32bit version?
Could it be a resources (memory) issue?
Maybe we have a common point somewhere?

**Comment by LexJackson** [comment]
@H34dl3ss 32 bit arm here. Shouldn't be a memory issue, I'm not showing much or any memory pressure in top.

**Comment by icecream42** [comment]
@H34dl3ss amd64, same for me. Memory and resources are plenty. What I noticed though was a spike on server resources from the unhealthy VPN container. It wasn't too significant as to cause any major issues, but noticeably.

**Comment by bubuntux** [comment]
i reached out to nordvpn support, seems like this issue shouldn't happen when using openvpn protocol, also seems like the connection is just very very slow and not really drops, i think that is the reason why my reconnect mechanism isn't working

**Comment by H34dl3ss** [comment]
As you can see in my options, I'm using the openvpn protocol.
I'm not sure what you mean by "reconnect mechanism".
The container gets unhealthy and unresponsive...

**Comment by bubuntux** [comment]
I made this image to fulfill my needs, i'm gonna keep it public and you can use it at your own risk, if something doesn't work for you, sry but is up to you to fix it, unfortunately i don't have time to keep addressing ppls issues, from now on i'm only accepting pull requests.

**Comment by bubuntux** [comment]
i added a reconnect in the health check that should fix this issue

**Comment by LexJackson** [comment]
THANK YOU! I’d switched back to the OpenVPN version as it’d been more stable. Much appreciated and can’t wait to try it.
