### ISSUE TITLE
vpn connects to different country after restart

### ISSUE THREAD

**Issue by hardik1986** [bubuntux/nordvpn#65]
Initially, I was running below command 1 but I needed vpn to start automatically after reboot so I added restart flag as per docker documentation which is command 2. After 2, whenever vpn gets disconnected and auto restarts, my country IP is changed to USA instead of Canada. Bug? If not, any idea how to fix this?

1.
docker run -ti --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -p 8080:80 -e NETWORK=192.168.1.0/24 -e USER=user@gmail.com -e PASS='pass' -e COUNTRY=Canada -e CATEGORY=P2P -e PROTOCOL=UDP -e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180' -d bubuntux/nordvpn

2.
docker run -dit --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -p 8080:80 -e NETWORK=192.168.1.0/24 -e USER=user@gmail.com -e PASS='pass' -e COUNTRY=Canada -e CATEGORY=P2P -e PROTOCOL=UDP -e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180' --restart unless-stopped bubuntux/nordvpn

**Comment by bubuntux** [comment]
i would recommend to pull the latest version and read the README again, since most env variables have changed

**Comment by bubuntux** [comment]
I made this image to fulfill my needs, i'm gonna keep it public and you can use it at your own risk, if something doesn't work for you, sry but is up to you to fix it, unfortunately i don't have time to keep addressing ppls issues, from now on i'm only accepting pull requests.
