### ISSUE TITLE
User authentication failed, since version 3.6.1-1

### ISSUE THREAD

**Issue by hellomister9876** [bubuntux/nordvpn#67]
I am having an authentication error since verison 3.6.1-1.
When I roll back to version 3.6.0-5 everything works fine.

It might be related to #39 but it worked before so it seems something different.
Is there something I am doing wrong?
Thanks a lot for the container!

My docker compose file:
  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: nordvpn
    restart: always
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USER}
      - PASS=${NORDVPN_PASS}
      - CONNECT=Belgium
      - PROTOCOL=TCP
      - CATEGORY=P2P
      - NETWORK=192.168.178.0/24
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
    ports:
      - 8090:80
      - 9091:9091

Here are the logs:
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
Protocol is successfully set to 'TCP'.
Subnet 172.18.0.0/16 is whitelisted successfully.
Subnet 192.168.178.0/24 is whitelisted successfully.
Connecting to Belgium #129 (be129.nordvpn.com)
/2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 OpenVPN 2.4.8 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 18 2019
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 MANAGEMENT: Connected to management server at /var/run/nordvpn-openvpn.sock
-2020/03/14 12:05:03 [Error] sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 MANAGEMENT: CMD 'state on'
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 MANAGEMENT: CMD 'username "Auth" La51mNxEKJKhJ1ehnrtBwEJM'
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 MANAGEMENT: CMD 'password [...]'
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 NOTE: --fast-io is disabled since we are not using UDP
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]188.95.55.13:443
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 Attempting to establish TCP connection with [AF_INET]188.95.55.13:443 [nonblock]
2020/03/14 12:05:03 [INFO] Sat Mar 14 12:05:03 2020 MANAGEMENT: >STATE:1584187503,TCP_CONNECT,,,,,,
We could not disable IPv6. For more information, please check activity log.
\2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 TCP connection established with [AF_INET]188.95.55.13:443
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 TCP_CLIENT link local: (not bound)
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 TCP_CLIENT link remote: [AF_INET]188.95.55.13:443
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 MANAGEMENT: >STATE:1584187504,WAIT,,,,,,
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 MANAGEMENT: >STATE:1584187504,AUTH,,,,,,
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 TLS: Initial packet from [AF_INET]188.95.55.13:443, sid=d917649e 19145181
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
|2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 VERIFY KU OK
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 Validating certificate extended key usage
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 VERIFY EKU OK
2020/03/14 12:05:04 [INFO] Sat Mar 14 12:05:04 2020 VERIFY OK: depth=0, CN=be129.nordvpn.com
-2020/03/14 12:05:06 [INFO] Sat Mar 14 12:05:06 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1635', remote='link-mtu 1636'
-2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:06 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:06 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:06 2020 [be129.nordvpn.com] Peer Connection Initiated with [AF_INET]188.95.55.13:443
|2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 MANAGEMENT: >STATE:1584187507,GET_CONFIG,,,,,,
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 SENT CONTROL [be129.nordvpn.com]: 'PUSH_REQUEST' (status=1)
/2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 AUTH: Received control message: AUTH_FAILED
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 SIGUSR1[soft,auth-failure] received, process restarting
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 MANAGEMENT: >STATE:1584187507,RECONNECTING,auth-failure,,,,,
2020/03/14 12:05:07 [INFO] Sat Mar 14 12:05:07 2020 Restart pause, 5 second(s)
-2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit
2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 NOTE: --fast-io is disabled since we are not using UDP
2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]188.95.55.13:443
2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 Attempting to establish TCP connection with [AF_INET]188.95.55.13:443 [nonblock]
2020/03/14 12:05:12 [INFO] Sat Mar 14 12:05:12 2020 MANAGEMENT: >STATE:1584187512,TCP_CONNECT,,,,,,
\2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 TCP connection established with [AF_INET]188.95.55.13:443
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 TCP_CLIENT link local: (not bound)
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 TCP_CLIENT link remote: [AF_INET]188.95.55.13:443
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 MANAGEMENT: >STATE:1584187513,WAIT,,,,,,
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 MANAGEMENT: >STATE:1584187513,AUTH,,,,,,
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 TLS: Initial packet from [AF_INET]188.95.55.13:443, sid=92d5d584 8c992180
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 VERIFY KU OK
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 Validating certificate extended key usage
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 VERIFY EKU OK
2020/03/14 12:05:13 [INFO] Sat Mar 14 12:05:13 2020 VERIFY OK: depth=0, CN=be129.nordvpn.com
/2020/03/14 12:05:15 [INFO] Sat Mar 14 12:05:15 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1635', remote='link-mtu 1636'
2020/03/14 12:05:15 [INFO] Sat Mar 14 12:05:15 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2020/03/14 12:05:15 [INFO] Sat Mar 14 12:05:15 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
2020/03/14 12:05:15 [INFO] Sat Mar 14 12:05:15 2020 [be129.nordvpn.com] Peer Connection Initiated with [AF_INET]188.95.55.13:443
\2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 MANAGEMENT: >STATE:1584187517,GET_CONFIG,,,,,,
2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 SENT CONTROL [be129.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 AUTH: Received control message: AUTH_FAILED
2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 SIGUSR1[soft,auth-failure] received, process restarting
2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 MANAGEMENT: >STATE:1584187517,RECONNECTING,auth-failure,,,,,
2020/03/14 12:05:17 [INFO] Sat Mar 14 12:05:17 2020 Restart pause, 5 second(s)
|2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit
2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 NOTE: --fast-io is disabled since we are not using UDP
2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]188.95.55.13:443
2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 Attempting to establish TCP connection with [AF_INET]188.95.55.13:443 [nonblock]
2020/03/14 12:05:22 [INFO] Sat Mar 14 12:05:22 2020 MANAGEMENT: >STATE:1584187522,TCP_CONNECT,,,,,,
/2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 TCP connection established with [AF_INET]188.95.55.13:443
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 TCP_CLIENT link local: (not bound)
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 TCP_CLIENT link remote: [AF_INET]188.95.55.13:443
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 MANAGEMENT: >STATE:1584187523,WAIT,,,,,,
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 MANAGEMENT: >STATE:1584187523,AUTH,,,,,,
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 TLS: Initial packet from [AF_INET]188.95.55.13:443, sid=6d40b5d5 6a22b694
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 VERIFY KU OK
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 Validating certificate extended key usage
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 VERIFY EKU OK
2020/03/14 12:05:23 [INFO] Sat Mar 14 12:05:23 2020 VERIFY OK: depth=0, CN=be129.nordvpn.com
|2020/03/14 12:05:25 [INFO] Sat Mar 14 12:05:25 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1635', remote='link-mtu 1636'
2020/03/14 12:05:25 [INFO] Sat Mar 14 12:05:25 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2020/03/14 12:05:25 [INFO] Sat Mar 14 12:05:25 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
2020/03/14 12:05:25 [INFO] Sat Mar 14 12:05:25 2020 [be129.nordvpn.com] Peer Connection Initiated with [AF_INET]188.95.55.13:443
-2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 MANAGEMENT: >STATE:1584187526,GET_CONFIG,,,,,,
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 SENT CONTROL [be129.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 AUTH: Received control message: AUTH_FAILED
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 SIGUSR1[soft,auth-failure] received, process restarting
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 MANAGEMENT: >STATE:1584187526,RECONNECTING,auth-failure,,,,,
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 Restart pause, 5 second(s)
2020/03/14 12:05:26 [Error] account expired
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 MANAGEMENT: CMD 'pid'
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 MANAGEMENT: CMD 'signal "SIGINT"'
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 SIGINT[hard,init_instance] received, process exiting
2020/03/14 12:05:26 [INFO] Sat Mar 14 12:05:26 2020 MANAGEMENT: >STATE:1584187526,EXITING,init_instance,,,,,
Opening the web browser...
If nothing happens, please visit https://join.nordvpn.com/order/?utm_medium=app&utm_source=linux
Your account has expired. Renew your subscription now to continue enjoying the ultimate privacy and security with NordVPN.

**Comment by kb8080** [comment]
Having the same issue.

**Comment by obbardc** [comment]
duplicate of #66

**Comment by hellomister9876** [comment]
> duplicate of #66

I don't understand why this is a duplicate, I have no firewall issues in my log.

**Comment by bubuntux** [comment]
that seems to be an issue with the nordvpn binaries, i guess they changed something on their end that is not backward compatible.. or something.. 

i just pushed a fix for version 3.7 (latest) can you try there and see if the problem persist, thanks.

**Comment by obbardc** [comment]
with the latest version and NordLynx, I get:

```
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Technology is already set to 'NordLynx'.
Subnet 192.168.1.0/24 is whitelisted successfully.
Please enter your login details.
proxy_nordvpn    | Stdin/Stdout should be terminal
proxy_nordvpn exited with code 1
It's not you, it's us. We're having trouble reaching our servers. If the issue persists, please contact our customer support.
Technology is already set to 'NordLynx'.
Subnet 192.168.1.0/24 is whitelisted successfully.
Please enter your login details.
proxy_nordvpn    | Stdin/Stdout should be terminal
proxy_nordvpn exited with code 1
```

**Comment by hellomister9876** [comment]
Thanks the latest update fixed it for me!
