### ISSUE TITLE
Add a way to restart the network if the VPN goes down

### ISSUE THREAD

**Issue by BakasuraRCE** [bubuntux/nordvpn#7]
Add a way to restart the network if the VPN goes down.

I have this script that could be adapted, makes use of firewall rules so that it does not ping when the network falls and the firewall denies requests to prevent leaks

```bash
#!/bin/bash
SERVERIP=8.8.8.8
while [ "true" ]
do
    ping -c 3 $SERVERIP > /dev/null 2>&1
    if [ $? -ne 0 ]
    then
       # restart the service
       systemctl restart openvpn.service
    fi
    sleep 15
done
```

**Comment by bubuntux** [comment]
i'm gonna try to add that functionality in , meanwhile the current image define a health check, you can use https://hub.docker.com/r/willfarrell/autoheal/ to restart the service when unhealthy.

**Comment by bubuntux** [comment]
latest version will reconnect after a while on his own, please update an re-read the documentation since implementation changed

**Comment by bubuntux** [comment]
nordvpn-bin version has restart capabilities but it has being deprecated due other issues, reopening this so this can be include in main version

**Comment by bubuntux** [comment]
autoheal or https://github.com/bubuntux/nordvpn#reconnect should work to restart the network
