### ISSUE TITLE
Feature request, whitelist ports and protocols

### ISSUE THREAD

**Issue by hackin9-panda** [bubuntux/nordvpn#70]
could you please add a option to whitelist ports and protocols

**Comment by bubuntux** [comment]
i would be happy to accept the merge request with the change..

**Comment by bubuntux** [comment]
I made this image to fulfill my needs, i'm gonna keep it public and you can use it at your own risk, if something doesn't work for you, sry but is up to you to fix it, unfortunately i don't have time to keep addressing ppls issues, from now on i'm only accepting pull requests.
