### ISSUE TITLE
Feature Request, Add support for ARM64/v8

### ISSUE THREAD

**Issue by ali-shaw** [bubuntux/nordvpn#74]
**Is your feature request related to a problem? Please describe.**
I've just moved to a Pi 4 running 64bit Ubuntu 20.04 and would love to add support for this! 

**Describe the solution you'd like**
Support for 64bit ARM - I'm relatively new to Docker so didn't know where to start on a PR may be as simple as another ARCH argument?

**Describe alternatives you've considered**
None

**Comment by ali-shaw** [comment]
I had a go at updating line one of the Dockerfile 

from `ARG ARCH=amd64` to `ARG ARCH=aarch64` then built my own image locally. It appears to have worked but obviously that wouldn't make for a great PR

**Comment by bubuntux** [comment]
Hi @ali-shaw this is something i looked at the other day, 
the branch dev adds support for arm64v8 armv5 and i386 
i haven't merge it cuz i need help testing, can you pull it and try that branch
image name is `bubuntux/nordvpn:dev`

**Comment by ali-shaw** [comment]
hey @bubuntux ! Done - pulled `bubuntux/nordvpn:dev` and it works! Container is up, I curl http://ifconfig.io/ to test the IP and I have another container that connects through it too! Anything I can send you output wise to validate? 

I did notice it sat in `starting` state for a good few minutes but is now `healthy`! Thanks!

**Comment by bubuntux** [comment]
> Anything I can send you output wise to validate?

your word is enough for me, i'll do a little more testing before merging it :bow:
