### ISSUE TITLE
Unable to Log In to NordVPN on Linux

### ISSUE THREAD

**Issue by musicaljoeker** [bubuntux/nordvpn#78]
**Describe the bug**
vpn container fails to start because it appears that it can't sign in on the `nordvpn login -u ** -p **` command. It appears that the nordvpn login process is making API calls to some unrecognized domain.

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    #  network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=myemail@email.com    # Required
      - PASS='mypass'         # Required
      - CONNECT=United_States
      - TECHNOLOGY=OpenVPN
      - NETWORK=192.168.1.0/24 
      - DEBUG=on
    ulimits:
      memlock:
        soft: -1
        hard: -1

  torrent:
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn

  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:                                                                                   
      - vpn:torrent                                                                          
    depends_on:                                                                              
      - torrent                                                                              
    tmpfs:                                                                                   
      - /run                                                                                 
      - /tmp                                                                                 
      - /var/cache/nginx                                                                     
    ports:                                                                                   
      - 80:80                                                                                
      - 443:443                                                                              
    command: -w "http://torrent:8080/;/" 
    
# The torrent service would be available at http://localhost/ 

```

**Expected behavior**
Using this docker-compose file, I'm simply running a `docker-compose up -d`

**Logs**
Add DEBUG=on and copy the logs here (make sure to remove you user and password from the logs as well).

```
+ [[ -n '' ]]
+ [[ '' =~ ^[0-9]+$ ]]
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
+ DOCKER_NET=172.23.0.2/16
+ kill_switch
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
+ local docker6_network=
+ iptables -F
+ iptables -X
+ iptables -P INPUT DROP
+ iptables -P FORWARD DROP
+ iptables -P OUTPUT DROP
+ iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A INPUT -i lo -j ACCEPT
+ iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A FORWARD -i lo -j ACCEPT
+ iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A OUTPUT -o lo -j ACCEPT
+ iptables -A OUTPUT -o tap+ -j ACCEPT
+ iptables -A OUTPUT -o tun+ -j ACCEPT
+ iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
+ [[ -n 172.23.0.2/16 ]]
+ iptables -A INPUT -s 172.23.0.2/16 -j ACCEPT
+ iptables -A FORWARD -d 172.23.0.2/16 -j ACCEPT
+ iptables -A FORWARD -s 172.23.0.2/16 -j ACCEPT
+ iptables -A OUTPUT -d 172.23.0.2/16 -j ACCEPT
+ [[ -n 192.168.1.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ return_route 192.168.1.0/24
++ ip route
++ awk '/default/ {print $3}'
+ local network=192.168.1.0/24 gw=172.23.0.1
+ ip route
+ grep -q 192.168.1.0/24
+ ip route add to 192.168.1.0/24 via 172.23.0.1 dev eth0
+ iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
+ iptables -A FORWARD -d 192.168.1.0/24 -j ACCEPT
+ iptables -A FORWARD -s 192.168.1.0/24 -j ACCEPT
+ iptables -A OUTPUT -d 192.168.1.0/24 -j ACCEPT
+ [[ -n '' ]]
+ ip6tables -F
+ ip6tables -X
+ ip6tables -P INPUT DROP
+ ip6tables -P FORWARD DROP
+ ip6tables -P OUTPUT DROP
+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A INPUT -p icmp -j ACCEPT
+ ip6tables -A INPUT -i lo -j ACCEPT
+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A FORWARD -p icmp -j ACCEPT
+ ip6tables -A FORWARD -i lo -j ACCEPT
+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o tap+ -j ACCEPT
+ ip6tables -A OUTPUT -o tun+ -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
+ ip6tables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT
+ [[ -n '' ]]
+ [[ -n '' ]]
+ pkill nordvpnd
+ rm -f /run/nordvpnd.sock
+ sleep 0.5
+ sg vpn -c nordvpnd
+ nordvpn login -u myemail@email.com -p ''\''mypass'\'''
|2020/05/12 04:21:00 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout
-2020/05/12 04:21:01 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": dial tcp: i/o timeout
/2020/05/12 04:21:25 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": dial tcp: i/o timeout
+ setup_nordvpn
+ [[ -n OpenVPN ]]
+ nordvpn set technology OpenVPN
Technology is already set to 'OpenVPN'.
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 172.23.0.2/16 ]]
+ nordvpn whitelist add subnet 172.23.0.2/16
Subnet 172.23.0.0/16 is whitelisted successfully.
+ [[ -n 192.168.1.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ nordvpn whitelist add subnet 192.168.1.0/24
Subnet 192.168.1.0/24 is whitelisted successfully.
+ [[ -n on ]]
+ nordvpn -version
NordVPN Version 3.7.2
+ nordvpn settings
Technology: OpenVPN
Protocol: UDP
Kill Switch: disabled
CyberSec: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
	172.23.0.0/16
	192.168.1.0/24
+ create_tun_device
+ mkdir -p /dev/net
+ [[ -c /dev/net/tun ]]
+ nordvpn connect United_States
Please enter your login details.
Stdin/Stdout should be terminal
+ exit 1
```

**Additional context**
I'm on amd64 running on Ubuntu 20.04 with the 5.4.0-29-generic linux kernel. I should also note this same behavior occurs when trying to use NordLynx as well.

**Comment by bubuntux** [comment]
looks like the dns is not resolving the domain `zwyr157wwiu6eior.com`

**Comment by musicaljoeker** [comment]
I agree. Does this domain look familiar to you? Is it a NordVPN domain? I ran a `dig` on this domain without many details revealed.

**Comment by bubuntux** [comment]
yeah, is just a domain behind api.nordvpn.com, i have seeing it before, nothing to worry about, i would try:
1. manually add a dns using env variable DNS
2. check that the container host has a working dns
3. modifying the start script to always allow port 53 (instead of only when group matching fails)
`iptables  -A OUTPUT -p udp -m udp --dport 53    -j ACCEPT`

**Comment by klara31** [comment]
I had the same issue, when you omit the single quotes around the password, it works again...
At least: it did with me (-:

**Comment by alpha017** [comment]
I had the same issue too and as @klara31  said, you need to omit the single quotes around the password.

But I had another probleme that was leading to this same debug output, to solve it I set the GROUPID to 0 (I run this container on a VM with sudo, I'm not sure if it has something to do with it).

**Comment by charliwest** [comment]
I have this same issue, not DNS resolving issue, just says my password and/or user name it wrong. Tried all sorts of quotes, no quotes, PGID=0 PUID=0 still says its wrong. If it create the container with a single command then it starts ok, only via composer does it give this error :(

```
Try `iptables -h' or 'iptables --help' for more information.
+ iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
+ iptables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
+ iptables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
+ iptables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
+ iptables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
+ iptables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT
+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
+ [[ -n 172.17.0.4/16 ]]
+ iptables -A INPUT -s 172.17.0.4/16 -j ACCEPT
+ iptables -A FORWARD -d 172.17.0.4/16 -j ACCEPT
+ iptables -A FORWARD -s 172.17.0.4/16 -j ACCEPT
+ iptables -A OUTPUT -d 172.17.0.4/16 -j ACCEPT
+ [[ -n 192.168.1.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ return_route 192.168.1.0/24
++ ip route
++ awk '/default/ {print $3}'
+ local network=192.168.1.0/24 gw=172.17.0.1
+ ip route
+ grep -q 192.168.1.0/24
+ ip route add to 192.168.1.0/24 via 172.17.0.1 dev eth0
+ iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
+ iptables -A FORWARD -d 192.168.1.0/24 -j ACCEPT
+ iptables -A FORWARD -s 192.168.1.0/24 -j ACCEPT
+ iptables -A OUTPUT -d 192.168.1.0/24 -j ACCEPT
+ [[ -n '' ]]
+ ip6tables -F
+ ip6tables -X
+ ip6tables -P INPUT DROP
+ ip6tables -P FORWARD DROP
+ ip6tables -P OUTPUT DROP
+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A INPUT -p icmp -j ACCEPT
+ ip6tables -A INPUT -i lo -j ACCEPT
+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A FORWARD -p icmp -j ACCEPT
+ ip6tables -A FORWARD -i lo -j ACCEPT
+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o tap+ -j ACCEPT
+ ip6tables -A OUTPUT -o tun+ -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
+ ip6tables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT
+ [[ -n '' ]]
+ [[ -n '' ]]
+ pkill nordvpnd
+ rm -f /run/nordvpnd.sock
+ '[' '!' -S /run/nordvpnd.sock ']'
+ sg vpn -c nordvpnd
+ sleep 0.25
+ '[' '!' -S /run/nordvpnd.sock ']'
+ sleep 0.25
+ '[' '!' -S /run/nordvpnd.sock ']'
+ nordvpn login -u my@email -p mypassword
-  -\|/-\|/
Username or password is not correct. Please try again.
+ setup_nordvpn
+ [[ -n NordLynx ]]
+ nordvpn set technology NordLynx
Technology is successfully set to 'NordLynx'.
DNS is set to '103.86.99.100' successfully.
+ [[ -n '' ]]
Subnet 172.17.0.0/16 is whitelisted successfully.
Subnet 192.168.1.0/24 is whitelisted successfully.
NordVPN Version 3.7.2
-  - Technology: NordLynx
Kill Switch: disabled
CyberSec: disabled
Notify: disabled
Auto-connect: disabled
DNS: 103.86.99.100
Whitelisted subnets:
	192.168.1.0/24
	172.17.0.0/16
- Please enter your login details.
Stdin/Stdout should be terminal
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 103.86.99.100 ]]
+ nordvpn set dns 103.86.99.100
+ [[ -n 172.17.0.4/16 ]]
+ nordvpn whitelist add subnet 172.17.0.4/16
+ [[ -n 192.168.1.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ nordvpn whitelist add subnet 192.168.1.0/24
+ [[ -n '' ]]
+ [[ -n on ]]
+ nordvpn -version
+ nordvpn settings
+ create_tun_device
+ mkdir -p /dev/net
+ [[ -c /dev/net/tun ]]
+ nordvpn connect Germany
+ exit 1
```

**Comment by dragonhelios** [comment]
@musicaljoeker had a similar issue on a new debian 10 minimal server install, don't know if it is related. The docker daemon could 1) not resolve DNS queries and 2) would not load properly at boot that affected networking. Following resolved it:

1) Add dns address to docker daemon adn restart docker service. edit/add /etc/docker/daemon.json and add the following: 
{
  "dns": ["8.8.8.8", "8.8.4.4"]
}
Note: Above DNS servers can be changed to your needs

This resolved the DNS issue. I still had to run "sudo systemctl restart docker" after every system boot. Steps 2 and 3 resolved the latter issue.

2) Make sure that the docker service starts after the netfilter-persistent service on boot up. Below snippet from /etc/systemd/system/docker.service:

After=network-online.target firewalld.service netfilter-persistent.service containerd.service

3) Some kernel features have to be enabled for the docker daemon on system startup and need to be added to the default grub commandline:

sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1 /g' /etc/default/grub
update-grub

PS: Various tutorials say there is an incompatibility between docker and nft tables, which is what debian 10 and some other distributions is now using. THey recommend that iptables-legacy needs to be used. I'm currently running iptables-nft in auto mode with no problems so it seems as though this might have been resolved but haven't seen anything to confirm this.

The above steps was was all I needed to get it work for me, cant guarantee it will work for you but the following guide led me to the solution: https://community.hetzner.com/tutorials/debian-10-docker-install-dual%20stack-ipv6nat-firewall

**Comment by musicaljoeker** [comment]
I've tried almost all of these suggestions to no avail. I'm not completely sure how to modify the start script since I'm referencing an image hosted on docker hub. I tried building the container myself but then I ran into other errors.

Things I've tried:

- adjusting quotes. I'm certain I'm passing in the the password correctly (also given the recent documentation change in the readme around the double quotes)
- adding dns rules to the docker daemon as suggested by @dragonhelios. This did not solve my problem.

**Comment by timdonovanuk** [comment]
Having the same issue here on debian. New docker install, just copied the example docker compose file and it doesn't work with the follow error:


```
/2020/05/30 17:20:50 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout

-2020/05/30 17:20:50 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": dial tcp: i/o timeout

|2020/05/30 17:21:25 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": dial tcp: i/o timeout
  
Technology is successfully set to 'NordLynx'.

Subnet 172.20.0.0/16 is whitelisted successfully.
 
Please enter your login details.

Stdin/Stdout should be terminal
```

The container then terminates.

**Comment by modzilla99** [comment]
Same here:

```
Recreating data_vpn_1 ... done
Attaching to data_vpn_1
/2020/06/05 06:26:16 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout
-2020/06/05 06:26:16 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": dial tcp: i/o timeout
-2020/06/05 06:26:21 Get "https://zwyr157wwiu6eior.com/v1/servers/countries": dial tcp: i/o timeout
\2020/06/05 06:26:21 Post "https://boi9osyg1uwtyafn.com/v1/users/tokens": dial tcp: i/o timeout
```
The weird thing is, that I tried running the container without compose as well and that work flawless!
Here are my configs:
```
docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            -e USER=my@email.com -e PASS='Password123' \
            -e CONNECT=Netherlands -e TECHNOLOGY=NordLynx  bubuntux/nordvpn
```
```
  vpn:
    image: bubuntux/nordvpn
    dns:
      - 1.1.1.1                         #Tried without DNS as well
      - 8.8.8.8
    networks: 
      - vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
     - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    environment:
      - DNS=1.1.1.1
      - USER=my@email.com                  
      - PASS='Password123'              #Tried with normal quotes as well
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
```

**Comment by modzilla99** [comment]
using a different entrypoint and setting the nameserver manually solves the issue (for now). Here is what I did. I added a script to override the resolv.conf and added it to the compose file as the entrypoint:

```
echo "Modifing the resolv.conf"

echo "#Created by Me" > /etc/resolv.conf
echo "nameserver 103.86.96.100" >> /etc/resolv.conf

echo "DONE"

bash /usr/bin/start_vpn.sh
```
```
...
entrypoint: ["bash", "/NordVPN/resolver.sh"]
volumes:
      - /data/Docker/NordVPN:/NordVPN:ro
...
```

**Comment by iprajeen** [comment]
I found a temporary workaround for this issue. Its as simple as adding resolved ip address(es) of those domain(s) in `extra_hosts` variable in the `docker-compose.yml` or by passing in `--add-host=w569ut7zbkiqf5b.xyz:104.28.28.105`  in `docker run` command.

docker-compose.yml:
```yml
vpn:
     container_name: vpn
     image: bubuntux/nordvpn:3.7.3
     cap_add:
       - NET_ADMIN
       - SYS_MODULE
     devices:
       - /dev/net/tun
     environment:
       - USER=username
       - PASS=pass
       - CONNECT=United_States
       - TECHNOLOGY=NordLynx
     extra_hosts:
       - "w569ut7zbkiqf5b.xyz:104.28.28.105"
       - "zwyr157wwiu6eior.com:104.17.188.107"
       - "boi9osyg1uwtyafn.com:104.16.229.42"
     restart: unless-stopped
```

**Comment by timmillwood** [comment]
Thanks @iprajeen I came from #91 and this "fixed" the issue.

**Comment by haveard** [comment]
Add "network_mode: bridge" to vpn service.

**Comment by timmillwood** [comment]
Now I get `Get "https://zwyr157wwiu6eior.com/v1/servers?filters[servers.id]=946813": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by timmillwood** [comment]
Adding "network_mode" and removing "extra_hosts" works.

**Comment by jagtesh** [comment]
I ran into the same issue using this docker-compose file:
```
version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    privileged: true
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    ipc: private
    environment:
      - "USER=${NORDVPN_USER}"
      - "PASS=${NORDVPN_PASS}"
      - "CONNECT=${NORDVPN_CONNECT}"
      - TECHNOLOGY=NordLynx
```

I even logged into the container and checked that the env variables are present. Tried running nomadvpn manually, still get the same result as above (keeps trying to connect to different domains and fails).

However, if I use docker cli directly using the command below, it works beautifully:
```
docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            -e USER="${NORDVPN_USER}" -e PASS="${NORDVPN_PASS}" \
            -e CONNECT="${NORDVPN_CONNECT}" -e TECHNOLOGY=NordLynx -d bubuntux/nordvpn
```

I've inspected both containers and the only configuration difference is with some unused fields, that are initialized to `null` in one place and `[]` in the other place.

**Comment by mabushey** [comment]
As of two days ago the new version gives these errors. I deleted `latest`, and ran `docker tag ff963812e7bb bubuntux/nordvpn:latest` which got things running again.

**Comment by AnanthVivekanand** [comment]
For me, the issue was Pihole, which was blocking the DNS queries for some reason. That fixed login.


> I even logged into the container and checked that the env variables are present. Tried running nomadvpn manually, still get the same result as above (keeps trying to connect to different domains and fails).
> 
> However, if I use docker cli directly using the command below, it works beautifully:
> 
> ```
> docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
>             --sysctl net.ipv4.conf.all.rp_filter=2 \
>             -e USER="${NORDVPN_USER}" -e PASS="${NORDVPN_PASS}" \
>             -e CONNECT="${NORDVPN_CONNECT}" -e TECHNOLOGY=NordLynx -d bubuntux/nordvpn
> ```
> 
> I've inspected both containers and the only configuration difference is with some unused fields, that are initialized to `null` in one place and `[]` in the other place.

Can also confirm this, might be related to how docker-compose manages networks?

**Comment by prozb** [comment]
> using a different entrypoint and setting the nameserver manually solves the issue (for now). Here is what I did. I added a script to override the resolv.conf and added it to the compose file as the entrypoint:
> 
> ```
> echo "Modifing the resolv.conf"
> 
> echo "#Created by Me" > /etc/resolv.conf
> echo "nameserver 103.86.96.100" >> /etc/resolv.conf
> 
> echo "DONE"
> 
> bash /usr/bin/start_vpn.sh
> ```
> 
> ```
> ...
> entrypoint: ["bash", "/NordVPN/resolver.sh"]
> volumes:
>       - /data/Docker/NordVPN:/NordVPN:ro
> ...
> ```

Had the same problem with bad credentials. I spent literally two days fixing this problem and today I came across your solution. Finally fixed, thank you! The problem was nameserver.

@bubuntux Would you like to take this into the documentation? The problem with docker-compose and bad credentials is very common in issues as I saw.

**Comment by bubuntux** [comment]
@prozb  i'm happy to accept Pull requests

**Comment by ChuckNorrison** [comment]
Same issue here on a single device (Ubuntu 20.04 Desktop). The concept of nordvpn with weird domain names and this DNS solution is hard to verify as customer... so it is with the nordvpn login and the browser url with a hidden shell prompt in it. Nordvpn was not able to help me solve my issue after 3 attempts. Invested dozens of hours into this, but seems its kind of internetprovider censorship or nordvpn server side misconfiguration. 

Maybe this will help: The issue happens to me after 2.5 Years of usage without any issues so far, but since some weeks it mostly wont work anymore. Sometimes i can connect, but mostly one of the described errors can be found in the nordvpnd journal.
