### ISSUE TITLE
container get stuck in "health: starting". After time out it's in "unhealthy" state

### ISSUE THREAD

**Issue by almarax** [bubuntux/nordvpn#8]
Where are the logs I can check to see what's the problem.
It's happening both under Docker for windows:
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

And synology:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Thu Oct 11 21:32:14 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Thu Oct 11 21:32:14 2018
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by bubuntux** [comment]
Can you try again? i update the container to use the latest official nordvpn binaries, please read the documentation again since parameters have changed
