### ISSUE TITLE
Restart automatically

### ISSUE THREAD

**Issue by felinto-dev** [bubuntux/nordvpn#85]
Hello!

I am using your container to connect a Telegram BOT API.

The Telegram API unfortunately blocks traffic after a certain period of time and its image has proven to be very useful as it is very easy to restart the container and the VPN automatically connects to a new server.

It would be a good idea to specify a URL to monitor as environment variables and if that URL is inaccessible, connect to a new server.

**Comment by frdmn** [comment]
You should be able to use the Docker healthcheck for that. If the healthcheck enters a "unhealthy" state, Docker will restart the container (which will probably connect you to a new VPN node): https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by bubuntux** [comment]
in theory that should be the current behavior 

```
HEALTHCHECK --interval=5m --timeout=20s --start-period=1m \
  CMD if test $( curl -m 10 -s https://api.nordvpn.com/vpn/check/full | jq -r '.["status"]' ) = "Protected" ; then exit 0; else nordvpn connect ${CONNECT} ; exit $?; fi
```

when it disconnects it will try to reconnect in base of the CONNECT variable, if it's empty or generic enough (like a country) it should connect to an active server (which may be a diff one).

**Comment by felinto-dev** [comment]
I haven't had time to test this yet but I believe the problem has been resolved. Could you close the issue?
