### ISSUE TITLE
NORDVPN + eth0 local access

### ISSUE THREAD

**Issue by user9823749** [bubuntux/nordvpn#88]
Hi,
I have bridge created by docker on rpi4 and have all containers inside and i use brctl to add inside that network my eth0 port to have direct access to containers. Now how i can connect everything throught nordvpn? I was trying to -net and my network name but nordvpn wont start got errors dial tcp: i/o timeout , only start like new network. I know how to make containers to use that new network but im gonna loose them from my network and eth0 dont have access to nordvpn.

If nordvnp container act like gateway should have ip so i can put on my devices from eth0 side as gateway but i cant because nordvpn container have own network so i need to bridge them?

**Comment by bubuntux** [comment]
![](https://i.kym-cdn.com/photos/images/original/001/240/075/90f.png)
