### ISSUE TITLE
Make healthcheck to reconnect less often

### ISSUE THREAD

**Issue by H34dl3ss** [bubuntux/nordvpn#90]
**Is your feature request related to a problem? Please describe.**
I'm running a downloader client as a container that hooks up on this NordVPN docker.
The frequent reconnects make the downloader useless as it will never finish a job before the reconnect happens. After a reconnect the download has to start from new.

I suppose this is related to the healthcheck???

**Describe the solution you'd like**
I would like to tweak the healthcheck options to have a lower reconnect frequency.

**Describe alternatives you've considered**
I tried the OpenVPN as well as the NordLynx.

**Additional context**
I'm not using the compose to start the docker.
I would need some advice how to add the options on commandline.

I'm starting the container with this option:
docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
-e USER=xxx -e PASS='xxx' \
-e COUNTRY=switzerland -e CATEGORY='Standard VPN servers' \
-e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180' \
-e TECHNOLOGY=NordLynx \
-e PROTOCOL=TCP -e TZ=DE -d bubuntux/nordvpn:latest

**Comment by frdmn** [comment]
That is weird, since the container shouldn't restart in first place if the connection is still successfully established to the VPN server. If your container is restarting all the time (due to the healthcheck), maybe there is some kind of networking problem (or something similiar) going on? 🤔

**Comment by H34dl3ss** [comment]
The container is not restarting but the VPN connection is built up to another exit node.

In the meanwhile I tried to revert to the former docker pull that I was using which didn't reconnect but would go unhealthy instead.
For some reasons the old version is also reconnecting now.
I don't understand what's happening.

**Comment by H34dl3ss** [comment]
I tried another setup using OpenVPN instead of NordLynx - this is what my setup was before.
It still reconnects autonomously. I wrote a short script to capture the IP changes.

2020.06.12-23:50:31 Current server: lu71.nordvpn.com Your new IP: 92.223.89.192
2020.06.13-00:10:42 Current server: nl384.nordvpn.com Your new IP: 185.212.171.200
2020.06.13-01:26:04 Current server: ch253.nordvpn.com Your new IP: 195.206.105.99
2020.06.13-03:26:29 Current server: de523.nordvpn.com Your new IP: 82.102.16.219
2020.06.13-08:41:11 Current server: de710.nordvpn.com Your new IP: 5.180.62.45

**Comment by bubuntux** [comment]
you can always override the health check a long with the timeout parameters and so on.. 
take a look at https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by H34dl3ss** [comment]
Thanks for your reply!
Comes just in time as I need the downloader just now.
The current settings are (found in one of your posts in the solved issues):
HEALTHCHECK --interval=5m --timeout=20s --start-period=1m \

I'm not sure how to use that information.
Is this assumption correct (last line)?
docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn
-e USER=xxx -e PASS='xxx'
-e COUNTRY=switzerland -e CATEGORY='Standard VPN servers'
-e OPENVPN_OPTS='--pull-filter ignore "ping-restart" --ping-exit 180'
-e TECHNOLOGY=NordLynx
-e PROTOCOL=TCP -e TZ=DE -d bubuntux/nordvpn:latest
**-e HEALTHCHECK --interval=5m --timeout=60s --start-period=1m \**

Just for information, the amount of reconnects.
Empty lines means the container is not answering to the docker exec comand.
```
2020.06.19-07:24:38 Current server: ch266.nordvpn.com Your new IP: 89.187.165.141
2020.06.19-14:20:29 Current server: de827.nordvpn.com Your new IP: 5.180.62.153
2020.06.19-15:31:36 Current server: de870.nordvpn.com Your new IP: 185.220.70.195
2020.06.19-18:58:57 Current server: de789.nordvpn.com Your new IP: 5.180.62.135
2020.06.19-20:05:05 Current server: de708.nordvpn.com Your new IP: 5.180.62.39
2020.06.19-21:11:12 Current server: de856.nordvpn.com Your new IP: 185.59.220.229
2020.06.19-23:28:36 Current server: de768.nordvpn.com Your new IP: 37.120.197.44
2020.06.20-02:51:20 Current server: de874.nordvpn.com Your new IP: 185.220.70.215
2020.06.20-05:08:44 Current server: de682.nordvpn.com Your new IP: 45.141.152.35
2020.06.20-06:08:54 Current server: de799.nordvpn.com Your new IP: 195.181.170.204
2020.06.20-07:15:04 Current server: de684.nordvpn.com Your new IP: 45.141.152.51
2020.06.20-08:16:14 Current server: de714.nordvpn.com Your new IP: 5.180.62.57
2020.06.20-10:28:35 Current server: de825.nordvpn.com Your new IP: 5.180.62.147
2020.06.20-12:39:59 Current server: de720.nordvpn.com Your new IP: 5.180.62.75
2020.06.20-14:57:22 Current server: de772.nordvpn.com Your new IP: 37.120.197.56
2020.06.20-16:03:33 Current server: de741.nordvpn.com Your new IP: 5.180.62.93
2020.06.20-17:09:45 Current server: de742.nordvpn.com Your new IP: 5.180.62.96
2020.06.20-19:26:06 Current server: de725.nordvpn.com Your new IP: 5.180.62.90
2020.06.20-20:32:20 Current server: de860.nordvpn.com Your new IP: 185.216.33.18
2020.06.21-01:47:41
2020.06.21-01:50:41 Current server: ch216.nordvpn.com Your new IP: 185.156.175.188
2020.06.22-01:09:59 Current server: de846.nordvpn.com Your new IP: 193.176.87.59
2020.06.22-04:48:37 Current server: de705.nordvpn.com Your new IP: 5.180.62.30
2020.06.22-05:49:44 Current server: de799.nordvpn.com Your new IP: 195.181.170.204
2020.06.22-06:59:52 Current server: de767.nordvpn.com Your new IP: 37.120.197.41
2020.06.22-08:00:58 Current server: de743.nordvpn.com Your new IP: 5.180.62.99
2020.06.22-09:07:05 Current server: de819.nordvpn.com Your new IP: 141.98.102.171
2020.06.22-10:28:14
2020.06.23-00:44:30 Current server: ch264.nordvpn.com Your new IP: 89.187.165.151
2020.06.23-03:16:03 Current server: de711.nordvpn.com Your new IP: 5.180.62.48
2020.06.23-04:22:18 Current server: de821.nordvpn.com Your new IP: 141.98.102.251
2020.06.23-06:39:38 Current server: de677.nordvpn.com Your new IP: 85.208.72.234
2020.06.23-07:44:47 Current server: de847.nordvpn.com Your new IP: 192.145.125.35
2020.06.23-08:50:58 Current server: de817.nordvpn.com Your new IP: 141.98.102.155
2020.06.23-09:57:07 Current server: de765.nordvpn.com Your new IP: 37.120.197.35
2020.06.23-10:58:16 Current server: de820.nordvpn.com Your new IP: 141.98.102.131
2020.06.23-11:00:17 Current server: ch253.nordvpn.com Your new IP: 195.206.105.99
2020.06.23-11:02:17 Current server: fi124.nordvpn.com Your new IP: 196.196.203.51
2020.06.23-11:54:27 Current server: de748.nordvpn.com Your new IP: 5.180.62.114
2020.06.23-13:00:37 Current server: de735.nordvpn.com Your new IP: 46.165.221.39
2020.06.23-17:44:24 Current server: de711.nordvpn.com Your new IP: 5.180.62.48
2020.06.23-18:50:34 Current server: de700.nordvpn.com Your new IP: 5.180.62.15
2020.06.23-19:56:45 Current server: de862.nordvpn.com Your new IP: 185.145.38.224
2020.06.23-20:25:49 Current server: fi130.nordvpn.com Your new IP: 196.196.203.99
2020.06.23-23:14:21 Current server: de818.nordvpn.com Your new IP: 141.98.102.163
2020.06.24-00:08:27
2020.06.24-07:21:07 Current server: ch235.nordvpn.com Your new IP: 217.138.203.181
2020.06.24-08:01:14 Current server: de820.nordvpn.com Your new IP: 141.98.102.131
2020.06.24-09:07:22 Current server: de875.nordvpn.com Your new IP: 185.220.70.225
2020.06.24-09:16:25 Current server: de768.nordvpn.com Your new IP: 37.120.197.44
2020.06.24-09:18:26 Current server: pl144.nordvpn.com Your new IP: 5.253.206.147 
```

**Comment by frdmn** [comment]
No, the linked docs were for the Dockerfile directives. You can use the following command switches if you want to stick to CLI:

```
  --health-cmd            Command to run to check health
  --health-interval       Time between running the check
  --health-retries        Consecutive failures needed to report unhealthy
  --health-timeout        Maximum time to allow one check to run
  --health-start-period   Start period for the container to initialize before starting health-retries countdown
  --no-healthcheck        Disable any container-specified HEALTHCHECK
```

(via https://docs.docker.com/engine/reference/run/#healthcheck)

If you use docker-compose instead, you can use a YAML format like this: 

```
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
```

(via https://docs.docker.com/compose/compose-file/#healthcheck)

**Comment by rundx** [comment]
I think the health check is not your problem here, you're being disconnected every hour or so 
the health check only reconnects you to the vpn if it finds out you're not connected

make sure you can reach https://api.nordvpn.com/vpn/check/full from the container

**Comment by H34dl3ss** [comment]
Thanks @frdmn !
Is there, by chance, also a docker exec command that I could use to modify a running docker?

@rundx 
It almost looks like, but there are different intervals also where the container is running significantly longer.
Of course I cannot exclude that the root cause is the VPN provider itself.
But I can say that earlier I was able to download big files that took about 5 hours without issue. Now it's almost impossible to get one of those files.

**Comment by H34dl3ss** [comment]
Obviously a timout setting of 60s is also not enough. I still get reconnected.
Therefore I disabled the healthcheck. The container will go unhealthy but that happened with the healthcheck enabled too.
At least, the downloads are finishing now.

**Comment by rundx** [comment]
It seems like the API check at https://api.nordvpn.com/vpn/check/full is not reliable 

it gives false "Unprotected" responses every now and then

    {"ip":"141.98.102.164","isp":"M247 Ltd","status":"Unprotected","country":"Germany","code":"DE"}

**Comment by flakyton** [comment]
There are 2 things I had to do to solve the issue:

1. Use Cloudfare DNS home page HEAD request as a health check
2. disconnect before reconnecting

```
if test $( curl -m 10 -SsfI -o /dev/null -w '%{http_code}' 'https://1.1.1.1' ) = "200"; then exit 0; else nordvpn disconnect && nordvpn connect ${CONNECT}; exit $?; fi
```

**Comment by rundx** [comment]
Considering the "kill-switch" I'd say that's a cleaner option cause there is no point in making sure we're connected specifically to NordVPN servers if the kill-switch is already preventing traffic over non-vpn connection

**Comment by bubuntux** [comment]
i just removed the health check all together
