### ISSUE TITLE
Wait for Nordvpn container to be up - then start myself

### ISSUE THREAD

**Issue by MacGyver27** [bubuntux/nordvpn#93]
Hi,

E.g. when I reboot the server - containers using nordvpn as a network gets stuck.. when I restart them they will work again. I think this is because they get up before nordvpn container..

Is there a way to overcome this problem? Something like (for containers):
```yml
    depends_on:
      - container:nordvpn
```
However this is not supported.. Maybe some healthcheck to check nordvpn is `up` and then start up myself..

Thanks, Michal

**Comment by bubuntux** [comment]
This is an issue on docker, since the other containers attach to the nordvpn container's network, once you restart the nordvpn container the network is lost for the dependent containers.

one work around could be create a dummy container and then vpn and other containers attach to the network on dummy container, so you should be able to restart nordvpn and depends independently as long as the dummy containers remains up.

**Comment by Groofster** [comment]
This used to work but a change in docker-compose killed that option. It actually used to recreate all dependancies when doing a docker-compose up -d. Too bad that has gone.

The following in all the other service configurations does (in my case) make sure nordvpn is started first at host boot:

depends_on:
  - nordvpn

**Comment by Ansem93** [comment]
I solved running this script throught cronjob every 15 minutes. I don't reccomend to run it more often since nordvpn container often takes up to 5 minutes to return healthy:
`#!/usr/bin/env bash
if [ $(docker ps --filter "name=vpn" | grep -c "(healthy)") -eq 0 ]
        then
                echo "vpn is unhealthy :< "
                c=10
                while [ $(docker ps --filter "name=vpn" | grep -c "(healthy)") -eq 0 ]
                do
                        if [[ ($(docker ps --filter "name=vpn" | grep -c "starting") -eq 0) || ($c -eq 10 )]]
                        then
                                echo "reboot vpn"
                                docker restart vpn
                        fi
                        sleep 30
                        c=$(( $c - 1 ))
                        if [ $c -eq 0 ]
                                then
                                        c=10
                        fi
                        echo "Countdown al prossimo riavvio - $c"
                done
                echo "vpn is healthy now :D"
                docker restart xxx
                ...
                docker restart xzx
        else
                echo "vpn is healthy"
fi`
