### ISSUE TITLE
NordLynx not working - Whoops! We couldn't connect you to 'Switzerland'. Please try again. If the problem persists, contact our customer support.

### ISSUE THREAD

**Issue by quorn23** [bubuntux/nordvpn#97]
**Describe the bug**
NordLynx connections don't work. OpenVPN works fine. Tested on an Ubuntu 20 server and locally. Logs are from the server.

Between:
```
INFO: (nordlynx) 2020/07/26 03:22:55 Device started
```
and
```
\INFO: (nordlynx) 2020/07/26 03:23:25 Device closing
```
it just sits there with "starting" status. 

Tried with different countries and looked at the troubleshoot steps and issues. Sadly can't get it to work.

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: "3.4"
services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE             # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
    - USER=${VPN_USER}   # Required
    - PASS=${VPN_PASS}       # Required
    - CONNECT=Switzerland
    - TECHNOLOGY=NordLynx
    - NETWORK=192.168.1.0/24
    - DNS=${VPN_DNS}
    - TZ=${TZ}
    - GROUPID=0
    - DEBUG=ON
    ports:        # Required Ports for the app you use via VPN
    - 5800:5800 #Access JD
    - 3129:3129 #myJD access
  ...
```

VPN_DNS variable is 1.1.1.1,8.8.8.8
Timezone is my local timezone.

**Expected behavior**
Working connection, the same way as it works if i change/adapt to OpenVPN settings.

**Logs**
Add DEBUG=on and copy the logs here (make sure to remove you user and password from the logs as well).

+ [[ -n '' ]]

+ [[ 0 =~ ^[0-9]+$ ]]

+ groupmod -g 0 -o vpn

++ ip -o addr show dev eth0

++ awk '$3 == "inet" {print $4}'

+ DOCKER_NET=172.17.0.4/16

+ kill_switch

++ awk '$3 == "inet6" {print $4; exit}'

++ ip -o addr show dev eth0

+ local docker6_network=

+ iptables -F

+ iptables -X

+ iptables -P INPUT DROP

+ iptables -P FORWARD DROP

+ iptables -P OUTPUT DROP

+ iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A INPUT -i lo -j ACCEPT

+ iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A FORWARD -i lo -j ACCEPT

+ iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ iptables -A OUTPUT -o lo -j ACCEPT

+ iptables -A OUTPUT -o tap+ -j ACCEPT

+ iptables -A OUTPUT -o tun+ -j ACCEPT

+ iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT

+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE

+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE

+ [[ -n 172.17.0.4/16 ]]

+ iptables -A INPUT -s 172.17.0.4/16 -j ACCEPT

+ iptables -A FORWARD -d 172.17.0.4/16 -j ACCEPT

+ iptables -A FORWARD -s 172.17.0.4/16 -j ACCEPT

+ iptables -A OUTPUT -d 172.17.0.4/16 -j ACCEPT

+ [[ -n 192.168.1.0/24 ]]

+ for net in ${NETWORK//[;,]/ }

+ return_route 192.168.1.0/24

++ ip route

++ awk '/default/ {print $3}'

+ local network=192.168.1.0/24 gw=172.17.0.1

+ ip route

+ grep -q 192.168.1.0/24

+ ip route add to 192.168.1.0/24 via 172.17.0.1 dev eth0

+ iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT

+ iptables -A FORWARD -d 192.168.1.0/24 -j ACCEPT

+ iptables -A FORWARD -s 192.168.1.0/24 -j ACCEPT

+ iptables -A OUTPUT -d 192.168.1.0/24 -j ACCEPT

+ [[ -n '' ]]

+ ip6tables -F

+ ip6tables -X

+ ip6tables -P INPUT DROP

+ ip6tables -P FORWARD DROP

+ ip6tables -P OUTPUT DROP

+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A INPUT -p icmp -j ACCEPT

+ ip6tables -A INPUT -i lo -j ACCEPT

+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A FORWARD -p icmp -j ACCEPT

+ ip6tables -A FORWARD -i lo -j ACCEPT

+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

+ ip6tables -A OUTPUT -o lo -j ACCEPT

+ ip6tables -A OUTPUT -o tap+ -j ACCEPT

+ ip6tables -A OUTPUT -o tun+ -j ACCEPT

+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

+ ip6tables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

+ ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

+ ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

+ ip6tables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT

+ [[ -n '' ]]

+ [[ -n '' ]]

+ pkill nordvpnd

+ rm -f /run/nordvpnd.sock

+ '[' '!' -S /run/nordvpnd.sock ']'


+ sleep 0.25

+ sg vpn -c nordvpnd

+ '[' '!' -S /run/nordvpnd.sock ']'

+ nordvpn login -u xxxxxxxxxx -p xxxxxxxxxx

-
  

-
\
|
/
-
\
|
/
-
\
|
/
  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

+ setup_nordvpn

+ [[ -n NordLynx ]]

+ nordvpn set technology NordLynx

Technology is successfully set to 'NordLynx'.

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n 1.1.1.1,8.8.8.8 ]]

+ nordvpn set dns 1.1.1.1 8.8.8.8

DNS is set to '1.1.1.1, 8.8.8.8' successfully.

+ [[ -n 172.17.0.4/16 ]]

+ nordvpn whitelist add subnet 172.17.0.4/16

Subnet 172.17.0.0/16 is whitelisted successfully.

+ [[ -n 192.168.1.0/24 ]]

+ for net in ${NETWORK//[;,]/ }

+ nordvpn whitelist add subnet 192.168.1.0/24

Subnet 192.168.1.0/24 is whitelisted successfully.

+ [[ -n '' ]]

+ [[ -n ON ]]

+ nordvpn -version

NordVPN Version 3.7.4

+ nordvpn settings

-
  

-
  
Technology: NordLynx

Kill Switch: disabled

CyberSec: disabled

Notify: disabled

Auto-connect: disabled

DNS: 1.1.1.1, 8.8.8.8

Whitelisted subnets:

	172.17.0.0/16

	192.168.1.0/24

+ create_tun_device

+ mkdir -p /dev/net

+ [[ -c /dev/net/tun ]]

+ nordvpn connect Switzerland

-
  

-2020/07/26 03:22:54 PRE_CONNECT system info:

App Version: 3.7.4

OS Info:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"

NAME="Debian GNU/Linux"

VERSION_ID="10"

VERSION="10 (buster)"

VERSION_CODENAME=buster



n

HOME_URL="https://www.debian.org/"

SUPPORT_URL="https://www.debian.org/support"

BUG_REPORT_URL="https://bugs.debian.org/"

System Info:Linux fa46ceacc907 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 GNU/Linux

Routing Table:

default via 172.17.0.1 dev eth0 

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.4 

192.168.1.0/24 via 172.17.0.1 dev eth0 



:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 

IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A INPUT -s 192.168.1.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.1.0/24 -j ACCEPT

-A FORWARD -s 192.168.1.0/24 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -m owner --gid-owner 0 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.1.0/24 -j ACCEPT

nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT



:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

IP Set:

\
|
/
-
\
|
/
  
Connecting to Switzerland #234 (ch234.nordvpn.com)

-INFO: (nordlynx) 2020/07/26 03:22:55 Attaching to interface

INFO: (nordlynx) 2020/07/26 03:22:55 Interface set up

INFO: (nordlynx) 2020/07/26 03:22:55 Device started

\
|
/
-
\
|
/
-
\INFO: (nordlynx) 2020/07/26 03:23:25 Device closing

|INFO: (nordlynx) 2020/07/26 03:23:25 Interface closed

2020/07/26 03:23:25 got error: [failed to connect to nordlynx server]

  

-2020/07/26 03:23:25 POST_CONNECT system info:

Routing Table:

default via 172.17.0.1 dev eth0 

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.4 

192.168.1.0/24 via 172.17.0.1 dev eth0 



:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 

IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A INPUT -s 192.168.1.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.1.0/24 -j ACCEPT

-A FORWARD -s 192.168.1.0/24 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -m owner --gid-owner 0 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.1.0/24 -j ACCEPT

nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT



:

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

IP Set:

  
Whoops! We couldn't connect you to 'Switzerland'. Please try again. If the problem persists, contact our customer support.

+ exit 1

**Additional context**
The server was freshly installed a few days ago
Ubuntu 20.04.1 LTS
Docker 19.03.8

**Comment by LilDrunkenSmurf** [comment]
Did you resolve this? I was having similar issues. It would eventually show as "healthy", but I couldn't resolve any URLS. Curls to google would error out. Swapping to OpenVPN resolved it, but my connection speeds spike up, and then drop to a crawl.

**Comment by Crooklar** [comment]
I am now getting this as of yesturday.

I assume its since watchtower updated the image.

`time="2020-09-03T18:55:15+01:00" level=info msg="Found new bubuntux/nordvpn:latest image `

'-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT,
-A FORWARD -i lo -j ACCEPT,
-A FORWARD -d 172.17.0.0/16 -j ACCEPT,
-A FORWARD -s 172.17.0.0/16 -j ACCEPT,
-A FORWARD -d 192.168.1.0/24 -j ACCEPT,
-A FORWARD -s 192.168.1.0/24 -j ACCEPT,
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT,
-A OUTPUT -o lo -j ACCEPT,
-A OUTPUT -o tap+ -j ACCEPT,
-A OUTPUT -o tun+ -j ACCEPT,
-A OUTPUT -m owner --gid-owner 104 -j ACCEPT,
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT,
-A OUTPUT -d 192.168.1.0/24 -j ACCEPT,

nat:,
-P PREROUTING ACCEPT,
-P INPUT ACCEPT,
-P OUTPUT ACCEPT,
-P POSTROUTING ACCEPT,
-A POSTROUTING -o tap+ -j MASQUERADE,
-A POSTROUTING -o tun+ -j MASQUERADE,

mangle:,
-P PREROUTING ACCEPT,
-P INPUT ACCEPT,
-P FORWARD ACCEPT,
-P OUTPUT ACCEPT,
-P POSTROUTING ACCEPT,

:
-P PREROUTING ACCEPT,
-P OUTPUT ACCEPT,
 
Whoops! We couldn't connect you to 'UK'. Please try again. If the problem persists, contact our customer support.
,

**Comment by kernelstubbs** [comment]
Having this issue as well.

**Comment by therealklanni** [comment]
NordVPN support says there are issues with the latest version and Docker. Recommended I roll back to a previous version.

**Comment by quorn23** [comment]
@therealklanni confirming in the wrong thread, as you seen in my first post my issue is with version is 3.7.4

**Comment by therealklanni** [comment]
Well I was having this exact issue, but this fixed it for me.

```
Whoops! We couldn't connect you to 'United_States'. Please try again. If the problem persists, contact our customer support.
```

**Comment by LilDrunkenSmurf** [comment]
Yeah, this seems to be an issue with the nordvpn package in the docker image, rather than the image itself.

**Comment by LexJackson** [comment]
> NordVPN support says there are issues with the latest version and Docker. Recommended I roll back to a previous version.
> 
> UPDATE: confirmed, rolling back to version 3.7.4 resolves this issue (temporary fix).
> 
> Update your image to `bubuntux/nordvpn:3.7.4`. If using docker-compose run `docker-compose up -d --force-recreate` after updating.

Just wanted to say thanks for suggesting the roll-back. Works a treat for now.

**Comment by PriamX** [comment]
Confirmed here too. Rolling back to 3.7.4 as a temporary workaround did the trick.

**Comment by EckoEdc** [comment]
Same here, could only make it work with 3.7.4

**Comment by mikeholownych** [comment]
Seems this issue has been around for a while now. Has there been any progress on getting this to work beyond 3.7.4?

**Comment by ricardopt** [comment]
Yeah. This issue also happens to me.

**Comment by NikheelR97** [comment]
Issue still exists in 3.8.8

**Comment by quorn23** [comment]
> NordVPN support says there are issues with the latest version and Docker. Recommended I roll back to a previous version.
@therealklanni Could you contact them again and ask if they plan to fix this issue in this decade? (As it's still broken)

**Comment by therealklanni** [comment]
Anyone could contact them about it. I am still running on version 3.7.4. (If it ain't broke, don't fix it)

**Comment by w0ndersp00n** [comment]
I updated today to the newest image and this issue doesn't seem to occur. I think it's 3.9.1, but I was on 3..7.4 because of the same issue.

**Comment by bubuntux** [comment]
this seems like an issue with nordvpn itself and not this image, i added a retry just in case
